### ISSUE TITLE
Firestore 5.5.3 uses Symbol(Symbol.iterator) not supported by IE 11

### ISSUE THREAD

**Issue by harveylee** [firebase/firebase-js-sdk#1308]
* Operating System version: Windows 10
  * Browser version: Internet Explorer 11.345.17134.0
  * Firebase SDK version: 5.5.3
  * Firebase Product: firestore

#### Steps to reproduce:
1. Use Firebase JS SDK v5.5.3
2. Browse to page with Internet Explorer 11
3. Get error in console:
```
TypeError: Object doesn't support property or method 'Symbol(Symbol.iterator)_c.e9e7bht5pg3'
   at e.forEach (https://www.gstatic.com/firebasejs/5.5.3/firebase-firestore.js:1:187742)
   at e.prototype.onTransactionCommitted (https://www.gstatic.com/firebasejs/5.5.3/firebase-firestore.js:1:265406)
   at Anonymous function (https://www.gstatic.com/firebasejs/5.5.3/firebase-firestore.js:1:264146)
   at Anonymous function (https://www.gstatic.com/firebasejs/5.5.3/firebase-firestore.js:1:186886)
   at e.prototype.wrapUserFunction (https://www.gstatic.com/firebasejs/5.5.3/firebase-firestore.js:1:186729)
   at e.prototype.wrapSuccess (https://www.gstatic.com/firebasejs/5.5.3/firebase-firestore.js:1:186844)
   at e.prototype.next (https://www.gstatic.com/firebasejs/5.5.3/firebase-firestore.js:1:186251)
   at e.prototype.runTransaction (https://www.gstatic.com/firebasejs/5.5.3/firebase-firestore.js:1:264071)
   at e.prototype.start (https://www.gstatic.com/firebasejs/5.5.3/firebase-firestore.js:1:242380)
   at Anonymo
```

Note that this issue didn't occur with v5.5.2

#### Relevant Code:
```javascript
<script type='text/javascript' src='https://www.gstatic.com/firebasejs/5.5.3/firebase-firestore.js'></script>
```

**Comment by clintjansen** [comment]
Getting a similar error in React Native (Expo) after 5.3.1+ using the WebSDK

**Comment by cmacdonnacha** [comment]
I'm getting the same issue. Reverting back to 5.5.1 and it works

**Comment by schmidt-sebastian** [comment]
Thanks for reporting! We do have a Polyfill that is supposed to fix this. I will take a look tomorrow.

**Comment by schmidt-sebastian** [comment]
Are you also importing Firebase App?

**Comment by Feiyang1** [comment]
This also breaks our compatibility test in IE11. https://travis-ci.org/firebase/firebase-js-sdk/jobs/443437997#L1891
