### ISSUE TITLE
firebase.auth().signInWithPopup fails for sites running in an Electron BrowserWindow

### ISSUE THREAD

**Issue by diggabyte** [firebase/firebase-js-sdk#1334]
### Environment
  * Operating System version: `OS X 10.12.6`
  * Browser version: `Electron BrowserWindow` - `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36` '
  * Firebase SDK version: `4.7.1`
  * Firebase Product: `auth`

### Issue
`firebase.auth().signInWithPopup(provider)` fails to work when running a website from within an electron BrowserWindow.  Fails for both `FacebookAuthProvider` and `GoogleAuthProvider` (only ones I've tested). Works fine on the website, just fails in Electron, most likely due to the way popups are handled. 

#### Steps to reproduce:
1. Find a website that already uses `firebase.auth().signInWithPopup` and works as expected
2. Load website into an Electron BrowserWindow.
3. Attempt to authenticate the same way you would on the standard website
4. Observe the error handler is triggered with the following stacktrace:
```
TypeError: Cannot set property 'href' of null
    at Xe (https://www.gstatic.com/firebasejs/4.8.0/firebase.js:13:30361)
    at https://www.gstatic.com/firebasejs/4.8.0/firebase.js:13:109329
    at r.g (https://www.gstatic.com/firebasejs/4.8.0/firebase.js:13:8197)
    at mt (https://www.gstatic.com/firebasejs/4.8.0/firebase.js:13:9189)
    at vt (https://www.gstatic.com/firebasejs/4.8.0/firebase.js:13:9080)
    at Z.ou.Qb (https://www.gstatic.com/firebasejs/4.8.0/firebase.js:13:81801)
    at $ (https://www.gstatic.com/firebasejs/4.8.0/firebase.js:13:6669)
```

**Comment by prmichaelsen** [comment]
I have ran into this issue myself. Trying to integrate firebase auth into an electron app.

**Comment by bojeil-google** [comment]
Electron is not officially supported by Firebase Auth. Since Electron is a combination of a browser and Node.js server environment, some features may not work as expected, such as `signInWithPopup`. We'll treat this as a feature request.
For now, you can use some Electron supported OAuth library to get the OAuth credential, initialize a `firebase.auth.AuthCredential` and then sign in using `signInWithCredential`.

**Comment by prmichaelsen** [comment]
Bojeil, thank you for the response. I was not aware of sign in with credential. That will be useful.

**Comment by diggabyte** [comment]
I was able to get it to work via `signInWithRedirect` + `getRedirectResult`

**Comment by bojeil-google** [comment]
Interesting. Did you have to make any additional changes to your setup to get it to work?

**Comment by prmichaelsen** [comment]
I am also interested. I have just about finished my own implementation of OAuth flow, but this would be much easier.

**Comment by diggabyte** [comment]
My electron app wraps a website (using https://github.com/jiahaog/nativefier), so we are using a BrowserView around our site that already has the firebase social auth implementation. 

I had to make a change to authentication code to use `signInWithRedirect` when a flag is present indicating we are running inside the electron app. Futhermore, we treat `firebaseapp` urls as "internal" so that they don't open a new browser window. That permits the redirect to the firebaseapp urls and ultimately back to our website (still within the electron wrapper). 

Our web app always checks for `getRedirectResult` upon first load and proceeds with the existing flow if/when the result contains a valid user object (which only occurs upon successful redirect back from firebase).

**Comment by yanir21** [comment]
Any updates on this? as of 2024, `signInWithRedirect` doesn't work anymore.  

I found [this solution](https://sevenbits.hashnode.dev/demystifying-user-authentication-with-google-in-electron) but it's pretty quirky, and I wonder If Firebase would ever implement this feature
