### ISSUE TITLE
Can't find rollup.config.js file during `yarn install`?

### ISSUE THREAD

**Issue by zhaoyi0113** [firebase/firebase-js-sdk#1362]
I am trying to build this library with `yarn install` but I got `rollup.config.js` not found issue. Did it get missing in this repository?

**Comment by zhaoyi0113** [comment]
I mean this error happens when I run `npm install`.

**Comment by Feiyang1** [comment]
This repo is a monorepo using yarn workspace. You should use yarn instead of npm install.

**Comment by zhaoyi0113** [comment]
@Feiyang1  I use `yarn install` but get the same error as below. Is there any directory I need to run `yarn` or I should be able to run it from anywhere?

$ yarn install
yarn install v1.9.1
warning ../../package.json: No license field
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@firebase/auth > @firebase/auth-types@0.3.4" has unmet peer dependency "@firebase/app-types@0.x".
warning " > @firebase/database@0.3.6" has unmet peer dependency "@firebase/app-types@0.x".
warning "@firebase/database > @firebase/database-types@0.3.2" has unmet peer dependency "@firebase/app-types@0.x".
warning " > @firebase/firestore@0.8.6" has unmet peer dependency "@firebase/app-types@0.x".
warning "@firebase/firestore > @firebase/firestore-types@0.7.0" has unmet peer dependency "@firebase/app-types@0.x".
warning " > @firebase/functions@0.3.1" has unmet peer dependency "@firebase/app-types@0.x".
warning "@firebase/functions > @firebase/messaging-types@0.2.3" has unmet peer dependency "@firebase/app-types@0.x".
warning " > @firebase/messaging@0.3.6" has unmet peer dependency "@firebase/app-types@0.x".
warning " > @firebase/storage@0.2.4" has unmet peer dependency "@firebase/app-types@0.x".
warning "@firebase/storage > @firebase/storage-types@0.2.3" has unmet peer dependency "@firebase/app-types@0.x".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "1.12.3", while you're on "1.9.1".
info To upgrade, run the following command:
$ curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
$ npm run build

> firebase@5.5.7 build /Users/joeyzhao/dev/bigcrunch/extension/tbc/node_modules/firebase
> rollup -c

Error: ENOENT: no such file or directory, lstat '/Users/joeyzhao/dev/bigcrunch/extension/tbc/node_modules/firebase/rollup.config.js'
    at Object.realpathSync (fs.js:1649:15)
    at runRollup (/Users/joeyzhao/dev/node_modules/firebase/node_modules/rollup/bin/rollup:4028:29)
    at Object.<anonymous> (/Users/joeyzhao/dev/bigcrunch/extension/tbc/node_modules/firebase/node_modules/rollup/bin/rollup:4084:5)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
npm ERR! code ELIFECYCLE

**Comment by Feiyang1** [comment]
@zhaoyi0113 you need to be at the root folder of the repo. Why is it looking for firebase in node_modules?  Are you building firebase after you npm installed it in your project? It seems you are doing it in a non standard way.

Please describe your workflow including how you get the source code.

**Comment by zhaoyi0113** [comment]
You are right. The error happens because I didn't run it from root folder. However, when I tried to build from the root folder with `yarn dev` command, it stuck there and never finish:


```
@firebase/webchannel-wrapper: goog.net.WebChannel.Options.fastHandshake;
@firebase/webchannel-wrapper: ^^^^
@firebase/webchannel-wrapper: /Users/joeyzhao/dev/bigcrunch/firebase-js-sdk/packages/webchannel-wrapper/src/index.js:92: WARNING - variable module is undeclared
@firebase/webchannel-wrapper: module['exports'] = {
@firebase/webchannel-wrapper: ^^^^^^
@firebase/webchannel-wrapper: 0 error(s), 15 warning(s)
```
