### ISSUE TITLE
Errors installing via npm and yarn

### ISSUE THREAD

**Issue by JoeRoddy** [firebase/firebase-js-sdk#1404]
I could be doing something completely boneheaded, but I'm totally unable to add firebase to any project right now.

### [REQUIRED] Describe your environment

  * Operating System version: ubuntu 16.04
  * Browser version: n/a
  * Firebase SDK version: n/a
  * Firebase Product: n/a

### [REQUIRED] Describe the problem
I'm unable to install firebase to a project via either npm or yarn.

#### Steps to reproduce:
```
mkdir newproj
npm init
npm i --save firebase
```

Getting the same issue with firebase-admin, but I'm able to install other random dependencies, so I don't think it's npm.

### Error Logs
npm debug log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '--save',
1 verbose cli   'firebase' ]
2 info using npm@6.2.0
3 info using node@v10.9.0
4 verbose npm-session d894b7a551d832d8
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/firebase 15ms (from cache)
8 silly pacote tag manifest for firebase@latest fetched in 31ms
9 timing stage:loadCurrentTree Completed in 159ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 4ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule firebase@5.5.9 checking installable status
17 http fetch GET 401 https://registry.npmjs.org/@firebase%2fdatabase 164ms
18 silly fetchPackageMetaData error for @firebase/database@0.3.7 401 Unauthorized: @firebase/database@0.3.7
19 http fetch GET 401 https://registry.npmjs.org/@firebase%2ffirestore 171ms
20 silly fetchPackageMetaData error for @firebase/firestore@0.8.8 401 Unauthorized: @firebase/firestore@0.8.8
21 http fetch GET 401 https://registry.npmjs.org/@firebase%2fauth 221ms
22 silly fetchPackageMetaData error for @firebase/auth@0.7.9 401 Unauthorized: @firebase/auth@0.7.9
23 http fetch GET 401 https://registry.npmjs.org/@firebase%2fapp 228ms
24 http fetch GET 401 https://registry.npmjs.org/@firebase%2ffunctions 226ms
25 silly fetchPackageMetaData error for @firebase/app@0.3.5 401 Unauthorized: @firebase/app@0.3.5
26 silly fetchPackageMetaData error for @firebase/functions@0.3.3 401 Unauthorized: @firebase/functions@0.3.3
27 http fetch GET 401 https://registry.npmjs.org/@firebase%2fstorage 243ms
28 silly fetchPackageMetaData error for @firebase/storage@0.2.4 401 Unauthorized: @firebase/storage@0.2.4
29 http fetch GET 401 https://registry.npmjs.org/@firebase%2fmessaging 251ms
30 silly fetchPackageMetaData error for @firebase/messaging@0.3.7 401 Unauthorized: @firebase/messaging@0.3.7
31 http fetch GET 401 https://registry.npmjs.org/@firebase%2fpolyfill 300ms
32 silly fetchPackageMetaData error for @firebase/polyfill@0.3.3 401 Unauthorized: @firebase/polyfill@0.3.3
33 timing stage:rollbackFailedOptional Completed in 1ms
34 timing stage:runTopLevelLifecycles Completed in 477ms
35 silly saveTree deleteme@1.0.0
35 silly saveTree ├── firebase@5.5.9
35 silly saveTree └── lodash@4.17.11
36 verbose stack Error: 401 Unauthorized: @firebase/database@0.3.7
36 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
36 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
36 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
36 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
36 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
36 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
36 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
36 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
36 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
36 verbose stack     at runCallback (timers.js:693:18)
36 verbose stack     at tryOnImmediate (timers.js:664:5)
36 verbose stack     at processImmediate (timers.js:646:5)
37 verbose cwd /home/joe/Desktop/deleteme
38 verbose Linux 4.15.0-39-generic
39 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "--save" "firebase"
40 verbose node v10.9.0
41 verbose npm  v6.2.0
42 error code E401
43 error 401 Unauthorized: @firebase/database@0.3.7
44 verbose exit [ 1, true ]

----
yarn output:
error Couldn't find package "@firebase/app" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Couldn't find package "@firebase/messaging" on the "npm" registry.
    at /usr/share/yarn/lib/cli.js:49061:15
    at Generator.next (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:92:30)
    at /usr/share/yarn/lib/cli.js:103:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Couldn't find package "@firebase/auth" on the "npm" registry.
    at /usr/share/yarn/lib/cli.js:49061:15
    at Generator.next (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:92:30)
    at /usr/share/yarn/lib/cli.js:103:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Couldn't find package "@firebase/functions" on the "npm" registry.
    at /usr/share/yarn/lib/cli.js:49061:15
    at Generator.next (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:92:30)
    at /usr/share/yarn/lib/cli.js:103:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Couldn't find package "@firebase/storage" on the "npm" registry.
    at /usr/share/yarn/lib/cli.js:49061:15
    at Generator.next (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:92:30)
    at /usr/share/yarn/lib/cli.js:103:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Couldn't find package "@firebase/polyfill" on the "npm" registry.
    at /usr/share/yarn/lib/cli.js:49061:15
    at Generator.next (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:92:30)
    at /usr/share/yarn/lib/cli.js:103:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Couldn't find package "@firebase/firestore" on the "npm" registry.
    at /usr/share/yarn/lib/cli.js:49061:15
    at Generator.next (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:92:30)
    at /usr/share/yarn/lib/cli.js:103:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Couldn't find package "@firebase/database" on the "npm" registry.
    at /usr/share/yarn/lib/cli.js:49061:15
    at Generator.next (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:92:30)
    at /usr/share/yarn/lib/cli.js:103:13
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by JoeRoddy** [comment]
It's installing fine on my mac.  Both machines are running npm v6.2.0 & node v10.9.0.
