### ISSUE TITLE
Error to use firestore

### ISSUE THREAD

**Issue by higuitadiaz** [firebase/firebase-js-sdk#1419]
* Operating System version: _Linux Ubuntu 18.04____
  * Browser version: _Chrome____
  * Firebase SDK version: _5.7.0____
  * Firebase Product: _Firestore____ (auth, database, storage, etc)

Hello, 
I am using npm firebase in an Electron project, however, I am having problems when I try use the FireStore function, to start the program, the system is displaying the following error. check below

If I remove the firebase dependence or downgrade the version to 4.13, the system work 

`
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v3.0-linux-x64-glibc
Found: [node-v57-linux-x64-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/home/adrian/workspace/electron_projects/euruspro-desktop/node_modules/@firebase/firestore/node_modules/grpc/src/node/extension_binary/electron-v3.0-linux-x64-glibc/grpc_node.node'
    at Object.<anonymous> (/home/adrian/workspace/electron_projects/euruspro-desktop/node_modules/@firebase/firestore/node_modules/grpc/src/grpc_extension.js:53:17)
    at Object.<anonymous> (/home/adrian/workspace/electron_projects/euruspro-desktop/node_modules/@firebase/firestore/node_modules/grpc/src/grpc_extension.js:63:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/adrian/workspace/electron_projects/euruspro-desktop/node_modules/@firebase/firestore/node_modules/grpc/src/client_interceptors.js:145:12)`

Does anyone have any idea what to do? I'm losing the battle

![screenshot from 2018-12-07 14-51-24](https://user-images.githubusercontent.com/44470789/49664123-b6147100-fa2f-11e8-9c25-b345ca0d1238.png)

**Comment by mikelehen** [comment]
It would appear you're ending up with the node.js version of the SDK instead of the web version.  Electron isn't an officially supported environment right now, but @SlapBox recently had a similar issue and solved it in https://github.com/firebase/firebase-js-sdk/issues/1377 so maybe they can chime in on the best way to import firebase when using Electron...  Else, you can read through that thread and maybe get some ideas.

**Comment by Slapbox** [comment]
Using Firestore as a dependency in Electron is a nightmare because of the inclusion of gRPC. 

@higuitadiaz you can take a look at this issue and the links there, but I don't know if that's just going to  leave you with another issue: https://github.com/firebase/firebase-js-sdk/issues/1036
