### ISSUE TITLE
Testing: initializeAdminApp fails with `"projectId" not provided in firebase.initializeApp` if you also pass databaseName

### ISSUE THREAD

**Issue by sergeybekrin** [firebase/firebase-js-sdk#1445]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.14.2
  * Node version: v8.14.1
  * `firebase-admin`: 6.4.0
  * `@firebase/testing`: 0.5.1
  * Firebase Product: firestore

### [REQUIRED] Describe the problem

Hey there 👋

I'm trying to run tests locally via `@firebase/testing` and with emulated firestore, but apprently it fails due to `projectId` is [not being passed to `firebase.initializeApp`](https://github.com/firebase/firebase-js-sdk/blob/master/packages/testing/src/api/index.ts#L113). I'm not quite sure if it's intentional or not.

#### Steps to reproduce:

1. Import `@firebase/testing`
2. Call `.initializeAdminApp` from it

#### Relevant Code:

```javascript
const testing = require('@firebase/testing');

const app = testing.initializeAdminApp({
  projectId: 'foo',
  databaseName: 'bar'
});
```

#### Error:
```
FirebaseError: "projectId" not provided in firebase.initializeApp.
    at new FirestoreError (./node_modules/@firebase/firestore/dist/index.node.cjs.js:348:28)
    at Function.Firestore.databaseIdFromApp (./node_modules/@firebase/firestore/dist/index.node.cjs.js:19361:19)
    at new Firestore (./node_modules/@firebase/firestore/dist/index.node.cjs.js:19270:43)
    at Object.firestore (./node_modules/@firebase/firestore/dist/index.node.cjs.js:20613:79)
    at FirebaseAppImpl._getService (./node_modules/@firebase/app/dist/index.node.cjs.js:138:66)
    at FirebaseAppImpl.(anonymous function) [as firestore] (./node_modules/@firebase/app/dist/index.node.cjs.js:327:31)
    at initializeApp (./node_modules/@firebase/testing/dist/index.cjs.js:116:9)
    at Object.initializeAdminApp (./node_modules/@firebase/testing/dist/index.cjs.js:84:10)
    at [eval]:1:30
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
```

**Comment by mikelehen** [comment]
@ryanpbrewster It looks like the SDK is intended to be initialized with `projectId` OR `databaseName` but not both.  Is this intentional?  If so, perhaps we could throw an error if somebody tries...

**Comment by ryanpbrewster** [comment]
The next release of `@firebase/testing` will have more intuitive behavior in these cases. Thanks for the report!
