### ISSUE TITLE
Build failure when i use firebase 5.7.2 and ng build --prod  --base-href / --aot=true 

### ISSUE THREAD

**Issue by apunjaval** [firebase/firebase-js-sdk#1446]
* Operating System version:  Macos Sierra
  * Browser version: _____  Chrome 70
  * Firebase SDK version: _____ firebase 5.7.2
  * Firebase Product: _____ auth

When i build my code with ng build --prod --base-href / --aot=true the build fails , libraries used

{
  "name": "buyerdashboard",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/fire": "^5.1.1",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0",
    "angular-tabs-component": "^1.0.6",
    "angular4-carousel": "^3.1.8",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "firebase": "5.7.2",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "ng-simple-slideshow": "^1.2.3",
    "ng2-accordion": "0.0.15",
    "ngrok": "^3.0.1",
    "ngx-carousel": "^1.3.5",
    "rxjs": "^5.5.2",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.5.0",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
}

#### Steps to reproduce:

We get following error 

kshays-MacBook-Pro:valuates_buyer akshaypunja$ ng build --prod  --base-href / --aot=true 
Your global Angular CLI version (6.0.8) is greater than your local
version (1.5.0). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Date: 2019-01-02T11:55:12.242Z                                                          
Hash: 0bcef25313546c766f82
Time: 104990ms
chunk {0} polyfills.a44e9697145ea6c7de86.bundle.js (polyfills) 108 kB [initial] [rendered]
chunk {1} main.ec4c190ae56acd1b98e4.bundle.js (main) 2.73 MB [initial] [rendered]
chunk {2} styles.380c814f0b9bb7e54909.bundle.css (styles) 206 kB [initial] [rendered]
chunk {3} inline.a0de0b6ca49ba99b8321.bundle.js (inline) 1.45 kB [entry] [rendered]

ERROR in ./node_modules/@firebase/database/dist/index.cjs.js
Module build failed: TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (/Users/akshaypunja/apunja/code/production/buyerdashboard/valuates_buyer/node_modules/typescript/lib/typescript.js:9341:18)
    at assignContextualParameterTypes (/Users/akshaypunja/apunja/code/production/buyerdashboard/valuates_buyer/node_modules/typescript/lib/typescript.js:41652:25)
    at checkFunctionExpressionOrObjectLiteralMethod (/Users/akshaypunja/apunja/code/production/buyerdashboard/valuates_buyer/node_modules/typescript/lib/typescript.js:41948:29)
    at checkExpressionWorker (/Users/akshaypunja/apunja/code/production/buyerdashboard/valuates_buyer/node_modules/typescript/lib/typescript.js:42959:28)
    at checkExpression (/Users/akshaypunja/apunja/code/production/buyerdashboard/valuates_buyer/node_modules/typescript/lib/typescript.js:42898:42)
    at checkExpressionCached (/Users/akshaypunja/apunja/code/production/buyerdashboard/valuates_buyer/node_modules/typescript/lib/typescript.js:42779:38)
    at checkReturnStatement (/Users/akshaypunja/apunja/code/production/buyerdashboard/valuates_buyer/node_modules/typescript/lib/typescript.js:45418:54)
    at checkSourceElement (/Users/akshaypunja/apunja/code/production/buyerdashboard/valuates_buyer/node_modules/typescript/lib/typescript.js:46763:28)
    at Object.forEach (/Users/akshaypunja/apunja/code/production/buyerdashboard/valuates_buyer/node_modules/typescript/lib/typescript.js:1506:30)
    at checkBlock (/Users/akshaypunja/apunja/code/production/buyerdashboard/valuates_buyer/node_modules/typescript/lib/typescript.js:44563:16)
    at checkSourceElement (/Users/akshaypunja/apunja/code/production/buyerdashboard/valuates_buyer/node_modules/typescript/lib/typescript.js:46742:28)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred (/Users/akshaypunja/apunja/code/production/buyerdashboard/valuates_buyer/node_modules/typescript/lib/typescript.js:41990:21)
    at checkDeferredNodes (/Users/akshaypunja/apunja/code/production/buyerdashboard/valuates_buyer/node_modules/typescript/lib/typescript.js:46828:25)
    at checkSourceFileWorker (/Users/akshaypunja/apunja/code/production/buyerdashboard/valuates_buyer/node_modules/typescript/lib/typescript.js:46863:17)
    at checkSourceFile (/Users/akshaypunja/apunja/code/production/buyerdashboard/valuates_buyer/node_modules/typescript/lib/typescript.js:46842:13)
    at Object.forEach (/Users/akshaypunja/apunja/code/production/buyerdashboard/valuates_buyer/node_modules/typescript/lib/typescript.js:1506:30)
 @ ./node_modules/firebase/dist/index.cjs.js 8:0-29
 @ ./src/app/auth.service.ts
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts

**Comment by Feiyang1** [comment]
Though I don't know how exactly you import/use firebase, I went ahead and tried with the latest Angular CLI (7.1.4) and it works fine with firebase with the aot flag.
Then I downgraded the CLI version and other angular dependencies to match yours and got an error that's different from yours and is not coming from firebase.
I feel it's an issue with the old version of angular cli, which can be resolved by upgrading to the newer cli.
Are you able to upgrade the angular cli version and try again?

**Comment by apunjaval** [comment]
The root cause was we were using Angular 5 with latest version of
firebase,  After we upgraded to Angular 7 the issue got fixed.

Thank you for all the help.  Please close the defect with above information
for any one else looking for it.

*-Regards*
*Akshay Punja*

*Valuates Reports *




*Direct: +91-9845765095Address: Valuates , Balaraj's Arcade, India
Bangalore - 560066Website: https://reports.valuates.com
<https://reports.valuates.com/>Chief Technology Officer (CTO) - Valuates
Reports <https://reports.valuates.com/>Linked In
<https://www.linkedin.com/in/akshay-punja-83990a5/?originalSubdomain=in>*
