### ISSUE TITLE
Firebase install error with npm

### ISSUE THREAD

**Issue by dustinRDF** [firebase/firebase-js-sdk#1503]
### [REQUIRED] Describe your environment

  * Operating System version: (Lubuntu) Ubuntu 18.10 
  * Browser version: Chromium v71.0.3578.98
  * Node version: 10.15.0
  * npm version: 6.7.0
  * Firebase SDK version: 5.8.1
  * Firebase Product: firebase

### [REQUIRED] Describe the problem
Attempt to install firebase from command line using npm, but the build fails. According to the log it fails at the grpc@1.17.0 install  script. However, its showing an access error for mkdir. Which I find odd since I'm using sudo.
#### Steps to reproduce:

`sudo npm install -g firebase`

**Console error produced.**

>  dustin@dustin-pc ~: sudo npm install -g firebase                                                                      
> 
> \> grpc@1.17.0 install /usr/lib/node_modules/firebase/node_modules/grpc
> \> node-pre-gyp install --fallback-to-build --library=static_library
> 
> node-pre-gyp WARN Using needle for node-pre-gyp https download 
> node-pre-gyp WARN Pre-built binaries not installable for grpc@1.17.0 and node@10.15.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)                                                                                      
> node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/lib/node_modules/firebase/node_modules/grpc/src/node' 
> gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/dustin/.node-gyp/10.15.0"
> gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/firebase/node_modules/grpc/.node-gyp"
> gyp WARN install got an error, rolling back install
> gyp WARN install got an error, rolling back install
> gyp ERR! configure error 
> gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/firebase/node_modules/grpc/.node-gyp'
> gyp ERR! System Linux 4.18.0-10-generic
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/usr/lib/node_modules/firebase/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/usr/lib/node_modules/firebase/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
> gyp ERR! cwd /usr/lib/node_modules/firebase/node_modules/grpc
> gyp ERR! node -v v10.15.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok 
> node-pre-gyp ERR! build error 
> node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/usr/lib/node_modules/firebase/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/usr/lib/node_modules/firebase/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/firebase/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
> node-pre-gyp ERR! System Linux 4.18.0-10-generic
> node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/firebase/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
> node-pre-gyp ERR! cwd /usr/lib/node_modules/firebase/node_modules/grpc
> node-pre-gyp ERR! node -v v10.15.0
> node-pre-gyp ERR! node-pre-gyp -v v0.12.0
> node-pre-gyp ERR! not ok 
> Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/usr/lib/node_modules/firebase/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/usr/lib/node_modules/firebase/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! grpc@1.17.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the grpc@1.17.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/dustin/.npm/_logs/2019-01-29T16_37_08_141Z-debug.log

**Subsequent log file the error produces.**
[2019-01-29T08_54_20_952Z-debug.log](https://github.com/firebase/firebase-js-sdk/files/2808590/2019-01-29T08_54_20_952Z-debug.log)

**Comment by dustinRDF** [comment]
SOLVED:

Apparently it all had to with access permissions. Follow these [instructions](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) to manually change npm's default directory. You will no longer need to use the sudo command to install packages globally.
