### ISSUE TITLE
Building Firebase Node v10.16.0  fails because of dependency 

### ISSUE THREAD

**Issue by nadinejerome** [firebase/firebase-js-sdk#2041]
Node: v10.16.0
Firebase package: 6.3.3
Firebase installs properly on local development machine, but on the build server, it fails to install dependencies for node 10.16.x. No additional errors. I've also tried downgrading a couple of versions, but all the packages fail on the `grpc` package.

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.20.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Is there a version or beta version to support Node 10.16.xx+?

Ref:
https://cloud.google.com/functions/docs/concepts/nodejs-10-runtime

**Comment by nadinejerome** [comment]
Thank @Feiyang1, it's running with gitlab-runner 11.3.1. The firebase package is used for an Ionic app

**Comment by Feiyang1** [comment]
There is a similar issue I found on [stackoverflow](https://stackoverflow.com/questions/53139831/gitlab-ci-build-fails-for-grpc).
The issue is usually caused by gRPC not having a prebuilt binary for the specific Node version. 

What `image` do you use in `.gitlab-ci.yml`?
If you can share the detailed npm install log like the stackoverflow question does, it will also help use identify the problem.

**Comment by nadinejerome** [comment]
Thanks @Feiyang1, see below. Also, I am using a PaaS (Ionic Pro Build) so I do not have access to change the image.

```
[01:05:15]: fastlane finished with errors
/usr/local/bin/fastlane: [!] Exit status of command 'npm install --quiet --no-optional' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
npm WARN deprecated path-is-absolute@2.0.0: This package is no longer relevant as Node.js 0.12 is unmaintained.

> grpc@1.22.2 install /builds/App/Mobile.App/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for grpc@1.22.2 and node@10.16.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error tunneling socket could not be established, statusCode=404 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: tunneling socket could not be established, statusCode=404
gyp ERR! stack     at ClientRequest.onConnect (/usr/local/lib/node_modules/npm/node_modules/tunnel-agent/index.js:166:19)
gyp ERR! stack     at Object.onceWrapper (events.js:286:20)
gyp ERR! stack     at ClientRequest.emit (events.js:198:13)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:475:11)
gyp ERR! stack     at Socket.emit (events.js:198:13)
gyp ERR! stack     at addChunk (_stream_readable.js:288:12)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:269:11)
gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:224:10)
gyp ERR! stack     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
gyp ERR! System Linux 4.14.123-111.109.amzn2.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/builds/App/Mobile.App/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/builds/App/Mobile.App/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /builds/App/Mobile.App/node_modules/grpc
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/builds/App/Mobile.App/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/builds/App/Mobile.App/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess. (/builds/App/Mobile.App/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.14.123-111.109.amzn2.x86_64
node-pre-gyp ERR! command "/usr/local/bin/node" "/builds/App/Mobile.App/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /builds/App/Mobile.App/node_modules/grpc
node-pre-gyp ERR! node -v v10.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/builds/App/Mobile.App/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/builds/App/Mobile.App/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
```

**Comment by Feiyang1** [comment]
It looks like a network issue. Are you behind a proxy? 
I'm afraid there is not much we can do from the Firebase side. Can you please open an issue with `node-pre-gyp` to see if they can help?

**Comment by nadinejerome** [comment]
@Feiyang1 Will do! Thanks for your help.
