### ISSUE TITLE
Uncaught FirebaseError: Performance: Custom metric name _fp is invalid (performance/invalide custom metric name)

### ISSUE THREAD

**Issue by henrylearn2rock** [firebase/firebase-js-sdk#2108]
### [REQUIRED] Describe your environment

  * Operating System version: Win10
  * Browser version: Chrome Version 76.0.3809.100 (Official Build) (64-bit)
  * Firebase SDK version: 6.4.1
  * Firebase Product: performance

#### Steps to reproduce:
exception is thrown on load

```
index.cjs.js?6d09:1001 Uncaught FirebaseError: Performance: Custom metric name _fp is invalid (performance/invalide custom metric name).
    at Trace.putMetric (webpack-internal:///./node_modules/@firebase/performance/dist/index.cjs.js:1001:33)
    at Trace.incrementMetric (webpack-internal:///./node_modules/@firebase/performance/dist/index.cjs.js:986:18)
    at Function.Trace.createOobTrace (webpack-internal:///./node_modules/@firebase/performance/dist/index.cjs.js:1098:23)
    at eval (webpack-internal:///./node_modules/@firebase/performance/dist/index.cjs.js:1209:23)
    at eval (webpack-internal:///./node_modules/first-input-delay/src/first-input-delay.js:68:9)
    at Array.forEach (<anonymous>)
    at reportFirstInputDelayIfRecordedAndValid (webpack-internal:///./node_modules/first-input-delay/src/first-input-delay.js:67:17)
    at recordFirstInputDelay (webpack-internal:///./node_modules/first-input-delay/src/first-input-delay.js:51:7)
    at onInput (webpack-internal:///./node_modules/first-input-delay/src/first-input-delay.js:142:9)
```

#### Relevant Code:
none needed

**Comment by bogacg** [comment]
I did report same error in @angular/fire since I am using it with Angular and it got updated same day so wasn't really sure which lib is the incompatible one. In my case it happened when service worker is introduced in the mix. https://github.com/angular/angularfire2/issues/2154

**Comment by alikn** [comment]
Thanks for reporting the issue. Please update to the latest version. It should be fixed as of this pr:
https://github.com/firebase/firebase-js-sdk/pull/2110
