### ISSUE TITLE
breaking after upgrading to firebase > 7 messaging/no-sw-in-reg

### ISSUE THREAD

**Issue by sibelius** [firebase/firebase-js-sdk#2524]
### [REQUIRED] Describe your environment

  * Operating System version: macOs
  * Browser version: Chrome
  * Firebase SDK version: 7.6.2
  * Firebase Product: messaging (auth, database, storage, etc)

#### Steps to reproduce:

Upgrade from 6.4.1 to 7.6.2

is it safe to add all firebaseConfig on web?

```jsx
const firebaseConfig = {
  messagingSenderId: 'messagingSenderId',
  apiKey: 'apiKey',
  authDomain: 'authDomain',
  databaseURL: 'databaseURL',
  projectId: 'projectId',
  storageBucket: 'storageBucket,
  appId: 'appId',
};
```

on v6, you could just use `messagingSenderId`

The error is:

```jsx
getToken err:  FirebaseError: Messaging: Even though the service worker registration was successful, there was a problem accessing the service worker itself. (messaging/no-sw-in-reg).
    at eval (webpack-internal:///../../node_modules/@firebase/messaging/dist/index.esm.js:1964:37)
    at new Promise (<anonymous>)
    at WindowController.waitForRegistrationToActivate_ (webpack-internal:///../../node_modules/@firebase/messaging/dist/index.esm.js:1961:16)
    at WindowController.getSWRegistration_ (webpack-internal:///../../node_modules/@firebase/messaging/dist/index.esm.js:2000:25)
    at WindowController.eval (webpack-internal:///../../node_modules/@firebase/messaging/dist/index.esm.js:1055:51)
```

#### Relevant Code:

https://stackblitz.com/fork/firebase-issue-sandbox

```javascript
export const useSWReg = () => {
  const onTokenRefresh = useRef<firebase.Unsubscribe>(null);
  const onMessage = useRef<firebase.Unsubscribe>(null);

  useEffect(() => {
    // TODO - use workbox-window
    const registerSW = async () => {
      if (!firebase.messaging.isSupported()) {
        return;
      }

      if ('serviceWorker' in navigator) {
        const registration = await navigator.serviceWorker.getRegistration('/home/sw.js');

        if (!registration) {
          return;
        }

        firebase.initializeApp(firebaseConfig);

        const messaging = firebase.messaging();

        messaging.usePublicVapidKey(config.FIREBASE_VAPID);
        messaging.useServiceWorker(registration);

        try {
          const permission = await Notification.requestPermission();

          if (permission === 'granted') {
            const token = await messaging.getToken();

            await sendPushToServer(token);
          }
        } catch (err) {
          if (err.code === 'messaging/permission-blocked') {
            // eslint-disable-next-line
            console.log('Please Unblock Notification Request Manually: ', err);
          } else {
            // eslint-disable-next-line
            console.log('getToken err: ', err);
          }
        }

        onTokenRefresh.current = messaging.onTokenRefresh(async () => {
          const token = await messaging.getToken();

          // eslint-disable-next-line
          console.log('token refresh: ', token);

          // TODO - validate if user is logged in
          await sendPushToServer(token);
        });

        onMessage.current = messaging.onMessage(payload => {
          // eslint-disable-next-line
          console.log('Notification Received', payload);

          const { data } = payload;

          // TODO - show local notification
          // this is the function that gets triggered when you receive a
          // push notification while you’re on the page. So you can
          // create a corresponding UI for you to have the push
          // notification handled.

          registration.showNotification(data.title, {
            vibrate: [200],
            // icon: '/img/apple-icon-144x144-precomposed.png',
            // badge: '/img/badge.png',
            body: data.body,
            title: data.title,
            // timestamp: data.from, notificationData.timestamp,
            // image: notificationData.image,
            // tag: notificationData.tag,
            data,
            // If we don't set a tag and set renotify to true this'll throw an error
            // renotify: notificationData.renotify || !!notificationData.tag,
          });
        });

        navigator.serviceWorker.addEventListener('message', event => {
          // eslint-disable-next-line
          console.log('SW message: ', event);
        });
      }
    };

    registerSW();

    return () => {
      if (onTokenRefresh.current) {
        onTokenRefresh.current();
      }

      if (onMessage.current) {
        onMessage.current();
      }
    };
  }, []);
};
```

**Comment by itsalb3rt** [comment]
> is it safe to add all firebaseConfig on web?

No. If you use a framework like Vue, React, Angula, put all credentials in `env `variable and call then in the `firebase config` file

**Comment by sibelius** [comment]
isn't putting then .env the same as exposing them on web?

**Comment by itsalb3rt** [comment]
> isn't putting then .env the same as exposing them on web?

Theoretically not, because the variable is destroyed after being used in your code, unless you do not use secure network protocols and webpack especially to obfuscate the code.

**Comment by itsalb3rt** [comment]
> > isn't putting then .env the same as exposing them on web?
> 
> Theoretically not, because the variable is destroyed after being used in your code, unless you do not use secure network protocols and webpack especially to obfuscate the code.

if you want to feel that your environment variables are safer, keep an eye on this
[https://www.npmjs.com/package/secure-env](https://www.npmjs.com/package/secure-env)

**Comment by sibelius** [comment]
this is not true, no env is safe on frontend

**Comment by itsalb3rt** [comment]
> this is not true, no env is safe on frontend

think the following, if it were not safe there would be no firebase SDK for the front-end

**Comment by rommelpe** [comment]
Sorry about the slow response, @sibelius. Are you still encountering the error? Could I ask you to go a bit further and provide a working repro with a detailed steps that we can run locally?

The code snippet is useful, but this is likely hard to repro, so getting a complete mcve will be a necessary starting point.
