### ISSUE TITLE
auth/network-request-failed when debugging on react native

### ISSUE THREAD

**Issue by shirlev-wix** [firebase/firebase-js-sdk#2652]
### [REQUIRED] Describe your environment

  * Operating System version: Mac 10.14.6
  * Browser version: Chrome Version 79.0.3945.130
  * Firebase SDK version: 6.6.2
  * Firebase Product: auth (auth, database, storage, etc)
  * **React Native version**: 0.61.5

### [REQUIRED] Describe the problem
Getting an error when running on debug mode on the simulator (both for ios and android)
```
code: "auth/network-request-failed"
message: "A network error (such as timeout, interrupted connection or unreachable host) has 
occurred."
```
* Works fine on the simulator when I'm not debugging.
* Happens also for other teammates that work on the same project
* Rebooting Chrome didn't help
#### Relevant Code:

I created a small react native app to reproduce the bug:
https://github.com/shirlev-wix/firebase-bug

```javascript
return Promise.resolve()
        .then(() => firebase.initializeApp(options, this.name))
        .then(app => app.auth().signInWithCustomToken(authKey)
```

Thanks!

**Comment by rommelpe** [comment]
Thanks for the report, @shirlev-wix. While I'm trying to replicate this, can you try using the latest version ([7.8.2](https://firebase.google.com/support/release-notes/js))? Most of these reports tend to be network related. If you can get network logs, that would be very helpful.

**Comment by rommelpe** [comment]
@shirlev-wix I'm trying to reproduce this issue but haven't been able to. Putting your working repro up on [StackBlitz](https://stackblitz.com/fork/react) would be very helpful as we could fork it and might help you get it running. Thanks!

**Comment by shirlev-wix** [comment]
Hi,
Upgrading firebase didn't help.
I created a small react native app to reproduce the bug.
https://github.com/shirlev-wix/firebase-bug

When debugging you can see the UI stays not connected.

**Comment by shirlev-wix** [comment]
Hi @rommelpe! Any updates regarding this one?
It is really making our life harder when trying to debug things related to firebase.

**Comment by jayawasthi** [comment]
same issue --- 

code: "auth/network-request-failed",
 message: "A network error (such as timeout, interrupted connection or unreachable host) has occurred."

    "firebase": "^7.13.2",
    "react": "16.9.0",
    "react-native": "0.61.5",

**Comment by kishansbs** [comment]
same issue -- 

code: "auth/network-request-failed", message: "A network error (such as timeout, interrupted connection or unreachable host) has occurred."

    "firebase": "^7.13.2",
    "react": "16.9.0",
    "react-native": "0.61.5",

**Comment by nyenye** [comment]
Not sure is the same, but I get a an error saying I have no connection on my device on an Android Emulator, but making requests with i.e. unfetch library, work just fine.

**Comment by berndartmueller** [comment]
Our users experience the same `auth/network-request-failed` firebase auth issues since some time now. It mainly happens to Android Chrome users and the issue start immediately after/during using `firebase.auth().signInAnonymously`. (Note: I'm not using react, I simply use plain old Node.js SSR with vanilla js)

I'm also having a hard time reproducing the issue, I tried many real devices as well as devices on Browserstack. I'm just not getting this issue.

I already made sure that
- there is no `form` html tag used
- the call to action button is a `<button type='button'>Signup</button>` element
- no session cookie/token revocation happens

Any ideas or any idea how I could reproduce it myself? Thanks a lot!

**Comment by jefelewis** [comment]
I'm receiving the same issue with React. I was testing logging in and it was returning a user object. 10 or so times later, it just stopped working and I have got the message `Error: A network error (such as timeout, interrupted connection or unreachable host) has occurred.` for the past 12 hours.

    "firebase": "^7.15.1",
    "react": "^16.13.1",
    "redux": "^4.0.5",
    "redux-persist": "^6.0.0",
    "redux-saga": "^1.1.3",
    "redux-saga-firebase": "^0.15.0"

**Comment by HassanAbass** [comment]
I'm facing the same error when trying to use google/facebook signing with popup, used to work before and nothing change in the code.

```
//version
"firebase": "^7.15.5"

let provider = new firebase.auth.GoogleAuthProvider();
firebase.auth().signInWithPopup(provider).then(e => ...)
```

**Comment by mogwely** [comment]
Im facing the same error using google to sign in with signInWithPopup. Works for some users just fine but fails for other users.
//version
"firebase": "^7.15.5"

**Comment by frietkip** [comment]
I am running into the same error using google to sign to next js. Both on local, development and production. 
![image](https://user-images.githubusercontent.com/41699402/87509315-8e58a680-c671-11ea-9218-4e9e2e28bf4e.png)

"firebase": "^7.14.2",

Please advice

**Comment by avolkovi** [comment]
Folks-

Thanks for reporting this, does anyone have a trace for the endpoint and underlying error (like in https://github.com/firebase/firebase-js-sdk/issues/3081#issuecomment-631589480)? The Network Error you are seeing is a generic error we throw when the underlying fetch() call fails.

**Comment by HassanAbass** [comment]
In my case with signInWithPopup the pop up url (app-name/__/auth/...) was unreachable and not redirect to facebook/google happens, it worked again days later without changing anything.

**Comment by shirlev-wix** [comment]
What kind of information do you need?
Like I wrote on March 6, here's a demo project that reproduce the bug:
https://github.com/shirlev-wix/firebase-bug

**Comment by obrunopolo** [comment]
I'm having the same issue with a React Native Expo app. All of the sudden I cant make any development and I'm stuck with this unexpected error.

**Comment by yzalvov** [comment]
@obrunopolo , I faced with network problems on Android working with Expo too. I don't have a permanent solution, though two things work for me while developing:
- Using a DNS proxy 8.8.8.8 for Android emulator.
- Using a cell provider network on my dev Android device instead of any WiFi networks.

I hope this will help you for development and there will be a fix from Firebase team soon.

**Comment by Georgemburu** [comment]
I had the same Error.
I solved it by Turning on the my phones internet connection by connecting to wifi.

**Solution**
Turn on your phone's internet connection.

**Comment by obrunopolo** [comment]
@Georgemburu that is not a "solution". Do you believe someone would come to GitHub and comment on this Issue just because the internet connection isn't on? I had this issue on a specific private wifi connection, all apps were working fine, except for mine.

**Comment by emad-ir** [comment]
Any updates on this issue? I am getting ```[Error: [auth/network-request-failed] A network error has occurred, please try again.]``` when I try to ```auth().signInWithPhoneNumber(phoneNumber)```

This only happens when Im testing on Iphone device for me.

```
"react-native": "0.63.3",
"@react-native-firebase/app": "^8.4.5",
"@react-native-firebase/auth": "^9.2.7",
```

**Comment by emad-ir** [comment]
So I was having a similar issue where I was getting ```[Error: [auth/network-request-failed] A network error has occurred, please try again.]``` on and IOS phone whenever I tried to ```auth().signInWithPhoneNumber(phoneNumber)``` 

And the reason for that was because the Date and Time on the phone was wrong 🤷🏻‍♂️

**Comment by rosalyntan** [comment]
Hi all, this issue is being tracked internally at b/171738114. It's on our radar to investigate, but unfortunately we don't have a timeline for this right now.

**Comment by MittalShruti** [comment]
I am getting the same error, while using google-auth in react, on chrome browser. 
The authentication was working fine just yesterday. 
I am using a button to call the authentication function.

`<button id="login">LOG IN</button>`

**Comment by avinashg-wal** [comment]
It's November 2020, firebase login was working fine until yesterday, but now it does not work anymore.
It always throws `auth/network-request-failed` error 👎 

<img width="1437" alt="Screenshot 2020-11-02 at 1 40 41 PM" src="https://user-images.githubusercontent.com/47351043/97844419-02968300-1d11-11eb-94fb-0cf7afc8bc54.png">

**Comment by avinashg-wal** [comment]
@google-oss-bot  @shirlev-wix @Georgemburu

**Comment by rameshvishnoi90904** [comment]
Any updates on this? some of my users started facing this issue, and are stuck out of app.

**Comment by viv3kk** [comment]
> In my case with signInWithPopup the pop up url (app-name/__/auth/...) was unreachable and no redirect to facebook/google happens, it worked again days later without changing anything.

We are also facing this issue. On one particular occasion, we tried to debug the cause for 4 hours and then it was back to working.
Another in most of the cases, changing the network connection (from broadband to mobile hotspot) helped get around this issue.

Recently I faced this issue twice on consecutive Mondays.

**Comment by viv3kk** [comment]
> @Georgemburu that is not a "solution". Do you believe someone would come to GitHub and comment on this Issue just because the internet connection isn't on? I had this issue on a specific private wifi connection, all apps were working fine, except mine.

@obrunopolo Yes I agree this is not the issue. Although this is mostly not an issue related to network and firebase should get some help if changing networks solves this issue.
I have also switched between 2 working connection, but it works on one network and fails on another.

**Comment by rahul-96** [comment]
Same error/issue. Suddenly. Did not change anything. It was working a while back perfectly. Pasting my error in the log which I'm getting from the
code 
```
firebase.auth().signInWithPopup(provider).then(function (result) {
...
}).catch(function (error) {
      // Handle Errors here.
      var errorCode = error.code;
      var errorMessage = error.message;
      // The email of the user's account used.
      var email = error.email;
      // The firebase.auth.AuthCredential type that was used.
      var credential = error.credential;
      console.log(error); //This it the error being consoled.
    }); 
```

The error in console:

_> u {code: "auth/network-request-failed", message: "A network error (such as timeout, interrupted connection or unreachable host) has occurred.", a: null}
> a: null
> code: "auth/network-request-failed"
> message: "A network error (such as timeout, interrupted connection or unreachable host) has occurred."
> __proto__: Error
> constructor: ƒ u(a, b, c)
> Za:
> constructor: ƒ Error()
> message: ""
> name: "Error"
> toString: ƒ toString()
> __proto__: Object
> arguments: (...)
> caller: (...)
> length: 3
> name: "u"
> prototype: Error {constructor: ƒ, v: ƒ, toJSON: ƒ}
> __proto__: ƒ ()
> [[FunctionLocation]]: auth.esm.js:411
> [[Scopes]]: Scopes[4]
> toJSON: ƒ d()
> v: ƒ ()
> __proto__: Object_

Please help. Is there nay development on this issue? The error is coming in production. Users are not able to login. Please help. Thank you so much in advance.

**Comment by viv3kk** [comment]
> Same error/issue. Suddenly. Did not change anything. It was working a while back perfectly. Pasting my error in the log which I'm getting from the
> code 
> ```
> firebase.auth().signInWithPopup(provider).then(function (result) {
> ...
> }).catch(function (error) {
>       // Handle Errors here.
>       var errorCode = error.code;
>       var errorMessage = error.message;
>       // The email of the user's account used.
>       var email = error.email;
>       // The firebase.auth.AuthCredential type that was used.
>       var credential = error.credential;
>       console.log(error); //This it the error being consoled.
>     }); 
> ```
> 
> The error in console:
> 
> _> u {code: "auth/network-request-failed", message: "A network error (such as timeout, interrupted connection or unreachable host) has occurred.", a: null}
> > a: null
> > code: "auth/network-request-failed"
> > message: "A network error (such as timeout, interrupted connection or unreachable host) has occurred."
> > __proto__: Error
> > constructor: ƒ u(a, b, c)
> > Za:
> > constructor: ƒ Error()
> > message: ""
> > name: "Error"
> > toString: ƒ toString()
> > __proto__: Object
> > arguments: (...)
> > caller: (...)
> > length: 3
> > name: "u"
> > prototype: Error {constructor: ƒ, v: ƒ, toJSON: ƒ}
> > __proto__: ƒ ()
> > [[FunctionLocation]]: auth.esm.js:411
> > [[Scopes]]: Scopes[4]
> > toJSON: ƒ d()
> > v: ƒ ()
> > __proto__: Object_
> 
> Please help. Is there nay development on this issue? The error is coming in production. Users are not able to login. Please help. Thank you so much in advance.

Please check if changing network solves this issue. I am also facing this issue with firebase-js-sdk..
It is very bad experience

**Comment by rahul-96** [comment]
> Same error/issue. Suddenly. Did not change anything. It was working a while back perfectly. Pasting my error in the log which I'm getting from the
> code
> 
> ```
> firebase.auth().signInWithPopup(provider).then(function (result) {
> ...
> }).catch(function (error) {
>       // Handle Errors here.
>       var errorCode = error.code;
>       var errorMessage = error.message;
>       // The email of the user's account used.
>       var email = error.email;
>       // The firebase.auth.AuthCredential type that was used.
>       var credential = error.credential;
>       console.log(error); //This it the error being consoled.
>     }); 
> ```
> 
> The error in console:
> 
> _> u {code: "auth/network-request-failed", message: "A network error (such as timeout, interrupted connection or unreachable host) has occurred.", a: null}
> 
> > a: null
> > code: "auth/network-request-failed"
> > message: "A network error (such as timeout, interrupted connection or unreachable host) has occurred."
> > **proto**: Error
> > constructor: ƒ u(a, b, c)
> > Za:
> > constructor: ƒ Error()
> > message: ""
> > name: "Error"
> > toString: ƒ toString()
> > **proto**: Object
> > arguments: (...)
> > caller: (...)
> > length: 3
> > name: "u"
> > prototype: Error {constructor: ƒ, v: ƒ, toJSON: ƒ}
> > **proto**: ƒ ()
> > [[FunctionLocation]]: auth.esm.js:411
> > [[Scopes]]: Scopes[4]
> > toJSON: ƒ d()
> > v: ƒ ()
> > **proto**: Object_
> 
> Please help. Is there nay development on this issue? The error is coming in production. Users are not able to login. Please help. Thank you so much in advance.

It somehow just started working back again. No errors or issue anymore. Pretty sure it's some issue deep in the firebase-JS sdk since many people faced it the same way.

**Comment by code-odyssey-trunk** [comment]
![WhatsApp Image 2020-11-12 at 10 41 31 AM](https://user-images.githubusercontent.com/72135089/99353331-b117f780-28bd-11eb-9504-a52416f8b409.jpeg)
I am also facing the same issue, and this is how it is happening to me. 
Mine is a react native app using expo. Firebase login is working fine in both expo and standalone app from my home network. 
But I sent apk file to my few friends, and one friend said he is getting this error (Error: A network error (such as timeout, interrupted connection or unreachable host) has occurred). He tried on multiple android phones (Pixel 4 and One plus nord). 
When he came to my home I tried to login from his phone and it worked. 
So now the firebase auth is working in my home network but not from my friend's.

**Comment by akushylun** [comment]
Some of my users getting this issue in angular version 10. 
Does some known workaround exist? Downgrade the firebase to some version?

`"@angular/core": "~10.2.0",
"firebase": "8.0.2",`

**Comment by fersucho** [comment]
Hey guys, I was having the same issue in an AngularJS app. In this comment: 
https://github.com/firebase/firebase-js-sdk/issues/20#issuecomment-313236458
It is explained that Firebase checks for navigator.online before doing the auth process, and sometimes (and in some cases, always) it receives a wrong answer. By adding the cordova-plugin-network-information to the project, it provides the correct answer to Firebase and the app works again. 
In my case, I tried with version 2.0.2 of the plugin without success, and then with version 1.2.1 and, my app started to work fine.

**Comment by SpectorHacked** [comment]
Also having this issue using Expo, can't connect through Specific Wifi, connected 3 clients to the same network
1 works and 2 doesn't work, using Expo SDK 39. Any Updates?

**Comment by HasanAboShally** [comment]
I'm facing the same issue! Any update or workarounds please?

**Comment by HasanAboShally** [comment]
In my case the issue was resolved by changing the `authDomain` to {{APP_ID}}.firebaseapp.com instead of {{APP_ID}}.web.app

**Comment by lewischa** [comment]
Seeing the same issue here on `firebase@8.2.6`.

- Tried switching networks.
- Ensured my `authDomain` is {{APP_ID}}.firebaseapp.com
- `navigator.onLine` is `true`
- Even tried deleting my firebase project and re-creating it.
- Button is not inside a `<form>` element. I also tried just attaching a function to `window`, completely removing a button from the equation - no dice:
    ```javascript
    import firebase from 'firebase/app';
    import 'firebase/auth';
    import 'firebase/firestore';

    import { firebaseConfig } from './config';

    firebase.initializeApp(firebaseConfig);

    export const auth = firebase.auth();

    auth.onAuthStateChanged((user) => {
        console.log('firebase user:', user);
    });

    const GoogleProvider = new firebase.auth.GoogleAuthProvider();

    export const logInWithGoogle = () => {
        auth.signInWithPopup(GoogleProvider)
            .then((result) => {
                console.log('LOGGED IN!!! User:', result.user);
            })
            .catch((error) => {
                console.log('LOGIN ERROR!! :(', error);
            });
    };

    export const logInWithEmail = (email, password) => {
        auth.signInWithEmailAndPassword(email, password)
            .then((user) => {
                console.log('User signed in via email:', user);
            })
            .catch((error) => {
                console.log('error signing in with email:', error);
            });
    };

    // Invoking this results in the same `auth/network-request-failed` error
    window.testLogin = logInWithGoogle;
    ```

Was planning to switch from AWS for a small project but looks like this issue's been around for almost a year now. Got stoked at how easy things are supposed to be to set up, and immediately ran into this!! 😬 😞

**Comment by HellBlazer616** [comment]
Well we were having the same issue on our website. Turns out for us the problem was that we switched hosting from firebase to vercel. And the route that was loading the pop up "_example.com/__auth/apiKey?..._ " was not free anymore. Chrome was not showing anything but firefox was showing our 404 page. So, we figured it was a DNS issue. We got it to working by switching to the default auth domain. We are now working on configuring a custom auth sub domain for our site. I will post an update if we figure that out

**Comment by ayyfahim** [comment]
I was facing the same issue. It turned out that I was caching everything on my service worker js file. So I disabled these domains.
`if (
        url.origin === "https://securetoken.googleapis.com" ||
        url.origin === "https://apis.google.com" ||
        url.origin === "https://www.googleapis.com"
    ) {
        return;
    }`

**Comment by iamdevlinph** [comment]
Our react app is suddenly this issue. Already disabled service workers. Also verified the Sign in with Google button is not in a form.

**Comment by tuancaraballo** [comment]
Running into the same issue. Have tried everything said here, except for switching to a different product :(

**Comment by emthomas** [comment]
facing the same on flutter in iOS.

**Comment by emthomas** [comment]
Ok not sure if that is the case for react-native, but for me and flutter, looks like it was a caching issue. Once I do clean with flutter clean (which cleans my XCode workspace, build folder, cache, etc...) it works fine.

**Comment by Adefunke** [comment]
Had the same issue but discovered that I was not passing in strings into 'createUserWithEmailAndPassword', I was passing in elements. Once, I switched to strings, I stopped getting auth/network-request-failed error.

**Comment by mayankkataria** [comment]
I'm still facing this issue with firebase emulator on angular. Is there any solution or workaround for it?

**Comment by mayankkataria** [comment]
> I'm still facing this issue with firebase emulator on angular. Is there any solution or workaround for it? And I'm shocked that it's still open since 2 years.

**Comment by rupakhetibinit** [comment]
Well, looks like it's still not fixed because I'm facing the same error.

**Comment by lghimfus** [comment]
@code-odyssey-trunk, @SpectorHacked (hope you were not really hacked)

Did you find out eventually what was causing the issue?

I'm facing the same issue and it's a really weird one. I have to switch through the wifi networks and it somehow eventually works...

**Comment by mogwely** [comment]
> 

I can second this behavior. I tell my users to switch networks and use their phones hotspot to go around this issue.

**Comment by mogwely** [comment]
I'm sure firebase team either don't care or don't know how to solve this issue, but they are definitely aware of it. There has been countless tickets and SO questions regrding that issue.

**Comment by qq280948982** [comment]
Had the same issue

**Comment by lewiscasewell** [comment]
I have the same issue too. Works fine in mobile browsers, however, when downloading PWA, get (auth/network-request-failed) error

**Comment by FortyXD** [comment]
Look, this can happen because the function does not have enough time to execute. Make it asynchronous. I solved the problem this way

**Comment by rpelissier** [comment]
Hello I have what seems to be the same issue. 

## Context
- Operating System version: Mac 12.4
- Firebase SDK version: ^9.8.4
- React version :  ^18
- React-Script : ^5.0.1
- Firebase Product: auth

## Issue

```shell
FirebaseError: Firebase: Error (auth/network-request-failed).

      at createErrorInternal (node_modules/@firebase/auth/src/core/util/assert.ts:123:7)
      at _fail (node_modules/@firebase/auth/src/core/util/assert.ts:65:28)
      at node_modules/@firebase/auth/src/api/index.ts:180:5
      at step (node_modules/tslib/tslib.js:144:27)
      at Object.throw (node_modules/tslib/tslib.js:125:57)
      at rejected (node_modules/tslib/tslib.js:116:69)
```

I created a [project to demo it](https://github.com/rpelissier/firebase-auth-bug).

## Workaround

Wait a little after `getAuth()` before invoking `signInWithEmailAndPassword()`.

## Root cause analysis

My guess : `the client socket is closing before the packet is acknowledged by the server.`

I found out by using Wireshark to monitor the TCP Packets between the Jest test and the Auth Emulator.
Doing so I could see that the first packet returned to the client has a TCP Reset (RST).

According to what I read on the web it means :
> The packet arrives on a TCP connection that was previously established, but the local 
> application already closed its socket or exited and the OS closed the socket.

**Comment by guptavishesh143** [comment]
I also faced the same issue, but while switching the data networks it started working! I switched from Wifi to Mobile Data.

**Comment by jacob0123456** [comment]
I have the same issue. But I didn't find the solution yet. How can I fix that?

**Comment by Maracaipe611** [comment]
Same problem here...
My dependencies:
`{
   "firebase": "^9.12.1",
   "next": "12.2.5",
   "react": "18.2.0",
}`

Error message: `Firebase: Error (auth/network-request-failed).`
I already checked all my authorized domains in console.firebase, and the other's requests like login & signing is fine. Just the reset password give me this error

**Comment by wendelfreitas** [comment]
Still happening when I try to mock firebase rest API using `nock` on jest


```js
  "dependencies": {
    "@react-query-firebase/auth": "^1.0.0-dev.2",    "firebase": "^9.12.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-query": "^3.39.2",
    "react-router-dom": "^6.4.2",
  },
```

**Comment by SSOURABH58** [comment]
> 
Hi, can you elaborate on the steps? 
I am unable to get the DNS firebase layer part where exactly do I have to replace the `localhost` with `127.0.0.1`?
( in my code or in the firebase or cloud console ??)
<img width="852" alt="image" src="https://user-images.githubusercontent.com/52000724/198989581-79793ea1-d06c-4052-9de6-2e8d9b63390e.png">

**Comment by jacob0123456** [comment]
Hello.
Could you tell me about you please?

**Comment by MarioBatalha** [comment]
Someone here already solved this issue?

**Comment by Rutvik17** [comment]
I am having the same issue, after some research I came across this https://github.com/firebase/firebase-js-sdk/issues/6322#issuecomment-1146598147 seems like configuring firebase for web in react native has an edge case. The emulators connect to different ports and causes the issue. Though I am not sure how to change my port on expo for the emulator. I tried creating a `firebase.json` file in the root folder and specify the ports and then run `firebase emulators:start` but it does not start the emulator. Errors out saying 
```error
Error when trying to check port 9099 on 10.0.2.2: Error: listen EADDRNOTAVAIL: address not available 10.0.2.2:9099
```
any suggestions ?

**Comment by Rutvik17** [comment]
> * S proxy 8.8.8.8 for Android emulator.

Is this only a development issue or also happens on production. I am also facing the same issue. How do you set DNS proxy ?

**Comment by ssmdssmp** [comment]
For me solution was just to reload emulator. It suddenly had a pour connection, what I checked with db, so for me it was just an emulator bug.

**Comment by hsubox76** [comment]
It seems like a number of workarounds, solutions and causes have been suggested in this thread:
- bad connection, just retry
- emulator uses a different port (unsure how to change it)
- use 127.0.0.1 instead of localhost
- make functions asynchronous so that they run after a delay

If anyone's experiencing this problem and none of those causes/workarounds seem to apply (or you have more details about a cause), please open a new issue with a full description of how to consistently reproduce the problem you are seeing.

**Comment by brloman** [comment]
@hsubox76 The whole point is that the error is inconsistent and the error message is too generic. I have been experiencing this issue for a very long time on and off while having a stable connection, and none of these suggestions resolve it for me. It just disappears and happens again. This is by no means complete.
