### ISSUE TITLE
Cant connect to firestore.

### ISSUE THREAD

**Issue by harisvsulaiman** [firebase/firebase-js-sdk#267]
* Operating System version: elementary os loki Linux4.13.6+
  * Firebase SDK version: 4.6.0
  * Firebase Product: firestore

#### Steps to reproduce:
1. install firebase sdk 
2. start script with node `node ./index.js`

#### Error 
```
➔ node index.js
module.js:529
    throw err;
    ^

Error: Cannot find module '/home/harisvsulaiman/node_modules/grpc/src/node/extension_binary/grpc_node.node'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/harisvsulaiman/node_modules/grpc/src/node/src/grpc_extension.js:45:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```
#### Relevant Code:
```javascript
let firebase = require("firebase");
// Required for Side Effects
require("@firebase/firestore");
require("firebase/auth");

const config = {
  apiKey: "",
  authDomain: "",
  databaseURL: "",
  projectId: ""
};

firebase.initializeApp(config);

firebase
  .firestore()
  .collection("users")
  .add({ kdskd: "dsd" })
  .then(params => {
    console.log(params);
  })
  .catch(err => {
    console.log(err);
  });

```

**Comment by goldensunliu** [comment]
@harisvsulaiman this is the same as issue https://github.com/firebase/firebase-js-sdk/issues/221
here is the temp solution I have been using: https://github.com/firebase/firebase-js-sdk/issues/221#issuecomment-337103110
feel free to close this one

**Comment by harisvsulaiman** [comment]
@goldensunliu Closing this in favour of #221

**Comment by goldensunliu** [comment]
@harisvsulaiman close?

**Comment by jshcrowthe** [comment]
@goldensunliu @harisvsulaiman I'm assuming this was meant to be closed.

**Comment by harisvsulaiman** [comment]
@jshcrowthe sorry, i forgot to close!

**Comment by alexandregiordanelli** [comment]
firestore is not working on the server side.. I have exactly this problem
