### ISSUE TITLE
FR: Allow Firestore to connect to a URL with firestore.settings

### ISSUE THREAD

**Issue by ValentaTomas** [firebase/firebase-js-sdk#3043]
### Describe your environment
- Operating System version: MacOS 10.15.2
- Firebase SDK version: 7.14.3
- Firebase Product: firestore

### Describe the problem
When using Firestore in the client SDK you can redirect calls to a running Firestore emulator with `firestore().settings({ host: <hostname>, ssl: false });`. Would it be possible to allow redirecting to a URL instead of just to a hostname? Similarly to how `functions().useFunctionsEmulator(<url>);` works with URLs.

Error when trying to use URL instead of a hostname:
```
(node:65330) UnhandledPromiseRejectionWarning: Error: Failed to parse target localhost:5002/firestore
    at Function.getDefaultAuthority (/Users/valenta.and.thomas/Developer/client-test/client/node_modules/@grpc/grpc-js/build/src/resolver-dns.js:263:15)
    at Object.getDefaultAuthority (/Users/valenta.and.thomas/Developer/client-test/client/node_modules/@grpc/grpc-js/build/src/resolver.js:73:32)
    at new ChannelImplementation (/Users/valenta.and.thomas/Developer/client-test/client/node_modules/@grpc/grpc-js/build/src/channel.js:79:48)
    at new Client (/Users/valenta.and.thomas/Developer/client-test/client/node_modules/@grpc/grpc-js/build/src/client.js:57:36)
    at new ServiceClientImpl (/Users/valenta.and.thomas/Developer/client-test/client/node_modules/@grpc/grpc-js/build/src/make-client.js:49:5)
    at GrpcConnection.ensureActiveStub (/Users/valenta.and.thomas/Developer/client-test/client/node_modules/@firebase/firestore/dist/index.node.cjs.js:22655:31)
    at GrpcConnection.openStream (/Users/valenta.and.thomas/Developer/client-test/client/node_modules/@firebase/firestore/dist/index.node.cjs.js:22700:25)
    at PersistentWriteStream.startRpc (/Users/valenta.and.thomas/Developer/client-test/client/node_modules/@firebase/firestore/dist/index.node.cjs.js:9518:32)
    at PersistentWriteStream.PersistentStream.startStream (/Users/valenta.and.thomas/Developer/client-test/client/node_modules/@firebase/firestore/dist/index.node.cjs.js:9344:28)
    at /Users/valenta.and.thomas/Developer/client-test/client/node_modules/@firebase/firestore/dist/index.node.cjs.js:9331:23
```

I would gladly make the PR.
Thanks

**Comment by wu-hui** [comment]
Hi, thanks for the feature request and offering to draft a PR!

Before a PR, I'd like to understand what exactly are you proposing though. Can you spell out how you imagine settings will be created and used?

My concern here is adding a `url` leads to potential conflicts with `ssl`, in that `http/https` in the `url` might be different than what `ssl` is set to. We need to have a way to resolve that.

But maybe I misunderstand your proposal?

Thanks!

**Comment by ValentaTomas** [comment]
In our company, we wanted to run and connect to the Firestore Emulator behind a proxy on a specific route - `<hostname>/firestore`.
We now realized that the Emulator communicates via gRPC so such routing is effectively out of the picture.

Feel free to close this issue.

**Comment by samtstern** [comment]
@ValentaTomas yeah as you said we can't really support a specific route, it has to be just the host/port so that the rest of our code can easily adapt.

Sorry for the slow response!
