### ISSUE TITLE
"Cannot parse Firebase url" on snapshot reference access when using RTDB via firebase functions.

### ISSUE THREAD

**Issue by filipesilva** [firebase/firebase-js-sdk#3451]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Chrome 84
  * Firebase SDK version: 7.16.1
  * Firebase Product: database

### [REQUIRED] Describe the problem

It's currently not possible to access the data snapshot reference when using RTDB via firebase functions.

I believe this is due to the check in https://github.com/firebase/firebase-js-sdk/blob/6af4c27743372ba531e8ce3d046ae2f81e8f5be1/packages/database/src/core/util/libs/parser.ts#L83-L91 

That piece of code checks that `parsedUrl.domain` is `localhost`, but it seems to be `emulator-test-1.localhost` instead.

#### Steps to reproduce:
```
git clone https://github.com/filipesilva/firebase-emulator-parse-url
cd firebase-emulator-parse-url
yarn
yarn emulators
# open http://localhost:5001/emulator-test-1/us-central1/posts in the browser
```

You should see the following error log in the console:
```
i  functions: Beginning execution of "postsPushHandler"
>  [2020-07-22T15:49:53.227Z]  @firebase/database: FIREBASE FATAL ERROR: Cannot parse Firebase url. Please use https://<YOUR FIREBASE>.firebaseio.com
!  functions: Error: FIREBASE FATAL ERROR: Cannot parse Firebase url. Please use https://<YOUR FIREBASE>.firebaseio.com
    at fatal (D:\sandbox\firebase-emulator-parse-url\node_modules\@firebase\database\dist\index.node.cjs.js:341:11)
    at parseRepoInfo (D:\sandbox\firebase-emulator-parse-url\node_modules\@firebase\database\dist\index.node.cjs.js:1296:9)
    at RepoManager.databaseFromApp (D:\sandbox\firebase-emulator-parse-url\node_modules\@firebase\database\dist\index.node.cjs.js:14990:25)
    at Object.initStandalone (D:\sandbox\firebase-emulator-parse-url\node_modules\@firebase\database\dist\index.node.cjs.js:15389:45)
    at DatabaseService.getDatabase (D:\sandbox\firebase-emulator-parse-url\node_modules\firebase-admin\lib\database\database.js:67:23)
    at FirebaseApp.database (D:\sandbox\firebase-emulator-parse-url\node_modules\firebase-admin\lib\firebase-app.js:232:24)
    at DataSnapshot.get ref [as ref] (D:\sandbox\firebase-emulator-parse-url\node_modules\firebase-functions\lib\providers\database.js:293:34)
    at D:\sandbox\firebase-emulator-parse-url\functions\index.js:17:24
    at cloudFunction (D:\sandbox\firebase-emulator-parse-url\node_modules\firebase-functions\lib\cloud-functions.js:132:23)
    at D:\sandbox\firebase-emulator-parse-url\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:573:20
!  Your function was killed because it raised an unhandled error.
```
#### Relevant Code:

```javascript
exports.postsPushHandler = functions.database.ref('/posts/{postId}').onCreate(snapshot => {
  console.log(snapshot.ref)
});
```

**Comment by filipesilva** [comment]
cc @samtstern (because I've reported other emulator related issues to you)

**Comment by samtstern** [comment]
@filipesilva what version of `firebase-functions` are you using?  This should be fixed in version `3.8.0` (assuming newest version of the CLI as well)

**Comment by filipesilva** [comment]
The repro (https://github.com/filipesilva/firebase-emulator-parse-url) is using firebase-functions@3.8.0. Everything there is the latest as of today, I believe.

**Comment by samtstern** [comment]
@filipesilva sorry I should have clicked into that

**Comment by samtstern** [comment]
Ok a few things here:

1. I was able to reproduce this
2. If I change the initialization block to just `admin.initializeApp()` This error goes away.

**Comment by samtstern** [comment]
It looks like `parseRepoInfo()` is being called with a URL like:
```
https://emulator-test-1.localhost
```

This is a `firebase-functions` issue, transferring.
