### ISSUE TITLE
@firebase/testing cannot use FieldValue object as firestore data.

### ISSUE THREAD

**Issue by mogaming217** [firebase/firebase-js-sdk#3483]
### Describe your environment

  * Operating System version: macOS 10.15.5
  * Browser version: none
  * Firebase SDK version: 
    * firebase-admin: 9.0.0 and 8.13.0 (both version occured)
    * @firebase/testing: 0.20.9
  * Firebase Product: Firestore

I use @firebase/testing and firebase-admin, and test the backend(admin) code using firestore. All packages are lastest version.

#### Steps to reproduce:
 `npm install` and `npm run test`, then error occured.

```
FirebaseError: Function DocumentReference.set() called with invalid data. Unsupported field value: a custom object (found in field createdAt in document users/JFLlyHHRCKcm08HOt2UQ)

      4 | 
      5 | const updateWithAdmin = (db: firestore.Firestore) => {
    > 6 |   return db.collection('users').doc().set({
        |                                       ^
      7 |     hello: 1,
      8 |     createdAt: firestore.FieldValue.serverTimestamp()
      9 |   })

      at new FirestoreError (node_modules/@firebase/firestore/src/util/error.ts:166:5)
      at createError (node_modules/@firebase/firestore/src/api/user_data_reader.ts:858:10)
      at ParseContext.createError (node_modules/@firebase/firestore/src/api/user_data_reader.ts:267:12)
      at validatePlainObject (node_modules/@firebase/firestore/src/api/user_data_reader.ts:772:21)
      at parseData (node_modules/@firebase/firestore/src/api/user_data_reader.ts:569:5)
      at node_modules/@firebase/firestore/src/api/user_data_reader.ts:620:27
      at forEach (node_modules/@firebase/firestore/src/util/obj.ts:40:7)
      at parseObject (node_modules/@firebase/firestore/src/api/user_data_reader.ts:619:5)
      at parseSetData (node_modules/@firebase/firestore/src/api/user_data_reader.ts:363:22)
      at DocumentReference.set (node_modules/@firebase/firestore/src/api/database.ts:1089:20)
      at updateWithAdmin (rules.test.ts:6:39)
      at rules.test.ts:40:7
      at rules.test.ts:9:71
      at __awaiter (rules.test.ts:5:12)
      at Object.it (rules.test.ts:38:24)
```

#### Relevant Code:
Here is minimum reproducing project.
https://github.com/mogaming217/firestore-invalid-data

```typescript
// This is production codes.

import { firestore } from 'firebase-admin'

const updateWithAdmin = (db: firestore.Firestore) => {
  return db.collection('users').doc().set({
    hello: 1,
    createdAt: firestore.FieldValue.serverTimestamp()
  })
}

// Test code

import * as firebase from '@firebase/testing'
import * as fs from 'fs'
const projectID = 'sample'
const databaseName = 'database'
const rules = fs.readFileSync('./firestore.rules', 'utf8')

// firestore client for admin
const adminDB = firebase.initializeAdminApp({ projectId: projectID, databaseName }).firestore()

// setup and clean up

beforeAll(async () => {
  await firebase.loadFirestoreRules({ projectId: projectID, rules });
})

beforeEach(async () => {
  await firebase.clearFirestoreData({ projectId: projectID });
})

afterAll(async () => {
  await Promise.all(firebase.apps().map(app => app.delete()));
})

describe('/users', () => {
  it('ok ', async () => {
    await firebase.assertSucceeds(
      updateWithAdmin(adminDB as any)
    )
  })
})
```

**Comment by wilhuff** [comment]
Apologies for the confusion, but this configuration isn't intended to work. See [discussion and how to adjust your tests](https://github.com/firebase/firebase-js-sdk/issues/3105#issuecomment-634875244) in a prior issue on this topic.

The TL;DR on this is:
  * `@firebase/testing` is intended to be used for testing rules only
  * Just connect to the emulator directly when testing admin SDK code

The underlying problem is that `@firebase/testing` is based on the Web SDK, but you're exercising the Admin SDK. Though these interfaces look similar they're actually different and incompatible types.

/cc @schmidt-sebastian @yuchenshi
