### ISSUE TITLE
SDK 7.5.1+ cause an error when loading firebase.auth() with Jest + TypeScript

### ISSUE THREAD

**Issue by goodpic** [firebase/firebase-js-sdk#3505]
### [REQUIRED] Describe your environment

  * Operating System version:  mac OS 10.15.5 
  * Node version: v12.18.3
  * Firebase SDK version: 7.5.1
  * Firebase Product: auth

### [REQUIRED] Describe the problem

The following jest test case works fine with SDK 7.5.0 or earlier but cause an error with SDK 7.5.1 or later.
Is there any difference between 7.5.0 and 7.5.1? 

https://github.com/goodpic/expo-jest-firebase/blob/master/src/__tests__/firebase.spec.ts

```
 PASS  src/__tests__/firebase.spec.ts
  UseProduct
    ✓ fetchProduct (157 ms)

  console.log
    Error: addEventListener and attachEvent are unavailable.
        at goog.events.listen_ (/Users/junkaneko/workspace/expo-jest-firebase/node_modules/@firebase/node_modules/google-closure-library/closure/goog/events/events.js:280:15)
        at goog.events.listen (/Users/junkaneko/workspace/expo-jest-firebase/node_modules/@firebase/node_modules/google-closure-library/closure/goog/events/events.js:189:12)
        at ak.addStorageListener [as $] (/Users/junkaneko/workspace/expo-jest-firebase/node_modules/@firebase/auth/dist/src/storage/localstorage.js:172:5)
        at pk.addListener (/Users/junkaneko/workspace/expo-jest-firebase/node_modules/@firebase/auth/dist/src/authstorage.js:459:3)
        at new Am (/Users/junkaneko/workspace/expo-jest-firebase/node_modules/@firebase/auth/dist/src/storageusermanager.js:107:3)
        at new Km (/Users/junkaneko/workspace/expo-jest-firebase/node_modules/@firebase/auth/dist/src/auth.js:121:7)
        at Object.instanceFactory (/Users/junkaneko/workspace/expo-jest-firebase/node_modules/@firebase/auth/dist/src/exports_auth.js:679:16)
        at Provider.getOrInitializeService (/Users/junkaneko/workspace/expo-jest-firebase/node_modules/@firebase/component/src/provider.ts:187:33)
        at Provider.getImmediate (/Users/junkaneko/workspace/expo-jest-firebase/node_modules/@firebase/component/src/provider.ts:95:29)
        at FirebaseAppImpl._getService (/Users/junkaneko/workspace/expo-jest-firebase/node_modules/@firebase/app/src/firebaseApp.ts:127:54)

      at src/__tests__/firebase.spec.ts:16:15
```

#### Steps to reproduce:

``` 
git clone https://github.com/goodpic/expo-jest-firebase.git
```

Place the firebase config file under /config/firebase.ts

``` 
const projectId = 'YOUR_PROJECT_ID'
export const firebaseConfig = {
  projectId,
  apiKey: YOUR_API_KEY,
  authDomain: `${projectId}.firebaseapp.com`,
  databaseURL: `https://${projectId}.firebaseio.com`,
  storageBucket: `${projectId}.appspot.com`,
}
``` 

then run jest

``` 
npm install
npm run test
```

**Comment by goodpic** [comment]
Found out that it works as expected if I remove the following config from jest.config.js

```
  "preset": "jest-expo",
```

https://github.com/goodpic/expo-jest-firebase/commit/2dadd693bef1b37ac9221c5985803d9250a4ebde#r41011908

I will look into jest-expo
