### ISSUE TITLE
Error: Cannot find module “@firebase/polyfill”

### ISSUE THREAD

**Issue by rashid-softordi** [firebase/firebase-js-sdk#355]
After running ionic serve command facing this eorror: **Error: Cannot find module “@firebase/polyfill”**

### [REQUIRED] Describe your environment

  * Operating System version: _____OS : 

> macOS Sierra
> Xcode : Xcode 9.1 Build version 9B55

  * Firebase SDK version: _____
```
"@ionic-native/firebase": "^4.1.0",
"angularfire2": "^5.0.0-rc.2"
"firebase": "^4.5.1",
"promise-polyfill": "6.0.2",
```

* Working environment:

> cli packages:
> @ionic/cli-utils : 1.19.0
> ionic (Ionic CLI) : 3.19.0
> global packages:
> 
> cordova (Cordova CLI) : 7.1.0
> local packages:
> 
> @ionic/app-scripts : 2.1.4
> Cordova Platforms : none
> Ionic Framework : ionic-angular 3.9.2
> System:
> 
> Node : v8.9.1
> npm : 5.1.0
> 

#### Steps to reproduce:
Error: Cannot find module "@firebase/polyfill"
    at webpackMissingModule (http://localhost:8100/build/vendor.js:71203:65)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:71203:160)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:71154:71)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:109392:79)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:109376:72)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:36504:70)#### Relevant Code:

https://forum.ionicframework.com/t/error-cannot-find-module-firebase-polyfill/114595

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by rashid-softordi** [comment]
This error is fixed.

> npm install @firebase/polyfill
