### ISSUE TITLE
INTERNAL ASSERT FAILED: Unexpected transaction status in abort

### ISSUE THREAD

**Issue by dsafreno** [firebase/firebase-js-sdk#3552]
Hey Firebase team,

We are seeing crashes with the above error. Looks like it comes from this line.

https://github.com/firebase/firebase-js-sdk/blob/2fa0353dda82c291dc4d1e97a9dd471b28af9995/packages/database/src/core/Repo_transaction.ts#L769

Based on your documentation, I think doing transactions / sets to the same place is not good practice, so we'll update the code to not use a transaction and see if that fixes things. However, I'd guess there's some internal issue for "Internal assert" to be raised, so I wanted to flag it for you.

**Comment by dsafreno** [comment]
Whoops, updating with some additional info:
- Firebase v7.9.3
- Environment: seems to occur in many, Sentry is showing Chrome and Electron, most of our users use one or the other.
- Stacktrace
```
Error: Firebase Database (${JSCORE_VERSION}) INTERNAL ASSERT FAILED: Unexpected transaction status in abort
  at assertionError(../../src/assert.ts:33:10)
  at assert(../../src/assert.ts:25:11)
  at abortTransactionsOnNode_(../../src/core/Repo_transaction.ts:763:9)
  at action(../../src/core/Repo_transaction.ts:718:10)
  at forEachAncestor(../../src/core/util/Tree.ts:169:11)
  at abortTransactions_(../../src/core/Repo_transaction.ts:717:19)
  at setWithPriority(../../src/core/Repo.ts:346:31)
  at set(../../src/api/Reference.ts:141:15)
  at d(<removing our code line>)
  at Ii(../node_modules/react-dom/cjs/react-dom.production.min.js:211:320)
  at Vj(../node_modules/react-dom/cjs/react-dom.production.min.js:257:303)
  at If(../node_modules/scheduler/cjs/scheduler.production.min.js:19:467)
  at cg(../node_modules/react-dom/cjs/react-dom.production.min.js:122:325)
  at Dj(../node_modules/react-dom/cjs/react-dom.production.min.js:257:58)
  at yj(../node_modules/react-dom/cjs/react-dom.production.min.js:239:100)
  at b(../node_modules/react-dom/cjs/react-dom.production.min.js:123:115)
  at If(../node_modules/scheduler/cjs/scheduler.production.min.js:19:467)
  at cg(../node_modules/react-dom/cjs/react-dom.production.min.js:122:325)
  at fg(../node_modules/react-dom/cjs/react-dom.production.min.js:123:61)
  at gg(../node_modules/react-dom/cjs/react-dom.production.min.js:122:496)
  at Ig(../node_modules/react-dom/cjs/react-dom.production.min.js:230:156)
  at zh(../node_modules/react-dom/cjs/react-dom.production.min.js:163:512)
  at call(<removing our code line>)
  at fn(../../src/core/view/EventRegistration.ts:133:12)
  at exceptionGuard(../../src/core/util/util.ts:588:5)
  at raise(../../src/core/view/EventQueue.ts:171:9)
  at raiseQueuedEventsMatchingPredicate_(../../src/core/view/EventQueue.ts:123:31)
  at raiseEventsForChangedPath(../../src/core/view/EventQueue.ts:103:10)
  at rerunTransactionQueue_(../../src/core/Repo_transaction.ts:564:22)
  at rerunTransactions_(../../src/core/Repo_transaction.ts:452:8)
  at onComplete(../../src/core/Repo_transaction.ts:427:14)
  at onResponse(../../src/core/PersistentConnection.ts:544:9)
  at onMessage_(../../src/core/PersistentConnection.ts:579:9)
  at onDataMessage_(../../src/realtime/Connection.ts:319:10)
  at onPrimaryMessageReceived_(../../src/realtime/Connection.ts:311:12)
  at onMessage(../../src/realtime/Connection.ts:207:16)
  at appendFrame_(../../src/realtime/WebSocketConnection.ts:278:12)
  at handleIncomingFrame(../../src/realtime/WebSocketConnection.ts:333:14)
  at WebSocket.mySock.onmessage(../../src/realtime/WebSocketConnection.ts:197:12)
```

**Comment by DellaBitta** [comment]
Hi @dsafreno,

It's been a while. Checking in to see if this still an issue that you're encountering. Thanks!
