### ISSUE TITLE
TypeError: Cannot read property 'enqueueSegment' of null

### ISSUE THREAD

**Issue by AVVS** [firebase/firebase-js-sdk#356]
### Describe your environment

  * Operating System version: Windows 10, Chrome 62
  * Firebase SDK version: https://github.com/firebase/firebase-js-sdk/commit/e979cc7793ee0a4f1c22590e4635f975615627b6
  * Firebase Product: database

```
TypeError: Cannot read property 'enqueueSegment' of null
  at send (../node_modules/@firebase/database/dist/cjs/src/realtime/BrowserPollConnection.js:281:1)
  at proceedWithUpgrade_ (../node_modules/@firebase/database/dist/cjs/src/realtime/Connection.js:244:1)
  at upgradeIfSecondaryHealthy_ (../node_modules/@firebase/database/dist/cjs/src/realtime/Connection.js:227:1)
  at onSecondaryControl_ (../node_modules/@firebase/database/dist/cjs/src/realtime/Connection.js:204:1)
  at onSecondaryMessageReceived_ (../node_modules/@firebase/database/dist/cjs/src/realtime/Connection.js:212:1)
...
(4 additional frame(s) were not displayed)
```

**Comment by schmidt-sebastian** [comment]
@AVVS, can you post the dependency list in your package.json file?

**Comment by AVVS** [comment]
```js
  "dependencies": {
    "@firebase/app": "^0.1.4",
    "@firebase/auth": "^0.3.0",
    "@firebase/database": "^0.1.5",
    "@firebase/storage": "^0.1.4",
    "auth0-js": "^8.12.1",
    "axios": "^0.17.1",
    "bluebird": "^3.5.1",
    "cappasity-icons": "^2.0.2",
    "classnames": "^2.2.5",
    "crypto-js": "^3.1.9-1",
    "ethereum-address": "^0.0.4",
    "format-number": "^3.0.0",
    "gridle": "^2.0.48",
    "i18next": "^10.2.1",
    "i18next-browser-languagedetector": "^2.0.0",
    "idtoken-verifier": "^1.1.0",
    "json-stringify-safe": "^5.0.1",
    "localforage": "^1.5.5",
    "locize-editor": "^1.3.0",
    "lodash": "^4.17.4",
    "material-ui": "^0.20.0",
    "moment": "2.20.0",
    "node-sass-chokidar": "^0.0.3",
    "npm-run-all": "^4.1.2",
    "prop-types": "^15.5.10",
    "qrcode.react": "^0.7.2",
    "qs": "^6.5.1",
    "ramda": "^0.25.0",
    "random-string": "^0.2.0",
    "react": "^16.2.0",
    "react-autosuggest": "^9.3.2",
    "react-copy-to-clipboard": "^5.0.0",
    "react-cryptocoins": "1.0.10",
    "react-dom": "^16.2.0",
    "react-flag-icon-css": "^1.0.19",
    "react-helmet": "^5.2.0",
    "react-i18next": "^6.2.0",
    "react-redux": "^5.0.6",
    "react-redux-firebase": "=2.0.0-beta.17",
    "react-router-dom": "^4.2.2",
    "react-router-redux": "^5.0.0-alpha.8",
    "react-scripts": "^1.0.17",
    "recompose": "^0.26.0",
    "redux": "^3.7.2",
    "redux-actions": "^2.2.1",
    "redux-form": "^7.2.0",
    "redux-form-material-ui": "^4.3.1",
    "redux-persist": "4.x.x",
    "redux-persist-transform-filter": "^0.0.16",
    "redux-promise": "^0.5.3",
    "redux-thunk-fsa": "^4.0.1",
    "reselect": "^3.0.1",
    "serializerr": "^1.0.3",
    "validator": "^9.2.0",
    "webfontloader": "^1.6.28"
  },
```

There is also a lock file to actually pin versions and installed version is `0.1.5`

**Comment by rommelpe** [comment]
@AVVS, I would like to check if you are still having the issue. If so, could you share a [simple repro ](https://stackoverflow.com/help/minimal-reproducible-example)that I could run locally? 

You may also consider upgrading your JS SDK to the [latest version](https://firebase.google.com/support/release-notes/js).
