### ISSUE TITLE
Cannot install firebase testing

### ISSUE THREAD

**Issue by siper92** [firebase/firebase-js-sdk#3572]
I'm running 
  * Operating System version: Ubuntu 18.04.4 LTS
  * npm version:  **6.14.5**
  * node version: **v13.5.0**

I cannot install the @firebase/testing when running
```bash
npm i --save-dev @firebase/testing --loglevel verbose
```
this is what I get
```
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/home/todd/.nvm/versions/node/v13.5.0/bin/node',
npm verb cli   '/home/todd/.nvm/versions/node/v13.5.0/bin/npm',
npm verb cli   'i',
npm verb cli   '--save-dev',
npm verb cli   '@firebase/testing',
npm verb cli   '--loglevel',
npm verb cli   'verbose'
npm verb cli ]
npm info using npm@6.14.5
npm info using node@v13.5.0
npm verb npm-session 379e3325b967570c
npm http fetch GET 200 https://registry.npmjs.org/@firebase%2ftesting 13ms (from cache)
npm timing stage:loadCurrentTree Completed in 56ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 72ms
npm http fetch GET 200 https://registry.npmjs.org/@firebase%2futil 35ms (from cache)
npm http fetch GET 404 https://registry.npmjs.org/@firebase%2flogger 100ms
npm http fetch GET 304 https://registry.npmjs.org/request 128ms (from cache)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm http fetch GET 404 https://registry.npmjs.org/@firebase%2flogger 35ms
npm http fetch GET 304 https://registry.npmjs.org/firebase 150ms (from cache)
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 302ms
npm verb stack Error: 404 Not Found - GET https://registry.npmjs.org/@firebase%2flogger - Not found
npm verb stack     at /home/todd/.nvm/versions/node/v13.5.0/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15
npm verb stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm verb statusCode 404
npm verb pkgid @firebase/logger@0.2.6
npm verb cwd /var/www/Projects/talen-hub/website/test
npm verb Linux 4.17.0-041700-generic
npm verb argv "/home/todd/.nvm/versions/node/v13.5.0/bin/node" "/home/todd/.nvm/versions/node/v13.5.0/bin/npm" "i" "--save-dev" "@firebase/testing" "--loglevel" "verbose"
npm verb node v13.5.0
npm verb npm  v6.14.5
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@firebase%2flogger - Not found
npm ERR! 404 
npm ERR! 404  '@firebase/logger@0.2.6' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@firebase/testing'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm verb exit [ 1, true ]
npm timing npm Completed in 565ms
```

**Comment by siper92** [comment]
As I read more it turned
