### ISSUE TITLE
Can't install @firebase/testing

### ISSUE THREAD

**Issue by James471** [firebase/firebase-js-sdk#3583]
The following error pops up in firebase CLI on using ```npm install @firebase/testing```-
```
core-js@3.6.5 postinstall E:\Coding\Web\poll-app-firebase-test\test\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

internal/modules/cjs/loader.js:967
  throw err;
  ^

Error: Cannot find module 'E:\Coding\Web\poll-app-firebase-test\test\node_modules\core-js\-e'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:964:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN test@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! core-js@3.6.5 postinstall: `node -e "try{require('./postinstall')}catch(e){}"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the core-js@3.6.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell\AppData\Roaming\npm-cache\_logs\2020-08-07T09_46_49_186Z-debug.log
```
I was using windows 10. I have tried installing core-js separately but that too fails.

**Comment by hsubox76** [comment]
If I understand you correctly, you tried `npm install core-js` and it also doesn't work? In that case it seems like a core-js issue and not an issue with the Firebase sdk code, and you may want to check the issues in the core-js repo.

However, just trying to be helpful, it looks like possibly whatever version of Node you have installed doesn't recognize the "-e" flag  (https://nodejs.org/api/cli.html#cli_e_eval_script) and is expecting a filename there. You might want to look into your version of Node and if there's anything unusual about the way it's set up on your machine. But I think this is out of scope of Firebase SDK issues.
