### ISSUE TITLE
[FS] FirebaseError: [code=deadline-exceeded]: The datastore operation timed out, or the data was temporarily unavailable.

### ISSUE THREAD

**Issue by larssn** [firebase/firebase-js-sdk#359]
### [REQUIRED] Describe your environment

  * Operating System version: OSX High Sierra
  * Firebase SDK version: From 4.6.2 to 4.12.1
  * Firebase Product: Firestore database

### [REQUIRED] Describe the problem

We're periodically (rarely) seeing the above error.
Seems to come out of nowhere, and seems related to listen streams. I can't supply much more info that what our error logging service has provided us:

```
Uncaught (in promise): FirebaseError: [code=deadline-exceeded]: The datastore operation timed out, or the data was temporarily unavailable.
FirebaseError: The datastore operation timed out, or the data was temporarily unavailable.
    at new FirestoreError (file:///android_asset/www/vendor.bundle.js:92299:28)
    at JsonProtoSerializer.webpackJsonp../node_modules/@firebase/firestore/dist/esm/src/remote/serializer.js.JsonProtoSerializer.fromRpcStatus (file:///android_asset/www/vendor.bundle.js:90449:16)
    at JsonProtoSerializer.webpackJsonp../node_modules/@firebase/firestore/dist/esm/src/remote/serializer.js.JsonProtoSerializer.fromWatchChange (file:///android_asset/www/vendor.bundle.js:90892:44)
    at PersistentListenStream.webpackJsonp../node_modules/@firebase/firestore/dist/esm/src/remote/persistent_stream.js.PersistentListenStream.onMessage (file:///android_asset/www/vendor.bundle.js:89117:43)
    at file:///android_asset/www/vendor.bundle.js:89059:34
    at file:///android_asset/www/vendor.bundle.js:89034:28
    at file:///android_asset/www/vendor.bundle.js:92081:20
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (file:///android_asset/www/polyfills.bundle.js:2863:26)
    at Object.onInvoke (file:///android_asset/www/vendor.bundle.js:21993:33)
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (file:///android_asset/www/polyfills.bundle.js:2862:32)
    at Zone.webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.run (file:///android_asset/www/polyfills.bundle.js:2613:43)
    at file:///android_asset/www/polyfills.bundle.js:3344:57
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (file:///android_asset/www/polyfills.bundle.js:2896:31)
    at Object.onInvokeTask (file:///android_asset/www/vendor.bundle.js:21984:33)
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (file:///android_asset/www/polyfills.bundle.js:2895:36)
    at Zone.webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.runTask (file:///android_asset/www/polyfills.bundle.js:2663:47)
    at drainMicroTaskQueue (file:///android_asset/www/polyfills.bundle.js:3073:35)
    at ZoneTask.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (file:///android_asset/www/polyfills.bundle.js:2974:21)
    at invokeTask (file:///android_asset/www/polyfills.bundle.js:4011:14)
    at XMLHttpRequest.globalZoneAwareCallback (file:///android_asset/www/polyfills.bundle.js:4037:17)
```

#### Steps to reproduce:

Seems entirely random

#### Relevant Code:

http://jsbin.com/rinilu/edit?js,console

```javascript
// TODO(you): code here to reproduce the problem
```

_Updated 18 Apr. 2018: Still happens with the latest version of the SDK_

**Comment by mikelehen** [comment]
This is an error from the backend (not the JS sdk). If you're still seeing this, please report it as a bug to Firebase support: https://firebase.google.com/support/contact/

**Comment by larssn** [comment]
We're seeing the same(ish) error again, it just happened in my browser.
v5.2.0 of the SDK. We've reported it to your support as well.

**Details:**

```
sentry-error-handler.service.ts:29 Error: The datastore operation timed out, or the data was temporarily unavailable.
    at new FirestoreError (index.cjs.js:346)
    at JsonProtoSerializer.push../node_modules/@firebase/firestore/dist/index.cjs.js.JsonProtoSerializer.fromRpcStatus (index.cjs.js:5258)
    at JsonProtoSerializer.push../node_modules/@firebase/firestore/dist/index.cjs.js.JsonProtoSerializer.fromWatchChange (index.cjs.js:5756)
    at PersistentListenStream.push../node_modules/@firebase/firestore/dist/index.cjs.js.PersistentListenStream.onMessage (index.cjs.js:13652)
    at index.cjs.js:13597
    at PersistentListenStream.<anonymous> (index.cjs.js:13573)
    at step (tslib.es6.js:91)
    at Object.next (tslib.es6.js:72)
    at tslib.es6.js:65
    at new ZoneAwarePromise (zone.js:891)
```

**Comment by nuvoPoint** [comment]
When the clients get disconnected as a result of this type of backend error the SDK does not handle any type of reconnection. We need to know how to recover when this error happens? Preferably this should be handled by SDK.

**Comment by mikelehen** [comment]
Correct.  FWIW, the error should actually be scoped to a single snapshot listener.  It's possible that one snapshot listener will receive the error and be cancelled, but others will continue.  Though from your description, it sounds like maybe when you get into this state the backend continually sends deadline-exceeded errors for all snapshot listeners, hence you keep getting the error until you restart.  As an experiment you could try calling `firebase.firestore().disableNetwork(); firebase.firestore().enableNetwork();` to see if that resolves the issue since it'll completely teardown and recreate our backend connection.

I'm not very familiar with AF2 and its error handling, but AFAIK your catchError() code should be getting invoked.

To move forward, the most helpful things would be to:
1) If you think your error handling isn't getting called, then try to reproduce this without AF2 so we can determine whether it's an SDK issue or an AF2 issue.
2) To understand the backend issue better it would be helpful if you could enable logging with `firebase.firestore().setLogLevel('debug');` and capture logs of the errors happening.  This will help us correlate the issue with backend logs and perhaps solve it once and for all.

Thanks and sorry for the pain!

**Comment by larssn** [comment]
@mikelehen No worries. It is beta after all!

We'll keep your experiment in mind. The error is pretty rare though, so I can't really say when we can attempt it. Thanks for taking the time!

Lars
