### ISSUE TITLE
[@firebase/testing] FIRESTORE (7.18.0) INTERNAL ASSERTION FAILED: Unexpected state

### ISSUE THREAD

**Issue by goleary** [firebase/firebase-js-sdk#3651]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Node version: 10.20.1
  * Firebase SDK version: "firebase": "7.18.0"
  * "@firebase/testing":"0.20.11"
  * "jest":"26.0.10"
  * Firebase Product: @firebase/testing & firestore emulator

### [REQUIRED] Describe the problem

When I run a very simple firestore rules unit test using jest it fails with the error:
```
  ● Test suite failed to run

    Error: FIRESTORE (7.18.0) INTERNAL ASSERTION FAILED: Unexpected state

      at fail (node_modules/@firebase/firestore/src/util/assert.ts:39:9)
      at hardAssert (node_modules/@firebase/firestore/src/util/assert.ts:53:5)
      at fromBytes (node_modules/@firebase/firestore/src/remote/serializer.ts:272:5)
      at fromWatchChange (node_modules/@firebase/firestore/src/remote/serializer.ts:488:25)
      at PersistentListenStream.onMessage (node_modules/@firebase/firestore/src/remote/persistent_stream.ts:576:25)
      at node_modules/@firebase/firestore/src/remote/persistent_stream.ts:456:21
      at node_modules/@firebase/firestore/src/remote/persistent_stream.ts:509:18
      at node_modules/@firebase/firestore/src/util/async_queue.ts:382:14

  console.error
    [2020-08-18T15:00:04.919Z]  @firebase/firestore: Firestore (7.18.0): FIRESTORE (7.18.0) INTERNAL ASSERTION FAILED: Unexpected state

      at Logger.defaultLogHandler [as _logHandler] (node_modules/@firebase/logger/src/logger.ts:115:57)
      at Logger.error (node_modules/@firebase/logger/src/logger.ts:210:21)
      at logError (node_modules/@firebase/firestore/src/util/log.ts:45:20)
      at fail (node_modules/@firebase/firestore/src/util/assert.ts:34:3)
      at hardAssert (node_modules/@firebase/firestore/src/util/assert.ts:53:5)
      at fromBytes (node_modules/@firebase/firestore/src/remote/serializer.ts:272:5)
      at fromWatchChange (node_modules/@firebase/firestore/src/remote/serializer.ts:488:25)
```

I tried the solution to several other "INTERNAL ASSERTION FAILED" issues found on this repo but none of them fixed the problem.

#### Steps to reproduce:
Here is a minimal repro: https://github.com/goleary/firebase-testing-repro-1

- clone repo
- `yarn install`
- `firebase emulators:start --only firestore`
- open second terminal and run `yarn test security-rules.spec.js`
- see error

#### Relevant Code:

Here is the unit test that result in the error.  Without the second assert it succeeds, but with the second one it fails with the error above.
```
const firebase = require("@firebase/testing");
const fs = require("fs");

const projectId = `whatever`;

const COLLECTION_NAME = "collection";
const adminApp = firebase.initializeAdminApp({ projectId });

test("should allow admin writing/reading to/from linkDetails collection", async () => {
  await await firebase.assertSucceeds(
    adminApp
      .firestore()
      .collection(COLLECTION_NAME)
      .doc("test")
      .set({ test: "test" })
  );
  await await firebase.assertSucceeds(
    adminApp.firestore().collection(COLLECTION_NAME).doc("test").get()
  );
});
```

**Comment by goleary** [comment]
Continued debugging:

I started rolling back the `@firebase/testing` to see if I could find a working version and got these:
- 0.20.10 - `@firebase/firestore: Firestore (7.17.2): FIRESTORE (7.17.2) INTERNAL ASSERTION FAILED: Unexpected state`
- 0.20.9 - `@firebase/firestore: Firestore (7.17.1): FIRESTORE (7.17.1) INTERNAL ASSERTION FAILED: Unexpected state`
- 0.20.8 - `@firebase/firestore: Firestore (7.16.0): FIRESTORE (7.16.0) INTERNAL ASSERTION FAILED: value must be undefined or Uint8Array`

After seeing the last error I remembered [this issue](https://github.com/firebase/firebase-js-sdk/issues/3096) and @dconeybe's [workaround](https://github.com/dconeybe/FirebaseJsBug3096/tree/workaround) which got things back into a working state.  I must have messed up the configuration when I tried this previously, but it does appear to fix the problem.

I'm closing this issue, but hopefully this will help someone else down the road since the error message that `@firebase/testing` spits out has changed.
