### ISSUE TITLE
`Couldn't serialize object of type "FieldValue$1"` in @firebase/rules-unit-testing for the admin app (initializeAdminApp)

### ISSUE THREAD

**Issue by dzhamshed** [firebase/firebase-js-sdk#3910]
### [REQUIRED] Describe your environment

  * Operating System version: Linux
  * Firebase SDK version: @firebase/rules-unit-testing v1.0.6 and firebase-admin v9.2.0
  * Firebase Product: Firestore rules unit testing

### [REQUIRED] Describe the problem
I have a small unit test (firestore rules allow everything):
```ts
const app = testing.initializeTestApp({ projectId: 'test-project' });
const admin = testing.initializeAdminApp({ projectId: 'test-project' });

// if replace **admin** with **app** it works...
await admin.firestore().collection('test').add({
      title: 'test',
      created: testing.firestore.FieldValue.serverTimestamp(),
});

await testing.assertSucceeds(app.firestore().collection('test').get());
```
When I first run it, it required to install **firebase-admin**. I installed that package by `npm install --save firebase-admin` and run it again but got following error:
 ```log
Error: Value for argument "data" is not a valid Firestore document. Couldn't serialize object of type "FieldValue$1" (found in field "created"). Firestore doesn't support JavaScript objects with custom prototypes (i.e. objects that were created via the "new" operator).
      at validateUserInput (node_modules/@google-cloud/firestore/build/src/serializer.js:314:15)
      at Object.validateUserInput (node_modules/@google-cloud/firestore/build/src/serializer.js:263:13)
      at Object.validateDocumentData (node_modules/@google-cloud/firestore/build/src/write-batch.js:620:18)
      at CollectionReference.add (node_modules/@google-cloud/firestore/build/src/reference.js:2020:23)
```
If I change **admin** app to the test **app** it works fine.

**Comment by samtstern** [comment]
@dzhamshed so the issue is that you're using the `FieldValue.serverTimestamp()` from the **web** SDK but you're passing it to the **admin** SDK.  This is definitely super confusing because the `rules-unit-testing` library blends both of them!

As you mentioned you need to make sure you use the admin types with admin operations and the web types with web operations, so this will work:

```js
const firebaseAdmin = require("firebase-admin"); // ⬅️ new import
// ...
await admin.firestore().collection('test').add({
      title: 'test',
      created: admin.firestore.FieldValue.serverTimestamp() // ⬅️ changed line
});
```

And this will work for non-admin operations:
```js
const firebase= require("firebase/app"); // ⬅️ new import
// ...
await app.firestore().collection('test').add({
      title: 'test',
      created: firebase.firestore.FieldValue.serverTimestamp() // ⬅️ changed line
});
```
