### ISSUE TITLE
Firestore throws error on Node.js runtime when signed in

### ISSUE THREAD

**Issue by joostfarla** [firebase/firebase-js-sdk#407]
### [REQUIRED] Describe your environment

  * Operating System version: macOS High Sierra / Node.js v8
  * Firebase SDK version: 4.8.1
  * Firebase Product: firestore

### [REQUIRED] Describe the problem

When using the Firestore SDK in combination with Firebase authentication, I'm getting the following error:

```
{ FirebaseError: Failed to get document because the client is offline.
    at new FirestoreError (/path/node_modules/@firebase/firestore/dist/cjs/src/util/error.js:151:28)
    at Object.next (/path/node_modules/@firebase/firestore/dist/cjs/src/api/database.js:595:32)
    at next (/path/node_modules/@firebase/firestore/dist/cjs/src/api/database.js:563:30)
    at Timeout._onTimeout (/path/node_modules/@firebase/firestore/dist/cjs/src/util/async_observer.js:46:21)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) code: 'aborted', name: 'FirebaseError', toString: [Function] }
```

#### Steps to reproduce:

Run the following code on a Node.js runtime:

```js
const firebase = require('firebase');
require('firebase/firestore');

firebase.initializeApp({
  ...
});

firebase.auth().signInWithEmailAndPassword('foo@example.com', 'fakePass');

const docRef = firebase.firestore()
  .collection('coll')
  .doc('id');

docRef.get()
  .then(doc => console.log(doc.data()))
  .catch(console.error);
```

When removing the `auth().signInWithEmailAndPassword` line, everything works fine.

#### Relevant Code:

See above.

**Comment by mikelehen** [comment]
Can you enable logging with `firebase.firestore.setLogLevel('debug')` and share the output?

**Comment by mikelehen** [comment]
Closing due to inactivity.  Let us know if you're still having issues and can provide more details.  Thanks.
