### ISSUE TITLE
@grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0 ? How do I fix this ?

### ISSUE THREAD

**Issue by lopeselio** [firebase/firebase-js-sdk#4114]
Error: @grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0
    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/@grpc/grpc-js/build/src/index.js:47:11)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/pubsub/node_modules/google-gax/build/src/grpc.js:21:14)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)

I tried updating node to 8.15.0 and it still doesnt work

**Comment by hsubox76** [comment]
Sometimes it can be tricky to make sure there aren't conflicting versions of node/npm, perhaps try some of the suggestions in the last comment here: https://stackoverflow.com/questions/57086717/how-can-i-fix-this-grpc-grpc-js-only-works-on-node-8-13-0-10-10-0 or look around to see how to make sure your npm and Node are using the version you think they are.

If none of that is any good, can you try the most recent Node 10.x.x?

**Comment by lopeselio** [comment]
Hey @hsubox76 I did try to find a workaround with the suggestion above. Finally solved it using `curl -sL firebase.tools | bash` and then `firebase login` started working. I even downgraded my node version from 10.x.x to 8.15.0 for that. There are issues with running `firebase login` with `sudo npm i -g firebase-tools`.

Thanks a lot for the help. Cheers

**Comment by hsubox76** [comment]
Oh, I'm so sorry I didn't realize you were running into this issue while trying to use the Firebase CLI (`firebase-tools`), I thought this was happening on npm install of the JS client SDK. If you do have any future problems with the CLI, here's the repo for the firebase-tools CLI: https://github.com/firebase/firebase-tools

**Comment by approached** [comment]
Check your version:
```node -v```

FYI: https://github.com/grpc/grpc-node/pull/1693/files

**Comment by radvansky-tomas** [comment]
I have this issue using Node v15.14.0 on M1

**Comment by radvansky-tomas** [comment]
```
Test suite failed to run

    @grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0

      at Object.<anonymous> (node_modules/@grpc/grpc-js/src/index.ts:71:9)
      at Object.<anonymous> (node_modules/google-gax/src/index.ts:17:1)
```

**Comment by DellaBitta** [comment]
Hi @radvansky-tomas,

It's been a while. Just checking in to see if this is still an issue. Thanks!
