### ISSUE TITLE
Uncaught FirebaseError: Firebase: Error (auth/internal-error) when Firestore is initialized before Auth

### ISSUE THREAD

**Issue by mbleigh** [firebase/firebase-js-sdk#4290]
If I do this code:

```js
import { initializeApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';
import { getAuth } from 'firebase/auth';

export const app = initializeApp({});

export const db = getFirestore(app);
export const auth = getAuth(app);
```

on version 0.900.4 I get:

```
Uncaught FirebaseError: Firebase: Error (auth/internal-error).
    at createErrorInternal (http://localhost:8080/_snowpack/pkg/firebase/auth.js:250:55)
    at _assert (http://localhost:8080/_snowpack/pkg/firebase/auth.js:260:35)
    at AuthImpl.registerStateListener (http://localhost:8080/_snowpack/pkg/firebase/auth.js:3886:9)
    at AuthImpl.onIdTokenChanged (http://localhost:8080/_snowpack/pkg/firebase/auth.js:3745:21)
    at AuthInternal.addAuthTokenListener (http://localhost:8080/_snowpack/pkg/firebase/auth.js:6089:37)
    at new F$1 (http://localhost:8080/_snowpack/pkg/firebase/firestore.js:2014:35)
    at new Mc$1 (http://localhost:8080/_snowpack/pkg/firebase/firestore.js:15478:20)
    at new Bu (http://localhost:8080/_snowpack/pkg/firebase/firestore.js:17007:9)
    at http://localhost:8080/_snowpack/pkg/firebase/firestore.js:18692:72
    at Component.instanceFactory (http://localhost:8080/_snowpack/pkg/firebase/firestore.js:18692:85)
```

if I instead change the order so `getAuth()` occurs before `getFirestore()`, it seems to work properly.

**Comment by hsubox76** [comment]
I think this was addressed by https://github.com/firebase/firebase-js-sdk/pull/4428
