### ISSUE TITLE
Documentation for browserify consumption does not work.

### ISSUE THREAD

**Issue by KoryNunn** [firebase/firebase-js-sdk#4475]
### Describe your environment

  * Operating System version: Any
  * Browser version: Any
  * Firebase SDK version: 8.2.7
  * Firebase Product: All

#### Steps to reproduce:

1. Follow firebase documentation for browserify

From the npm readme:
```
The Firebase JavaScript npm package contains code that can be run in the browser after combining the modules you use with a package bundler (e.g., Browserify, Webpack).

Install the Firebase npm module:

$ npm init
$ npm install --save firebase
In your code, you can access Firebase using:

var firebase = require('firebase');
var app = firebase.initializeApp({ ... });
```

2. Run browserify

```
> browserify index.js > out.js

Error: Parsing file .../firebase-bug/node_modules/firebase/dist/index.esm.js: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
    at Deps.parseDeps (.../firebase-bug/node_modules/module-deps/index.js:519:15)
    at getDeps (.../firebase-bug/node_modules/module-deps/index.js:447:44)
    at .../firebase-bug/node_modules/module-deps/index.js:430:38
    at ConcatStream.<anonymous> (.../firebase-bug/node_modules/concat-stream/index.js:37:43)
    at ConcatStream.emit (events.js:215:7)
    at finishMaybe (.../firebase-bug/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at endWritable (.../firebase-bug/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at ConcatStream.Writable.end (.../firebase-bug/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DuplexWrapper.onend (.../firebase-bug/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:299:28)
```

I was able to add the following plugins to make this work, but it is not a preferable solution, as this makes builds take a very long time:
```
browserify -t [ babelify --global --ignore \\[!node_modules/firebase/*\\] --plugins [ @babel/plugin-transform-modules-commonjs ] ] ./index.js > out.js
```

**Comment by hsubox76** [comment]
Thanks for letting us know.

Browserify seems to look at the `browser` field by default, which makes sense, but only works with cjs files natively, and our `browser` fields from firebase 8+ point to esm bundles. Seems you can use this browserify option:

```
  --no-browser-field, --no-bf

    Turn off package.json browser field resolution. This is also handy if you
    need to run a bundle in node.
```

to point to the `main` field instead and get the cjs bundle.

Let me know if that works, either way we will definitely update the README, just need to be sure of what to update it to.
