### ISSUE TITLE
@firebase/auth NetworkError ~100 users affected daily under Mobile Safari

### ISSUE THREAD

**Issue by zanona** [firebase/firebase-js-sdk#4476]
### [REQUIRED] Describe your environment

  * Operating System version: iOS 13.x / 14.x
  * Browser version: Mobile Safari 13.x / 14.x 
  * Firebase SDK version: 8.2.7
  * Firebase Product: auth

### [REQUIRED] Describe the problem

I have been following errors on Sentry and noticed that a considerable part of our traffic is being affected daily by this issue , wherein most cases are under Mobile Safari and the minority on mobile Chrome (always iOS). Even though the error is automatically handled and not visible to the user (AFAIK), I would still like to iron those out to keep our error logs clean.

#### Steps to reproduce:

I've been able to browse the site from an iPhone using 4G rather than Wi-Fi and noticed that the issue was listed in the logs right after (again, no visible feedback is shown besides log messages). During the entire time, the connection was stable and not offline throughout the test period _(probably the same is true for the approximate 100 daily cases hit by this issue)_. 

#### Relevant Code:

I've noticed that this issue is being triggered before making any calls to the `auth()` method,
 but rather, just by  importing it, it seems to trigger the error.

```javascript
import firebase from 'firebase/app';
import 'firebase/auth';
firebase.initializeApp({...});
//error possibly being triggered after this
```

Later in the app I then call for `firebase.auth().signInAnonymously()`, but that is only called at a point in which those affected users haven't had yet reached. 

The error stack is logged as follows:
```
Error: Network Error
  at call(./node_modules/@firebase/auth/dist/auth.esm.js:275:415)
  at call(./node_modules/@firebase/auth/dist/auth.esm.js:88:164)
  at Sc(./node_modules/@firebase/auth/dist/auth.esm.js:91:216)
  at Oc(./node_modules/@firebase/auth/dist/auth.esm.js:91:85)
  at call(./node_modules/@firebase/auth/dist/auth.esm.js:90:303)
  at xc(./node_modules/@firebase/auth/dist/auth.esm.js:84:781)
  at promiseReactionJob([native code])
```

Related: https://github.com/firebase/firebase-js-sdk/issues/20
https://github.com/firebase/firebase-js-sdk/blob/0dfef5dd58f961208e29e249f5e8f5a3e2908c88/packages/auth/src/iframeclient/iframewrapper.js#L243-L315

**Comment by zanona** [comment]
Just closing this after checking the real cause of the issue here was an incomplete set of CSR rules where some domains were in fact being blocked.

I am now using this subset of rules in order to allow connections to firebase services and the number of cases has reduced significantly, with only users with potential blocking browsers extensions experiencing issues, which is acceptable.

```js
const firebase = {
	"script-src": ["apis.google.com", "ajax.googleapis.com", "www.googletagmanager.com"],
	"frame-src": [`${projectId}.firebaseapp.com`],
	"connect-src": [
		"firebase.googleapis.com",
		"firestore.googleapis.com",
		"securetoken.googleapis.com",
		"firebaseinstallations.googleapis.com",
		"www.googleapis.com",
		`us-central1-${projectId}.cloudfunctions.net`,
	]
};
```
I would also like to suggest the addition of the CSR rules required for firebase, and it's aggregated services, to the docs. Just like stripe is doing: https://stripe.com/docs/security/guide#content-security-policy. This would help some developers to mitigate this issue from day one.
