### ISSUE TITLE
Error on installing on M1 mac

### ISSUE THREAD

**Issue by DenisRakhuba** [firebase/firebase-js-sdk#4800]
Operating System version: OS Big Sur
Chip: Apple Silicon M1
Command : `npm install --save firebase`
Expected : package installed
Result: multiple errors

Node v15.14.0
Npm v7.7.6
Native terminal

Node v.12.19.0
Npm v6.14.8
Rosetta terminal

I have an Angular project which I'm trying to run on new Mac M1. I've been receiving errors on npm install and lately I found out that it crashes exactly on installing firebase. I've tried to run `npm install --save firebase` both on native m1 terminal and the one launched through Rosetta with different version of node. 
I'm getting error on both native with node 15.14.0/npm 7.7.6 and rosettas node 12.19.0/npm 6.14.8 (those version runs fine on older macbook and this project)

Here is the error I'm getting:

1 error generated.
```
make: *** [Release/obj.target/grpc_node/ext/channel.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/mantebose/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 20.3.0
gyp ERR! command "/Users/mantebose/.nvm/versions/node/v12.19.0/bin/node" "/Users/mantebose/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/mantebose/Documents/Work/clawee-web-game/node_modules/@firebase/firestore/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/mantebose/Documents/Work/clawee-web-game/node_modules/@firebase/firestore/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /Users/mantebose/Documents/Work/clawee-web-game/node_modules/@firebase/firestore/node_modules/grpc
gyp ERR! node -v v12.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/mantebose/.nvm/versions/node/v12.19.0/bin/node /Users/mantebose/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/mantebose/Documents/Work/clawee-web-game/node_modules/@firebase/firestore/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/mantebose/Documents/Work/clawee-web-game/node_modules/@firebase/firestore/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/mantebose/Documents/Work/clawee-web-game/node_modules/@firebase/firestore/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 20.3.0
node-pre-gyp ERR! command "/Users/mantebose/.nvm/versions/node/v12.19.0/bin/node" "/Users/mantebose/Documents/Work/clawee-web-game/node_modules/@firebase/firestore/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /Users/mantebose/Documents/Work/clawee-web-game/node_modules/@firebase/firestore/node_modules/grpc
node-pre-gyp ERR! node -v v12.19.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/Users/mantebose/.nvm/versions/node/v12.19.0/bin/node /Users/mantebose/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/mantebose/Documents/Work/clawee-web-game/node_modules/@firebase/firestore/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/mantebose/Documents/Work/clawee-web-game/node_modules/@firebase/firestore/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.20.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mantebose/.npm/_logs/2021-04-16T09_52_57_705Z-debug.log

```

**Comment by looptheloop88** [comment]
Hi @DenisRakhuba, I wasn't able to replicate this issue using my test app here. Would you mind [sharing a minimal, but complete](https://stackoverflow.com/help/minimal-reproducible-example) sample project that I can run locally to reproduce the issue?

**Comment by DenisRakhuba** [comment]
Hi @looptheloop88 , I've created [test project](https://github.com/DenisRakhuba/for-reproduce) and pasted there package.json from my main project, so you could reproduce the error.
It's reproduced on native m1 terminal with node version 15.14.0 and command `npm i --save --legacy-peer-deps firebase` or 
on rosseta terminal with node version 12.19.0 and command `npm i --save firebase`

**Comment by looptheloop88** [comment]
Hi @DenisRakhuba, thanks for creating a sample project. I appreciate it.

You might need to fix or update the dependencies in your project. I've seen conflicts and some of them are deprecated or outdated. For example, you're still using the firebase version `5.5.+`, while we are already on `8.4.+`.

Running `npm install --legacy-peer-deps` will give the following result:

```
npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated chokidar@2.0.4: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.16.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will receive updates in the future
npm WARN deprecated @angular/http@7.0.4: Package no longer supported. Use @angular/common instead, see https://angular.io/guide/deprecations#angularhttp
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
```

I've seen similar issues filed in [node-pre-gyp](https://github.com/mapbox/node-pre-gyp/issues/381), [firebase-tools](https://github.com/firebase/firebase-tools/issues/467) and [grpc-node](https://github.com/grpc/grpc-node/issues/121) repositories, however I wasn't able to find a common solution. This might be due to the differences in the versions used.

I have these versions in my machine:
```
firebase tools --version 9.10.0
node -v v14.16.1
npm -v 7.8.0
```

Here are the workaround that worked for me (based on the similar issues above) without changing the versions:

1. Delete `firebase` dependency in the `package.json` file, run `npm install --legacy-peer-deps`, then `run npm install firebase --save`.
2. Downgrade the `firebase` dependency version in `package.json` file to `4.12.1`, then run `npm install --legacy-peer-deps`.

**Comment by DenisRakhuba** [comment]
Hi @looptheloop88. That helped. Thanks for your time.
