### ISSUE TITLE
Error when installing in Windows 10

### ISSUE THREAD

**Issue by arthurcohen** [firebase/firebase-js-sdk#488]
### [REQUIRED] Describe your environment

**Angular:** 5.0.3;

**Firebase:** not installed;

**AngularFire:** not installed;

**Ionic:**  3.19.1;

**Cordova:** 8.0.0;

**OS:** Windows 10 Pro v10.0.16299.

### [REQUIRED] Describe the problem

**Steps to set up and reproduce**

What I've done was simply tried to install Firebase following all the procedures suggested by the docs. I've already installed **node-gyp** and **windows-build-tools**.

### Debug output

**Errors in the Powershell console**

 ```powershell
npm install angularfire2 firebase --save

> grpc@1.8.4 install C:\Users\arthu\ionic\projects\firebase-chat-basic\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.4/node-v57-win32-x64-unknown.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.8.4 and node@8.9.4 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MS
B6006: "CL.exe" exited with code -1073741701. [C:\Users\arthu\ionic\projects\firebase-chat-basic\no
de_modules\grpc\build\WINDOWS_BUILD_WARNING.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MS
B6006: "CL.exe" exited with code -1073741701. [C:\Users\arthu\ionic\projects\firebase-chat-basic\no
de_modules\grpc\build\boringssl.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MS
B6006: "CL.exe" exited with code -1073741701. [C:\Users\arthu\ionic\projects\firebase-chat-basic\no
de_modules\grpc\build\gpr.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MS
B6006: "CL.exe" exited with code -1073741701. [C:\Users\arthu\ionic\projects\firebase-chat-basic\no
de_modules\grpc\build\grpc.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MS
B6006: "CL.exe" exited with code -1073741701. [C:\Users\arthu\ionic\projects\firebase-chat-basic\no
de_modules\grpc\build\z.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\arthu\\ionic\\projects\\firebase-chat-basic\\node_modules\\grpc\\src\\node\\extension_binary\\node-v57-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\arthu\\ionic\\projects\\firebase-chat-basic\\node_modules\\grpc\\src\\node\\extension_binary\\node-v57-win32-x64-unknown"
gyp ERR! cwd C:\Users\arthu\ionic\projects\firebase-chat-basic\node_modules\grpc
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --library=static_library --module=C:\Users\arthu\ionic\projects\firebase-chat-basic\node_modules\grpc\src\node\extension_binary\node-v57-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\arthu\ionic\projects\firebase-chat-basic\node_modules\grpc\src\node\extension_binary\node-v57-win32-x64-unknown' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\arthu\ionic\projects\firebase-chat-basic\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\arthu\\ionic\\projects\\firebase-chat-basic\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Users\arthu\ionic\projects\firebase-chat-basic\node_modules\grpc
node-pre-gyp ERR! node -v v8.9.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --library=static_library --module=C:\Users\arthu\ionic\projects\firebase-chat-basic\node_modules\grpc\src\node\extension_binary\node-v57-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\arthu\ionic\projects\firebase-chat-basic\node_modules\grpc\src\node\extension_binary\node-v57-win32-x64-unknown' (1)
npm WARN @angular/common@5.0.3 requires a peer of rxjs@^5.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/core@5.0.3 requires a peer of rxjs@^5.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/forms@5.0.3 requires a peer of rxjs@^5.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/http@5.0.3 requires a peer of rxjs@^5.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN angularfire2@5.0.0-rc.6 requires a peer of rxjs@^5.5.4 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.8.4 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.8.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\arthu\AppData\Roaming\npm-cache\_logs\2018-02-05T14_54_59_845Z-debug.log
```

### Expected behavior

A clean installation.

### Actual behavior

Somer Erros about **gyp** and **node-pre-gyp**.

**Comment by arthurcohen** [comment]
Installation problem solved with **node-pre-gyp**, as follow:

`npm install node-pre-gyp -g`

now the project is not running after installing the package, but this is another history.

**Comment by arthurcohen** [comment]
Hey @pranesh239, do you have the same errors messages as I had? Post more details then I can help you. After many tries, here is running with no problems.

**Comment by revooru** [comment]
did anyone solved this issue??...if u have then pls post the solution
