### ISSUE TITLE
Breaking change in rules-unit-testing 1.3.7

### ISSUE THREAD

**Issue by markgoho** [firebase/firebase-js-sdk#5025]
### [REQUIRED] Describe your environment

  * Operating System version: Win 10
  * Browser version: n/a
  * Firebase SDK version: 8.6.7
  * Firebase Product: rules-unit-testing

#### Steps to reproduce:
Install `@firebase/rules-unit-testing@1.3.6` and see rules unit tests pass
Install `@firebase/rules-unit-testing@1.3.7` and see rules unit tests break

#### Relevant Code:
relevant `v1.3.7` output:
``` bash
TypeError: app.firestore is not a function
    at initializeApp (D:\IdeaCrew\active-branch-tracker\functions\node_modules\@firebase\rules-unit-testing\dist\index.cjs.js:379:13)
    at Object.initializeTestApp (D:\IdeaCrew\active-branch-tracker\functions\node_modules\@firebase\rules-unit-testing\dist\index.cjs.js:163:12)
    at Suite.<anonymous> (D:\IdeaCrew\active-branch-tracker\functions\test\rules.spec.js:38:6)
    at Object.create (D:\IdeaCrew\active-branch-tracker\functions\node_modules\mocha\lib\interfaces\common.js:148:19)
    at context.describe.context.context (D:\IdeaCrew\active-branch-tracker\functions\node_modules\mocha\lib\interfaces\bdd.js:42:27)
    at Object.<anonymous> (D:\IdeaCrew\active-branch-tracker\functions\test\rules.spec.js:36:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.exports.requireOrImport (D:\IdeaCrew\active-branch-tracker\functions\node_modules\mocha\lib\esm-utils.js:42:12)
    at Object.exports.loadFilesAsync (D:\IdeaCrew\active-branch-tracker\functions\node_modules\mocha\lib\esm-utils.js:55:34)
    at Mocha.loadFilesAsync (D:\IdeaCrew\active-branch-tracker\functions\node_modules\mocha\lib\mocha.js:473:19)
    at singleRun (D:\IdeaCrew\active-branch-tracker\functions\node_modules\mocha\lib\cli\run-helpers.js:125:15)
    at exports.runMocha (D:\IdeaCrew\active-branch-tracker\functions\node_modules\mocha\lib\cli\run-helpers.js:190:10)
    at Object.exports.handler (D:\IdeaCrew\active-branch-tracker\functions\node_modules\mocha\lib\cli\run.js:362:11)
    at D:\IdeaCrew\active-branch-tracker\functions\node_modules\yargs\build\index.cjs:443:71
```

here's what's at rules.spec.js:36:
``` javascript
const noUserDb = firebase
    .initializeTestApp({
      projectId: DEMO_FIREBASE_PROJECT_ID,
      auth: null,
    })
    .firestore();
```

Repo for reproducing: https://github.com/ideacrew/active-branch-tracker

To reproduce, `cd functions && npm i` then `npm i @firebase/rules-unit-testing@1.3.7` then `npm run test:ci:rules`

**Comment by looptheloop88** [comment]
Hi @markgoho, thanks for the report. I was able to reproduce the error by using the sample project and following the steps you've shared. After deleting the **node_modules** directory and the **package-lock.json** file, then do `npm install` again, the test script was successfully executed without any errors.

<img width="759" alt="Screen Shot 2021-06-18 at 1 50 32 AM" src="https://user-images.githubusercontent.com/80330521/122449123-16f56a80-cfd8-11eb-963f-666fbbe9da2b.png">

**Comment by markgoho** [comment]
@looptheloop88 great work!

just to be safe, what version of npm were you using? I know that v6 > v7 had some weird things about peer dependency management

**Comment by looptheloop88** [comment]
Hi @markgoho, I used npm version `7.11.1`.
