### ISSUE TITLE
Could not install firebase from npm

### ISSUE THREAD

**Issue by mashouf** [firebase/firebase-js-sdk#5154]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * npm version: 6.4.1
  * node version: 10.13.0

### [REQUIRED] Describe the problem
Unable to install firebase
npm WARN using --force I sure hope you know what you are doing.
npm ERR! Unexpected end of JSON input while parsing near '...Wfnpt31GscdTOOWCx6IrK'
#### Steps to reproduce:
run npm i firebase from your root of project 

#### Relevant Code:
First Try from Ubuntu WSL:
```
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @firebase/app@undefined
npm WARN node_modules/firebase/node_modules/@firebase/app
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @firebase/app@"0.x" from @firebase/auth@0.15.0
npm WARN node_modules/firebase/node_modules/@firebase/auth
npm WARN   @firebase/auth@"0.15.0" from firebase@7.24.0
npm WARN   node_modules/firebase
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: @firebase/app@undefined
npm ERR! node_modules/@firebase/app
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @firebase/app@"0.x" from @firebase/firestore@1.18.0
npm ERR! node_modules/@firebase/firestore
npm ERR!   @firebase/firestore@"1.18.0" from firebase@7.24.0
npm ERR!   node_modules/firebase
npm ERR!     firebase@"^7.24.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
Second try from windows CMD:

```59 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...Wfnpt31GscdTOOWCx6IrK'
59 verbose stack     at JSON.parse (<anonymous>)
59 verbose stack     at parseJson (C:\Users\Mashouf\AppData\Roaming\nvm\v10.13.0\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
59 verbose stack     at consumeBody.call.then.buffer (C:\Users\Mashouf\AppData\Roaming\nvm\v10.13.0\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50)
59 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
```
with --force:
```
npm WARN using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @firebase/app@undefined
npm WARN node_modules/firebase/node_modules/@firebase/app
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @firebase/app@"0.x" from @firebase/auth@0.15.0
npm WARN node_modules/firebase/node_modules/@firebase/auth
npm WARN   @firebase/auth@"0.15.0" from firebase@7.24.0
npm WARN   node_modules/firebase
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @firebase/app@undefined
npm WARN node_modules/@firebase/app
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @firebase/app@"0.x" from @firebase/firestore@1.18.0
npm WARN node_modules/@firebase/firestore
npm WARN   @firebase/firestore@"1.18.0" from firebase@7.24.0
npm WARN   node_modules/firebase
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @firebase/app@undefined
npm WARN node_modules/firebase/node_modules/@firebase/app
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @firebase/app@"0.x" from @firebase/functions@0.5.1
npm WARN node_modules/firebase/node_modules/@firebase/functions
npm WARN   @firebase/functions@"0.5.1" from firebase@7.24.0
npm WARN   node_modules/firebase
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @firebase/app@undefined
npm WARN node_modules/firebase/node_modules/@firebase/app
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @firebase/app@"0.x" from @firebase/installations@0.4.17
npm WARN node_modules/firebase/node_modules/@firebase/installations
npm WARN   @firebase/installations@"0.4.17" from firebase@7.24.0
npm WARN   node_modules/firebase
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @firebase/app@undefined
npm WARN node_modules/firebase/node_modules/@firebase/app
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @firebase/app@"0.x" from @firebase/messaging@0.7.1
npm WARN node_modules/firebase/node_modules/@firebase/messaging
npm WARN   @firebase/messaging@"0.7.1" from firebase@7.24.0
npm WARN   node_modules/firebase
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @firebase/app@undefined
npm WARN node_modules/firebase/node_modules/@firebase/app
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @firebase/app@"0.x" from @firebase/performance@0.4.2
npm WARN node_modules/firebase/node_modules/@firebase/performance
npm WARN   @firebase/performance@"0.4.2" from firebase@7.24.0
npm WARN   node_modules/firebase
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @firebase/app@undefined
npm WARN node_modules/firebase/node_modules/@firebase/app
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @firebase/app@"0.x" from @firebase/remote-config@0.1.28
npm WARN node_modules/firebase/node_modules/@firebase/remote-config
npm WARN   @firebase/remote-config@"0.1.28" from firebase@7.24.0
npm WARN   node_modules/firebase
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @firebase/app@undefined
npm WARN node_modules/firebase/node_modules/@firebase/app
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @firebase/app@"0.x" from @firebase/storage@0.3.43
npm WARN node_modules/firebase/node_modules/@firebase/storage
npm WARN   @firebase/storage@"0.3.43" from firebase@7.24.0
npm WARN   node_modules/firebase
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @firebase/util@undefined
npm WARN node_modules/firebase/node_modules/@firebase/auth/node_modules/@firebase/util
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @firebase/util@"0.x" from @firebase/auth-types@0.10.1
npm WARN node_modules/firebase/node_modules/@firebase/auth/node_modules/@firebase/auth-types
npm WARN   @firebase/auth-types@"0.10.1" from @firebase/auth@0.15.0
npm WARN   node_modules/firebase/node_modules/@firebase/auth
npm ERR! code FETCH_ERROR
npm ERR! errno FETCH_ERROR
npm ERR! invalid json response body at https://registry.npmjs.org/@firebase%2fanalytics reason: Unexpected end of JSON input
```

Third try:
```
npm WARN tarball tarball data for @firebase/installations@https://registry.npmjs.org/@firebase/installations/-/installations-0.4.17.tgz (sha512-AE/TyzIpwkC4UayRJD419xTqZkKzxwk0FLht3Dci8WI2OEKHSwoZG9xv4hOBZebe+fDzoV2EzfatQY8c/6Avig==) seems to be corrupted. Trying again.
npm WARN tar zlib: unexpected end of file
```
try removing node_modules, package-lock.json or npm clean  cache do not help

**Comment by looptheloop88** [comment]
Hi @mashouf, thanks for the report. I wasn't able to replicate this issue. You may want to delete the existing node_modules directory and package-lock.json file, then do npm install again.

If the issue persists, please share a sample project that we can use and run locally to replicate the issue.
