### ISSUE TITLE
Firebase rules test fails when it shouldn't

### ISSUE THREAD

**Issue by moneer-muntazah** [firebase/firebase-js-sdk#5236]
I just started with firebase rules, but It doesn't seem like I'm doing anything wrong. I'm using lock down mode with 

```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if false;
    }
  }
}
```

and this is the code 

```js
const firebase = require('@firebase/rules-unit-testing');
const fs = require('fs');

const projectId = 'test-judge';

function getAuthedFirestore(auth) {
    return firebase.initializeAdminApp({
        projectId: projectId,
        auth: auth
    }).firestore();
}

beforeEach(async () => {
    await firebase.clearFirestoreData({ projectId });
});

before(async () => {
    const rules = fs.readFileSync('firestore.rules', 'utf8');
    await firebase.loadFirestoreRules({
        projectId: projectId,
        rules: rules
    });
});

after(async () => {
    await Promise.all(firebase.apps().map(app => app.delete()));
});

describe('locked down', () => {
    it("require users to log in before creating a profile", async () => {
        const db = getAuthedFirestore(null);
        const profile = db.collection("users").doc("alice");
        await firebase.assertFails(profile.set({ birthday: "January 1" }));
    });
});
```

The test should succeed but I'm getting

```
Warning: FIRESTORE_EMULATOR_HOST not set, using default value localhost:8080
    1) require users to log in before creating a profile


  0 passing (316ms)
  1 failing

  1) locked down
       require users to log in before creating a profile:
     Error: Expected request to fail, but it succeeded.
      at C:\Users\Moneer\Desktop\judge_rules\node_modules\@firebase\rules-unit-testing\dist\index.cjs.js:581:31
      at async Context.<anonymous> (test\test.js:33:9)

```

**Comment by moneer-muntazah** [comment]
Just realized I should be using `initializeTestApp` not `initializeAdminApp`
