### ISSUE TITLE
Unhandled network error rejection when using storage API

### ISSUE THREAD

**Issue by VeryCrazyDog** [firebase/firebase-js-sdk#5372]
### Describe your environment

  * Operating System version: Windows 10
  * Browser version: N/A (Node.js 14)
  * Firebase SDK version: 8.10.0
  * Firebase Product: storage

#### Steps to reproduce:
1. Simulate network error such as disconnect from network, blocking DNS server, blocking outgoing traffic, etc.
2. Execute storage API such as `getMetadata()` or `getDownloadURL()`.
3. Unhandled promise rejection is thrown. A sample console log is at below. My expected result is throwing `FirebaseError` with code `storage/retry-limit-exceeded`.

```
C:\Users\VCD\Developer\playground>node --unhandled-rejections=throw fbstorage-bug.js

C:\Users\VCD\Developer\playground\node_modules\node-fetch\lib\index.js:1461
                        reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
                               ^
FetchError: request to https://firebasestorage.googleapis.com/v0/b/xxxxxxxxxxxxxxxxx.appspot.com/o/image.png failed, reason: getaddrinfo ENOTFOUND firebasestorage.googleapis.com
    at ClientRequest.<anonymous> (C:\Users\VCD\Developer\playground\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND'
}
```

#### Relevant code:

```javascript
'use strict'

const firebase = require('firebase/app')
require('firebase/storage')

const app = firebase.initializeApp({
  apiKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  authDomain: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  projectId: 'xxxxxxxxxxxxxxxxx',
  storageBucket: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  messagingSenderId: 'xxxxxxxxxxxx',
  appId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
})
const storage = app.storage()

// Remember to disconnect the network before running
;(async () => {
  const ref = storage.ref('/image.png')
  const rtv = await ref.getMetadata()
  console.log(rtv)
  console.log('END')
})().catch(error => {
  console.log('EXCEPTION')
  if (error.stack) {
    console.error(error.stack)
  } else {
    console.error(error)
  }
}).finally(async () => {
  await app.delete()
})
```

**Comment by hsubox76** [comment]
Thanks for the repro, I was able to reproduce it in 9.0.0 compat. Just FYI, going forward, any fixes will be in version 9+ so you'll have to upgrade and change the import paths to `require('firebase/compat/app')` and `require('firebase/compat/storage')`.

I think we need to catch errors on `send` here https://github.com/firebase/firebase-js-sdk/blob/1b33fda40ddc48e9ed28e94607bf100159f5b80e/packages/storage/src/implementation/request.ts#L136 or maybe we should handle the node-fetch error specifically and catch here https://github.com/firebase/firebase-js-sdk/blob/1b33fda40ddc48e9ed28e94607bf100159f5b80e/packages/storage/src/platform/node/connection.ts#L53.
