### ISSUE TITLE
Error in Angular Universal app after upgrading from 9.1.3 to 9.2.0

### ISSUE THREAD

**Issue by Burgov** [firebase/firebase-js-sdk#5697]
After upgrading to 9.2.0, my Angular Universal app doesn't work anymore. It compiles successfully, but then on runtime I get this error:

```
/Users/bart/workspace/msp-navigator/dist/apps/frontend/server/main.js:370834
  throw new Error("NotYetImplemented");
  ^

Error: NotYetImplemented
    at Document.exports.nyi (/Users/bart/workspace/msp-navigator/dist/apps/frontend/server/main.js:370834:9) [<root>]
    at Object.<anonymous> (/Users/bart/workspace/msp-navigator/node_modules/@firebase/firestore/dist/index.node.cjs.js:14249:249) [<root>]
    at Module._compile (internal/modules/cjs/loader.js:1085:14) [<root>]
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) [<root>]
    at Module.load (internal/modules/cjs/loader.js:950:32) [<root>]
    at Function.Module._load (internal/modules/cjs/loader.js:790:14) [<root>]
    at Module.require (internal/modules/cjs/loader.js:974:19) [<root>]
    at require (internal/modules/cjs/helpers.js:92:18) [<root>]
    at Object.28627 (/Users/bart/workspace/msp-navigator/dist/apps/frontend/server/main.js:135335:35) [<root>]
    at __webpack_require__ (/Users/bart/workspace/msp-navigator/dist/apps/frontend/server/main.js:455544:42) [<root>]
    at Object.97670 (/Users/bart/workspace/msp-navigator/dist/apps/frontend/server/main.js:63091:81) [<root>]
    at __webpack_require__ (/Users/bart/workspace/msp-navigator/dist/apps/frontend/server/main.js:455544:42) [<root>]
    at Object.39100 (/Users/bart/workspace/msp-navigator/dist/apps/frontend/server/main.js:40899:99) [<root>]
    at __webpack_require__ (/Users/bart/workspace/msp-navigator/dist/apps/frontend/server/main.js:455544:42) [<root>]
```

The error is thrown from Domino, and the line in the firebase SDK that seems to be triggering it is 

```
const require$1 = module__default["default"].createRequire((typeof document === 'undefined' ? new (require('u' + 'rl').URL)('file:' + __filename).href : (document.currentScript && document.currentScript.src || new URL('index.node.cjs.js', document.baseURI).href)));
```

I tracked it down in the source code to this specific change: 
https://github.com/firebase/firebase-js-sdk/commit/4d36404812a7ca24ced5e1aabf6d8aa03de4e08a#diff-a233c3e0ac0fdbc396545af17e526b2a1163902c575b01329db7b2acc933b97cR43

I'm a bit stuck with this issue. Did the code change introduce an incompatibility between Domino and Firebase, or have I got things set up incorrectly?

Everything works fine when I'm on firebase 9.1.3

**Comment by Burgov** [comment]
Everything works as expected if i change

`typeof document === 'undefined'`
to 
`typeof global !== 'undefined'`

in the js file in my node_modules folder. Not sure how it should be solved on the source files though. I guess the fact that domino is defining `document` on `global` screws up the "hack"

**Comment by hsubox76** [comment]
I think we're going to end up reverting that change in favor of hardcoding the grpc version into Firestore, so hopefully that will fix this problem.

**Comment by hsubox76** [comment]
We've hardcoded the version in 9.6.1, has the issue gone away?
