### ISSUE TITLE
Maximum call stack exceeded while setting the `snapshot.ref` to null inside `child_added` callback.

### ISSUE THREAD

**Issue by itsmeneartou** [firebase/firebase-js-sdk#5733]
###  Describe your environment

  * Operating System version: Windows 10
  * Browser version:  Chrome Version:95.0.4638
  * Firebase SDK version:8.9.1
  * Firebase Product:realtime-database

#### Issue
I am listening for `child_added` event at a reference that is very busy i.e. many child events can occur in a short period of time.  In the callback for the `child_added` event after doing the work if the condition meets. I am setting the data to `null` at the reference of the snapshot received in the `child_added` callback. This leads to a `Maximum call stack size exceeded` error.

#### Steps to reproduce:
Below is the call stack from the Sentry dashboard.

```
RangeError: Maximum call stack size exceeded
  at e.remove(../../../src/background/../src/core/util/SortedMap.ts:316:3)
  at e.remove(../../../src/background/../src/core/util/SortedMap.ts:617:10)
  at e.updateImmediateChild(../../../src/background/../src/core/snap/ChildrenNode.ts:149:38)
  at e.updateChild(../../../src/background/../src/core/view/filter/IndexedFilter.ts:94:19)
  at bi(../../../src/background/../src/core/view/ViewProcessor.ts:493:51)
  at gi(../../../src/background/../src/core/view/ViewProcessor.ts:103:22)
  at Li(../../../src/background/../src/core/view/View.ts:213:18)
  at zi(../../../src/background/../src/core/SyncPoint.ts:107:9)
  at wo(../../../src/background/../src/core/SyncTree.ts:717:9)
  at wo(../../../src/background/../src/core/SyncTree.ts:706:9)
  at wo(../../../src/background/../src/core/SyncTree.ts:706:9)
  at Co(../../../src/background/../src/core/SyncTree.ts:664:10)
  at ao(../../../src/background/../src/core/SyncTree.ts:173:12)
  at Wa(../../../src/background/../src/core/Repo.ts:512:18)
  at Rs(../../../src/background/../src/exp/Reference_impl.ts:677:3)
  at t.set(../../../src/background/../src/api/Reference.ts:613:20)
  at ? (../../../src/background/event-listeners/firebase/on-remotely-filtered-hit-added.ts:39:25)
  at l(../../../src/background/../src/api/Reference.ts:253:16)
  at e.onValue(../../../src/background/../src/core/view/EventRegistration.ts:56:27)
  at ? (../../../src/background/../src/exp/Reference_impl.ts:924:30)
  at Y(../../../src/background/../src/core/util/util.ts:546:5)
  at Ia(../../../src/background/../src/core/view/EventQueue.ts:160:7)
  at ka(../../../src/background/../src/core/view/EventQueue.ts:128:9)
  at Ta(../../../src/background/../src/core/view/EventQueue.ts:108:3)
  at Wa(../../../src/background/../src/core/Repo.ts:541:3)
  at Rs(../../../src/background/../src/exp/Reference_impl.ts:677:3)
  at t.set(../../../src/background/../src/api/Reference.ts:613:20)
  at ? (../../../src/background/event-listeners/firebase/on-remotely-filtered-hit-added.ts:39:25)
  at l(../../../src/background/../src/api/Reference.ts:253:16)
  at e.onValue(../../../src/background/../src/core/view/EventRegistration.ts:56:27)
  at ? (../../../src/background/../src/exp/Reference_impl.ts:924:30)
  at Y(../../../src/background/../src/core/util/util.ts:546:5)
  at Ia(../../../src/background/../src/core/view/EventQueue.ts:160:7)
  at ka(../../../src/background/../src/core/view/EventQueue.ts:128:9)
  at Ta(../../../src/background/../src/core/view/EventQueue.ts:108:3)
  at Wa(../../../src/background/../src/core/Repo.ts:541:3)
  at Rs(../../../src/background/../src/exp/Reference_impl.ts:677:3)
  at t.set(../../../src/background/../src/api/Reference.ts:613:20)
  at ? (../../../src/background/event-listeners/firebase/on-remotely-filtered-hit-added.ts:39:25)
  at l(../../../src/background/../src/api/Reference.ts:253:16)
  at e.onValue(../../../src/background/../src/core/view/EventRegistration.ts:56:27)
  at ? (../../../src/background/../src/exp/Reference_impl.ts:924:30)
  at Y(../../../src/background/../src/core/util/util.ts:546:5)
  at Ia(../../../src/background/../src/core/view/EventQueue.ts:160:7)
  at ka(../../../src/background/../src/core/view/EventQueue.ts:128:9)
  at Ta(../../../src/background/../src/core/view/EventQueue.ts:108:3)
  at Wa(../../../src/background/../src/core/Repo.ts:541:3)
  at Rs(../../../src/background/../src/exp/Reference_impl.ts:677:3)
  at t.set(../../../src/background/../src/api/Reference.ts:613:20)
  at ? (../../../src/background/event-listeners/firebase/on-remotely-filtered-hit-added.ts:39:25)  //This is where snap.ref.set(null) is called.
```

#### Relevant Code:
```
let ref = rtdb.ref('foo');
ref.on('child_added',(snap)=>{
if(someCondition){
//Do the work
}
return snap.ref.set(null)
})
```

**Comment by jbalidiong** [comment]
Hi @itsmeneartou, thanks for reaching out to us. Just FYI, going forward, any fixes will be in version 9+. For minimal change, you can use the import paths require('firebase/compat/app') and require('firebase/compat/auth'). You can also check the documentation about upgrading from version 8 to the modular Web SDK for further information. With that, please try using the latest SDK and see if the behavior persists.
