### ISSUE TITLE
AttributeError: module 'google_auth_httplib2' has no attribute 'AuthorizedHttp' (python SDK)

### ISSUE THREAD

**Issue by halhwadi** [firebase/firebase-js-sdk#5750]
### [REQUIRED] Describe your environment

  * Operating System version: ___windows 10__
  * Browser version: __chrome___
  * Firebase SDK version: _5.1.0____
  * Firebase Product: _____ (messaging)

I'm working on[ firebase cloud messaging service SDK python ](https://firebase.google.com/docs/cloud-messaging/send-message)and I'm able to send msg to single device (token) but when i tried to send MultiCastMessage I got the below error , I have cloned this [repositry](https://github.com/googleapis/google-auth-library-python-httplib2) to get the latest google-auth-httplib2, however I ended up with below error which has no relevant results in google, I can see AuthorizedHttp class in google-auth-httplib2.py, please advise?

Traceback (most recent call last):
File "", line 1, in
File "C:\Users\Husam.Alhwadi\Envs\test\lib\site-packages\firebase_admin\messaging.py", line 167, in send_multicast
return _get_messaging_service(app).send_all(messages, dry_run)
File "C:\Users\Husam.Alhwadi\Envs\test\lib\site-packages\firebase_admin\messaging.py", line 377, in send_all
transport = self._build_transport(self._credential)
File "C:\Users\Husam.Alhwadi\Envs\test\lib\site-packages\googleapiclient_auth.py", line 117, in authorized_http
return google_auth_httplib2.AuthorizedHttp(credentials, http=build_http())
AttributeError: module 'google_auth_httplib2' has no attribute 'AuthorizedHttp'

#### Steps to reproduce:

```
>>> import google_auth_httplib2
>>> import Bikum.settings as settings
>>> import firebase_admin
>>> from firebase_admin import messaging
>>> from firebase_admin import credentials
>>> from django.contrib.auth.models import User
>>> from chat.models import TokenModel
>>> user_sys = User.objects.get(email='driver6@bikum.org')
>>> tokens = TokenModel.objects.get(user_sys=user_sys).value
>>> cred = credentials.Certificate(settings.GOOGLE_APPLICATION_CREDENTIALS)
>>> default_app = firebase_admin.initialize_app(cred)
>>> message = messaging.MulticastMessage(data={'score': '850','time': '2:45'}, notification=messaging.Notification(title= '21Nov', body= 'thanks'),toke
ns=tokens)
>>> response = messaging.send_multicast(message)
```

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by halhwadi** [comment]
Its solved..
At first I faced issue in getting google_auth_httplib2 model, which by default installed as part of firebase_admin sdk, but when I checked the folder i found only dist folder is there, i have uninstall google_auth_httplib2 and install it again but issue still there, So i cloned from github, after that i got error because of import statement in _auth.py file from googleapiclient package  so i changed the import statement, solution steps are mentioned here if someone else faced the same issue:

solution steps:
1-clone the  google_auth_http2" because pip didn't install the complete stuff, only dist file is there..
2- change the import statement in _auth.py line (28) in googleapiclient package :

from:
try:
`import google_auth_httplib2`

To:
```
try:
    import google_auth_httplib2_0.google_auth_httplib2 as google_auth_httplib2

```
take care to rename the google_auth_httplib2_XXXX folder to any other name rather than "google_auth_httplib2", In my case ; I changed to google_auth_httplib2_0
