### ISSUE TITLE
SvelteKit with Firebase >= v9.3.0 dev server errors

### ISSUE THREAD

**Issue by kenkunz** [firebase/firebase-js-sdk#5758]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 11.6.1
  * Browser version: Google Chrome 96.0.4664.55
  * Firebase SDK version: 9.3.0 (and newer)
  * Firebase Product: auth, functions, storage

### [REQUIRED] Describe the problem

I am using Firebase (`auth` and `firestore`) in a SvelteKit project. I recently tried upgrading from `9.2.0` to the `9.5.0` (latest) and encountered an error with `firebase/auth` when running SvelteKit `dev` server (as well as a warning when running `build` with the reference `node` adapter).

I created a minimal app to identify what dependencies/versions are required in order to reproduce the issue. This occurs when using any recent version of SvelteKit along with Firebase `>=9.3.0`. In addition to `firebase/auth`, the same error occurs when importing anything from `firebase/functions` or `firebase/storage`. This error does _not_ occur with some other Firebase packages (I tested `firebase/app` and `firebase/firestore`).

Note that a previous build issue that I reported with `9.0.1` (#5499) was fixed with `9.1.0`.

#### Steps to reproduce:

1. Create a skeleton [Sveltekit](https://kit.svelte.dev) app:
    ```
    $ npm init svelte@next sveltekit-firebase
    > Skeleton project
    > No Typescript
    > No ESLint
    > No Prettier
    ``` 
2. Install Firebase `9.3.0` or later
    ```
    $ cd sveltekit-firebase
    $ npm i firebase@9.3.0
    ```
3. Edit `src/routes/index.svelte` to import `firebase/auth`
    Add this to the top of the file:
    ```svelte
    <script>
      import { getAuth } from 'firebase/auth';
    </script>
    ```
4. Run the dev server
    ```
    $ npm run dev
    ```
5. Open a browser and load (http://localhost:3000)
6. Note the error output in the `dev` terminal
   * see **Dev Server Error Output** below
   * This error only occurs the first time the route is loaded for a given `dev` process. Try reloading the page and note that the error does not occur.
7. Revert `firebase` to `9.2.0`
    ```
    $ npm i firebase@9.2.0
    ```
8. Repeat steps 4-5; note that the error does not occur
   * Be sure to re-start the `dev` server to ensure that you are testing the first load of the route for the process (don't rely on HMR).

In addition to the `dev` server error, building with `>=9.3.0` results in a warning when using the reference `node` adapter.

9. Install the node adapter
    ```
    $ npm i -D @sveltejs/adapter-node@next
    ```
10. Edit `./svelte.config.js` to use the adapter
    ```javascript
    /** @type {import('@sveltejs/kit').Config} */
    import nodeAdapter from "@sveltejs/adapter-node";

    const config = {
      kit: {
        adapter: nodeAdapter(),
        // hydrate the <div id="svelte"> element in src/app.html
        target: "#svelte",
      },
    };

    export default config;
    ```
11. Build the project
    ```
    $ npm run build
    ```
12. Note the Build Warning Output below

#### Dev Server Error Output
Excluding unrelated deprecation warning.
```
1:50:30 PM [vite] Error when evaluating SSR module /node_modules/whatwg-url/lib/public-api.js?v=f858f299:
ReferenceError: exports is not defined
    at /node_modules/whatwg-url/lib/public-api.js?v=f858f299:3:1
    at instantiateModule (/Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66544:15)
1:50:30 PM [vite] Error when evaluating SSR module /node_modules/node-fetch/lib/index.mjs?v=f858f299:
ReferenceError: exports is not defined
    at /node_modules/whatwg-url/lib/public-api.js?v=f858f299:1:1
    at instantiateModule (/Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66544:15)
1:50:30 PM [vite] Error when evaluating SSR module /node_modules/@firebase/auth/dist/node-esm/index.js?v=f858f299:
TypeError: Line must be greater than or equal to 1, got -1
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:65405:13)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:65474:22)
    at /Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66413:34
    at String.replace (<anonymous>)
    at /Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66403:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66402:10)
    at instantiateModule (/Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66547:28)
1:50:30 PM [vite] Error when evaluating SSR module /node_modules/firebase/auth/dist/index.mjs?v=f858f299:
TypeError: Line must be greater than or equal to 1, got -1
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:65405:13)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:65474:22)
    at /Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66413:34
    at String.replace (<anonymous>)
    at /Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66403:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66402:10)
    at instantiateModule (/Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66547:28)
1:50:30 PM [vite] Error when evaluating SSR module /src/routes/index.svelte:
TypeError: Line must be greater than or equal to 1, got -1
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:65405:13)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:65474:22)
    at /Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66413:34
    at String.replace (<anonymous>)
    at /Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66403:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66402:10)
    at instantiateModule (/Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66547:28)
Line must be greater than or equal to 1, got -1
TypeError: Line must be greater than or equal to 1, got -1
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:65405:13)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:65474:22)
    at /Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66413:34
    at String.replace (<anonymous>)
    at /Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66403:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66402:10)
    at instantiateModule (/Users/ken/Code/sandbox/sk-fb-2/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66547:28)
```

#### Build Warning Output
```
> Using @sveltejs/adapter-node
 > .svelte-kit/output/server/chunks/index-43e607bd.js:924:23: warning: Comparison with -0 using the "===" operator will also match 0
    924 │       } else if (x === -0) {
        ╵                        ~~
```

**Comment by benmccann** [comment]
I haven't tested, but I would expect this is fixed with Vite 2.7, currently in beta. You could try using `pnpm` rather than `npm` and then using [the `overrides` functionality](https://pnpm.io/package_json#pnpmoverrides) to set the Vite version to `2.7.0-beta.8` until a final version is released

**Comment by dnotes** [comment]
I got this error, and as a workaround I added to svelte config:
```
kit: {
  vite: {
    ssr: {
      external: ['whatwg-url','node-fetch']
    }
```

**Comment by kenkunz** [comment]
@dnotes workaround above solves this for now! Thanks!

**Comment by dnotes** [comment]
FWIW, I just tested upgrading to Vite 2.7.0-beta.8 and the error still occurred without the workaround above.

**Comment by benmccann** [comment]
I just tried Vite 2.7.0-beta.8 and didn't encounter any issues following the reproduction steps above. 

I included it in my project with:
```
  "pnpm": {
    "overrides": {
      "vite": "2.7.0-beta.8"
    }
  }
```

And then built and ran my project with `pnpm` instead of `npm`.

I only got two minor warnings:
> [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at node_modules/.pnpm/@firebase+auth@0.19.3_@firebase+app@0.7.9/node_modules/tslib/package.json
> "getAuth" is imported from external module "firebase/auth" but never used in "src/routes/index.svelte"

**Comment by kenkunz** [comment]
@benmccann I just tried your solution – works great. I'll take this as my cue to finally switch to `pnpm` (seems great… just haven't needed it til now).

Since this issue is addressed an a forthcoming `vite` update, is there any reason to keep this `firebase` issue open?

**Comment by benmccann** [comment]
No, I think you can close it

The only thing that might be an issue is the "TypeError: Line must be greater than or equal to 1, got -1" message. But I don't know the sourcemap spec well enough to know if that's an issue in Firebase or Vite

**Comment by kenkunz** [comment]
Thanks! Not sure about the sourcemaps either… but `vite@beta` seems to fix it 🤷 

Closing for now unless Firebase maintainers decide to re-open.
