### ISSUE TITLE
Firebase Authentication ( signin ) failing with firebase npm module error 

### ISSUE THREAD

**Issue by rajathongal** [firebase/firebase-js-sdk#5840]
_* Operating System version: MacOS Monterey 12.1
  * Browser version: Chrome Version 96.0.4664.110 (Official Build) (x86_64)
  * Firebase SDK version: 9.6.1
  * Firebase Product: Authentication_ 
  
  **Problem -** 
  
  **When trying to Login user by firebase signInWithEmailAndPassword method, the below error is occurring.** 

  ```
backend/node_modules/@firebase/auth/dist/node/index-fe696f9c.js:506
        return (_a = authOrCode._errorFactory).create.apply(_a, tslib.__spreadArray([code], fullParams));
                                               ^

 TypeError: Cannot read properties of undefined (reading 'create')
    at createErrorInternal (/node_modules/@firebase/auth/dist/node/index-fe696f9c.js:506:48)
    at _createError (node_modules/@firebase/auth/dist/node/index-fe696f9c.js:484:32)
    at Timeout._onTimeout (/node_modules/@firebase/auth/dist/node/index-fe696f9c.js:1091:31)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```
    
  **Authentication method is used in backend side ( NodeJS ) and below is the method**
     
```
    const { signInWithEmailAndPassword, signInWithCustomToken } = require("firebase/auth");
    const { auth, db } = require("../../utils/firebaseClient");

    signInWithEmailAndPassword(auth, email, password). // Fails exactly at this step 
        .then(async(userCredential) => {}) 
```

**Comment by puf** [comment]
Also posted on https://stackoverflow.com/q/70519291

**Comment by jbalidiong** [comment]
Hi @rajathongal, thanks for reaching out. A reproducible example would be ideal, but in the meantime, could you share a few more details?
