### ISSUE TITLE
Unknown: None Stream removed

### ISSUE THREAD

**Issue by zdhernandez** [firebase/firebase-js-sdk#5850]
I've been getting this while running code in a Docker image from: FROM gcr.io/deeplearning-platform-release/base-cu113

And I have no clue what it is or why this is happening.

This is the code I ran and the last batch.commit() is  line # 1186 in the stack trace:
```
            batch = db.batch()
            batch_counter = 0

            for speechID, translatedSpeechSentenceAudio_dict in temporary_dict.items():
                ts_ref = narrated_speeches_ref.document(speechID)
                batch.update(ts_ref, translatedSpeechSentenceAudio_dict)

                if batch_counter > 450:
                    # Commit the batch to avoid exceeding batch limits on Firestore
                    batch.commit()
                    batch_counter = 0
                batch_counter += 1

            batch.commit()
```

```
E0103 04:45:52.108599360       1 ssl_transport_security.cc:523] Corruption detected.
E0103 04:45:52.108658012       1 ssl_transport_security.cc:499] error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac
E0103 04:45:52.108665003       1 secure_endpoint.cc:205]     Decryption error: TSI_DATA_CORRUPTED
E0103 04:45:52.108747272       1 ssl_transport_security.cc:550] SSL_write failed with error SSL_ERROR_SYSCALL.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 66, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/conda/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Stream removed"
	debug_error_string = "{"created":"@1641185152.108710407","description":"Error received from peer ipv4:142.250.73.234:443","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"Stream removed","grpc_status":2}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./app/main.py", line 1296, in <module>
    transcode_original_narrated_videos(batch_size=25)
  File "./app/main.py", line 1186, in transcode_original_narrated_videos
    batch.commit()
  File "/opt/conda/lib/python3.7/site-packages/google/cloud/firestore_v1/batch.py", line 60, in commit
    request=request, metadata=self._client._rpc_metadata, **kwargs,
  File "/opt/conda/lib/python3.7/site-packages/google/cloud/firestore_v1/services/firestore/client.py", line 815, in commit
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 68, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.Unknown: None Stream removed


```

```
And my requirements.txt file is:

# Google Cloud Platform Dependencies
firebase-admin
google-api-python-client
google-cloud-error-reporting
google-cloud-secret-manager
google-cloud-firestore
google-cloud-core
google-cloud-pubsub
google-cloud-translate
google-cloud-speech
google-cloud-texttospeech
google-cloud-storage

# Others
flask==2.0.2
python-dateutil
keyring
keyrings.google-artifactregistry-auth
twine
setuptools
wheel
build

opencv-contrib-python-headless
pydub==0.25.1
audioread==2.1.9
nltk==3.6.3
scikit-learn==0.24.2
Werkzeug 
```

**Comment by thebrianchen** [comment]
@zdhernandez This is the repo for the JS client SDKs. Can you please file a ticket with the [python server SDK](https://github.com/googleapis/python-firestore?

Closing the issue.
