### ISSUE TITLE
Firebase 9.8.0 with React: Testing with Jest throws "INTERNAL ASSERTION FAILED: Expected a class definition" error

### ISSUE THREAD

**Issue by anneHell** [firebase/firebase-js-sdk#6265]
### Environment

  * Operating System version: MacOS Big Sur Version 11.5.2
  * Browser version: no browser used
  * Firebase SDK version: 9.8.0

#### Steps to reproduce:
I am testing my React app with Jest and Enzyme. I use Firebase as well and when I try to write tests for my pages which use a Header component with Firebase signin, I get the following error: "Test suite failed to run: INTERNAL ASSERTION FAILED: Expected a class definition"

Full error message:

```
INTERNAL ASSERTION FAILED: Expected a class definition

  42 | firebase.initializeApp(config);
  43 |
> 44 | export const auth = firebase.auth();
     |                              ^
  45 | export const firestore = firebase.firestore();
  46 |
  47 | const provider = new firebase.auth.GoogleAuthProvider();

  at debugFail (node_modules/@firebase/auth/src/core/util/assert.ts:256:9)
  at debugAssert (node_modules/@firebase/auth/src/core/util/assert.ts:271:5)
  at Object._getInstance (node_modules/@firebase/auth/src/core/util/instantiator.ts:34:3)
  at new CompatPopupRedirectResolver (node_modules/@firebase/auth-compat/src/popup_redirect.ts:29:9)
  at _getInstance (node_modules/@firebase/auth/src/core/util/instantiator.ts:45:14)
  at AuthImpl.Object.<anonymous>.AuthImpl._initializeWithPersistence (node_modules/@firebase/auth/src/core/auth/auth_impl.ts:121:37)
  at _initializeAuthInstance (node_modules/@firebase/auth/src/core/auth/initialize.ts:86:8)
  at node_modules/@firebase/auth/src/core/auth/register.ts:87:11
  at Component.instanceFactory (node_modules/@firebase/auth/src/core/auth/register.ts:90:10)
  at Provider.Object.<anonymous>.Provider.getOrInitializeService (node_modules/@firebase/component/src/provider.ts:318:33)
  at Provider.Object.<anonymous>.Provider.initialize (node_modules/@firebase/component/src/provider.ts:242:27)
  at new Auth (node_modules/@firebase/auth-compat/src/auth.ts:68:31)
  at Component.instance.INTERNAL.registerComponent.component.Component.setServiceProps.ActionCodeInfo.Operation.EMAIL_SIGNIN [as instanceFactory] (node_modules/@firebase/auth-compat/index.ts:82:16)
  at Provider.Object.<anonymous>.Provider.getOrInitializeService (node_modules/@firebase/component/src/provider.ts:318:33)
  at Provider.Object.<anonymous>.Provider.getImmediate (node_modules/@firebase/component/src/provider.ts:115:21)
  at FirebaseAppImpl.Object.<anonymous>.FirebaseAppImpl._getService (node_modules/@firebase/app-compat/src/firebaseApp.ts:138:21)
  at FirebaseAppImpl.firebaseAppImpl.<computed> [as auth] (node_modules/@firebase/app-compat/src/firebaseNamespaceCore.ts:185:29)
  at Object.auth (node_modules/@firebase/app-compat/src/firebaseNamespaceCore.ts:166:59)
  at Object.<anonymous> (src/firebase/firebase.utils.js:44:30)
  at Object.<anonymous> (src/components/header/header.component.jsx:6:1)
  at Object.<anonymous> (src/pages/finder/finder.component.jsx:5:1)
  at Object.<anonymous> (src/pages/finder/finder.test.js:3:1)
```

#### Relevant Code:

This is my Firebase configuration file:
```
import firebase from 'firebase/compat/app';
import 'firebase/compat/firestore';
import 'firebase/compat/auth';

const config = {
    ...
  }

export const createUserProfileDocument = async (userAuth, additionalData) => {
  if (!userAuth) return;

  const userRef = firestore.doc(`users/${userAuth.uid}`); 
  
  const snapShot = await userRef.get();

  if(!snapShot.exist) {
    const { displayName, email } = userAuth;
    const createdAt = new Date();

    try {
      await userRef.set({
        displayName,
        email,
        createdAt,
        ...additionalData
      })
    } catch (error) {
      console.log("error creating user", error.message);
    }
  }

  return userRef;

}

```

**Comment by sam-gc** [comment]
The error indicates that the SDK isn't finding the persistence objects. Can you describe how this testing framework works? Does it run in a Node environment, for example?

**Comment by anneHell** [comment]
Hi. Yes, Jest is running on Node. Here are the Doc files: https://jestjs.io/docs/getting-started
