### ISSUE TITLE
firebase emulator rules context/enviornment not clearing between tests

### ISSUE THREAD

**Issue by janitha09** [firebase/firebase-js-sdk#6361]
### [REQUIRED] Environment info

**firebase-tools:** 11.0.1

**Platform:**
uname -a
Linux 214c0f395319 5.15.0-33-generic firebase/firebase-tools#34-Ubuntu SMP Wed May 18 13:34:26 UTC 2022 x86_64 GNU/Linux

### [REQUIRED] Test case

see below

### [REQUIRED] Steps to reproduce

**Describe the bug**
I am trying to develop rules using the emulator for my collections. To do so I have the tests below that let me experiment

**To Reproduce**

```typescript
import {
  assertFails,
  assertSucceeds,
  initializeTestEnvironment,
} from '@firebase/rules-unit-testing';
import test from 'ava';
import { doc, setDoc } from 'firebase/firestore';

test('create an organization fails with rule', async (t) => {
  const rule = `service cloud.firestore {
    match /databases/{database}/documents {
      match /Organizations/{organization} {
        allow read, write: if false;
      }
    }
  }`;
  const testEnv = await initializeTestEnvironment({
    projectId: 'fs-sec',
    firestore: {
      host: 'localhost',
      port: 8080,
      rules: rule,
    },
  });

  const orgAdmin = testEnv.authenticatedContext('org-admin');
  const db = orgAdmin.firestore();
  await assertFails(
    setDoc(doc(db, 'Users', 'user1'), {
      name: 'user 1',
    })
  );
  await assertFails(
    setDoc(doc(db, 'Organizations', 'Org1'), {
      name: 'Organization 1',
    })
  );
  await testEnv.clearFirestore();
  await testEnv.cleanup();
  t.is(1, 1);
});

test('create an organization success with rule', async (t) => {
  const rule = `service cloud.firestore {
    match /databases/{database}/documents {
      match /Organizations/{organization} {
        allow read, write: if true;
      }
    }
  }`;
  const testEnv = await initializeTestEnvironment({
    projectId: 'fs-sec',
    firestore: {
      host: 'localhost',
      port: 8080,
      rules: rule,
    },
  });

  const orgAdmin = testEnv.authenticatedContext('org-admin'); 
  const db = orgAdmin.firestore();
  await assertFails(
    setDoc(doc(db, 'Users', 'user1'), {
      name: 'user 1',
    })
  ); 
  await assertSucceeds(
    setDoc(doc(db, 'Organizations', 'Org1'), {
      name: 'Organization 1',
    })
  );
  await testEnv.clearFirestore();
  await testEnv.cleanup();
  t.is(1, 1);
});

```
running these tests together produces the following test error
```sh
[2022-05-18T19:26:05.481Z]  @firebase/firestore: Firestore (9.8.1): Connection GRPC stream error. Code: 7 Message: 7 PERMISSION_DENIED: No matching allow statements
[2022-05-18T19:26:05.486Z]  @firebase/firestore: Firestore (9.8.1): Connection GRPC stream error. Code: 7 Message: 7 PERMISSION_DENIED: No matching allow statements
  firestorecrud.ts › create an organization fails with rule

  src/lib/firestorecrud.spec.ts:33

   32:   );                                          
   33:   await assertFails(                          
   34:     setDoc(doc(db, 'Organizations', 'Org1'), {

  Rejected promise returned by test. Reason:

  Error {
    message: 'Expected request to fail, but it succeeded.',
  }

  › node_modules/@firebase/rules-unit-testing/src/util.ts:138:9
  › src/lib/firestorecrud.spec.ts:33:3

  ─

  1 test failed
```
the firestore-debug.log
```sh
May 18, 2022 7:33:12 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
May 18, 2022 7:33:12 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
May 18, 2022 7:33:12 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected HTTP/2 connection.
May 18, 2022 7:33:12 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: No matching allow statements
com.google.cloud.datastore.core.exception.DatastoreException: No matching allow statements
	at com.google.cloud.datastore.core.exception.DatastoreException$Builder.build(DatastoreException.java:111)
	at com.google.cloud.datastore.emulator.impl.rules.EmulatorRulesAuthorizer.verboseError(EmulatorRulesAuthorizer.java:286)
	at com.google.cloud.datastore.emulator.impl.rules.EmulatorRulesAuthorizer.withVerboseErrors(EmulatorRulesAuthorizer.java:263)
	at com.google.cloud.datastore.emulator.impl.rules.EmulatorRulesAuthorizer.checkCommit(EmulatorRulesAuthorizer.java:118)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1.commitHelper(CloudFirestoreV1.java:950)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1.internalCommit(CloudFirestoreV1.java:856)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1.internalCommit(CloudFirestoreV1.java:839)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1.write(CloudFirestoreV1.java:828)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1WriteStream.handleRequest(CloudFirestoreV1WriteStream.java:208)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1WriteStream.write(CloudFirestoreV1WriteStream.java:136)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1WriteStream.onNext(CloudFirestoreV1WriteStream.java:92)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1WriteStream.onNext(CloudFirestoreV1WriteStream.java:25)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:262)
	at io.grpc.ForwardingServerCallListener.onMessage(ForwardingServerCallListener.java:33)
	at io.grpc.Contexts$ContextualizedServerCallListener.onMessage(Contexts.java:76)
	at io.grpc.ForwardingServerCallListener.onMessage(ForwardingServerCallListener.java:33)
	at io.grpc.Contexts$ContextualizedServerCallListener.onMessage(Contexts.java:76)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:318)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:301)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:834)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

May 18, 2022 7:33:12 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: No matching allow statements
com.google.cloud.datastore.core.exception.DatastoreException: No matching allow statements
	at com.google.cloud.datastore.core.exception.DatastoreException$Builder.build(DatastoreException.java:111)
	at com.google.cloud.datastore.emulator.impl.rules.EmulatorRulesAuthorizer.verboseError(EmulatorRulesAuthorizer.java:286)
	at com.google.cloud.datastore.emulator.impl.rules.EmulatorRulesAuthorizer.withVerboseErrors(EmulatorRulesAuthorizer.java:263)
	at com.google.cloud.datastore.emulator.impl.rules.EmulatorRulesAuthorizer.checkCommit(EmulatorRulesAuthorizer.java:118)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1.commitHelper(CloudFirestoreV1.java:950)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1.internalCommit(CloudFirestoreV1.java:856)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1.internalCommit(CloudFirestoreV1.java:839)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1.write(CloudFirestoreV1.java:828)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1WriteStream.handleRequest(CloudFirestoreV1WriteStream.java:208)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1WriteStream.write(CloudFirestoreV1WriteStream.java:136)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1WriteStream.onNext(CloudFirestoreV1WriteStream.java:92)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1WriteStream.onNext(CloudFirestoreV1WriteStream.java:25)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:262)
	at io.grpc.ForwardingServerCallListener.onMessage(ForwardingServerCallListener.java:33)
	at io.grpc.Contexts$ContextualizedServerCallListener.onMessage(Contexts.java:76)
	at io.grpc.ForwardingServerCallListener.onMessage(ForwardingServerCallListener.java:33)
	at io.grpc.Contexts$ContextualizedServerCallListener.onMessage(Contexts.java:76)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:318)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:301)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:834)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

May 18, 2022 7:33:12 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
May 18, 2022 7:33:12 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

package.json
```json
{
  "name": "typescript-starter-firebase",
  "version": "1.0.0",
  "description": "firebase no admin",
  "main": "build/main/index.js",
  "typings": "build/main/index.d.ts",
  "module": "build/module/index.js",
  "repository": "https://github.com/janitha09/typescript-starter-firebase",
  "license": "MIT",
  "keywords": [],
  "scripts": {
    "build": "run-p build:*",
    "build:main": "tsc -p tsconfig.json",
    "build:module": "tsc -p tsconfig.module.json",
    "fix": "run-s fix:*",
    "fix:prettier": "prettier \"src/**/*.ts\" --write",
    "fix:lint": "eslint src --ext .ts --fix",
    "test": "run-s build test:*",
    "test:lint": "eslint src --ext .ts",
    "test:prettier": "prettier \"src/**/*.ts\" --list-different --write",
    "test:unit": "nyc ava",
    "check-cli": "run-s test diff-integration-tests check-integration-tests",
    "check-integration-tests": "run-s check-integration-test:*",
    "diff-integration-tests": "mkdir -p diff && rm -rf diff/test && cp -r test diff/test && rm -rf diff/test/test-*/.git && cd diff && git init --quiet && git add -A && git commit --quiet --no-verify --allow-empty -m 'WIP' && echo '\\n\\nCommitted most recent integration test output in the \"diff\" directory. Review the changes with \"cd diff && git diff HEAD\" or your preferred git diff viewer.'",
    "watch:build": "tsc -p tsconfig.json -w",
    "watch:test": "nyc --silent ava --watch",
    "cov": "run-s build test:unit cov:html cov:lcov && open-cli coverage/index.html",
    "cov:html": "nyc report --reporter=html",
    "cov:lcov": "nyc report --reporter=lcov",
    "cov:send": "run-s cov:lcov && codecov",
    "cov:check": "nyc report && nyc check-coverage --lines 100 --functions 100 --branches 100",
    "doc": "run-s doc:html && open-cli build/docs/index.html",
    "doc:html": "typedoc src/ --exclude **/*.spec.ts --target ES6 --mode file --out build/docs",
    "doc:json": "typedoc src/ --exclude **/*.spec.ts --target ES6 --mode file --json build/docs/typedoc.json",
    "doc:publish": "gh-pages -m \"[ci skip] Updates\" -d build/docs",
    "version": "standard-version",
    "reset-hard": "git clean -dfx && git reset --hard && npm i",
    "prepare-release": "run-s reset-hard test cov:check doc:html version doc:publish"
  },
  "engines": {
    "node": ">=10"
  },
  "dependencies": {
    "@bitauth/libauth": "^1.17.1"
  },
  "devDependencies": {
    "@ava/typescript": "^1.1.1",
    "@firebase/rules-unit-testing": "^2.0.2",
    "@istanbuljs/nyc-config-typescript": "^1.0.1",
    "@typescript-eslint/eslint-plugin": "^4.0.1",
    "@typescript-eslint/parser": "^4.0.1",
    "ava": "^3.12.1",
    "codecov": "^3.5.0",
    "cspell": "^4.1.0",
    "cz-conventional-changelog": "^3.3.0",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-eslint-comments": "^3.2.0",
    "eslint-plugin-functional": "^3.0.2",
    "eslint-plugin-import": "^2.22.0",
    "firebase": "^9.8.1",
    "gh-pages": "^3.1.0",
    "npm-run-all": "^4.1.5",
    "nyc": "^15.1.0",
    "open-cli": "^6.0.1",
    "prettier": "^2.1.1",
    "standard-version": "^9.0.0",
    "ts-node": "^9.0.0",
    "typedoc": "^0.19.0",
    "typescript": "^4.5.5"
  },
  "files": [
    "build/main",
    "build/module",
    "!**/*.spec.*",
    "!**/*.json",
    "CHANGELOG.md",
    "LICENSE",
    "README.md"
  ],
  "ava": {
    "failFast": true,
    "timeout": "60s",
    "typescript": {
      "rewritePaths": {
        "src/": "build/main/"
      }
    },
    "files": [
      "!build/module/**"
    ]
  },
  "config": {
    "commitizen": {
      "path": "cz-conventional-changelog"
    }
  },
  "prettier": {
    "singleQuote": true
  },
  "nyc": {
    "extends": "@istanbuljs/nyc-config-typescript",
    "exclude": [
      "**/*.spec.js"
    ]
  }
}
```

### [REQUIRED] Expected behavior

The documentation implies that calling `testEnv.cleanup()` allows one to clean up the rules between tests. This doesn't appear to be happening

Running a test at a time produces a passing result i.e. the asserts are valid.

### [REQUIRED] Actual behavior

Tests cannot be run see debug log above
this was asked here https://github.com/firebase/firebase-tools-ui/issues/772

**Comment by yuchenshi** [comment]
Are your tests running in parallel or out of order by any chance? RUT test environments are isolated by `projectId` and you can set `projectId: 'fs-sec' + randomSuffix` in each test to avoid the problem.

If not, we'd need a self-contained repro in order to look into this problem. Consider creating a GitHub repo with all setup, test scripts and `firestore.rules`.
