### ISSUE TITLE
Angular Material Jasmine Karma initializeTestEnvironment with rules 

### ISSUE THREAD

**Issue by weilinzung** [firebase/firebase-js-sdk#6400]
### [REQUIRED] Describe your environment

  * Operating System version: ___MacOS Monterey__
  * Browser version: __Chrome Version 103.0.5060.53 (Official Build) (x86_64)___
  * Firebase SDK version: _@firebase/rules-unit-testing _2.0.3___
  * Firebase Product: _database____ (auth, database, storage, etc)

#### Steps to reproduce:

- The latest version of `@firebase/rules-unit-testing: 2.0.3` is required to better use Node for operating now
- We are using Angular Material and AngularFire Compat which with Jasmine & Karma
- First of all, we can't use `fs` to read the rule.json while initializing the test
- And, we couldn't do a plain string way because the below error

#### Relevant Code:

```javascript
    this.testEnv = await initializeTestEnvironment({
      projectId: environment.firebase.projectId,
      hub: {
        host: 'localhost',
        port: 4400
      },
      database: {
        rules: '{ "rules": {} }',
      }
    });
```

```
TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation

    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:1465:1
    at Object.proto.<computed> [as default] (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:975:1)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@firebase/rules-unit-testing/dist/index.cjs.js:507:1
    at step (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@firebase/rules-unit-testing/dist/index.cjs.js:74:1)
    at Object.next (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@firebase/rules-unit-testing/dist/index.cjs.js:55:46)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@firebase/rules-unit-testing/dist/index.cjs.js:48:1
    at new ZoneAwarePromise (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:1387:1)
    at __awaiter (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@firebase/rules-unit-testing/dist/index.cjs.js:44:1)
    at loadDatabaseRules (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@firebase/rules-unit-testing/dist/index.cjs.js:500:1)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@firebase/rules-unit-testing/dist/index.cjs.js:655:1
```

Is any better way to support "webApp" for @firebase/rules-unit-testing? Also, is "js-sdk" should be "plain" JS without NodeJs?

**Comment by staugaard** [comment]
I'm running into the same issue here. I was trying to run storybook via `firebase emulators:exec` and then set up an authenticated text context for my stories to run in. It looks like `@firebase/rules-unit-testing` is only compatible with a nodejs environment.
