### ISSUE TITLE
An error is thrown in emulator mode when passing POJO wrapped in a proxy to `httpsCallable`

### ISSUE THREAD

**Issue by jorroll** [firebase/firebase-js-sdk#6429]
### [REQUIRED] Describe your environment

  * Operating System version: Computer is running macOS 12.4 but code is running inside a devcontainer running Debian GNU/Linux 11 (bullseye) (the container is `mcr.microsoft.com/vscode/devcontainers/typescript-node:0-16-bullseye`
  * Browser version: Google Chrome 103.0.5060.114
  * Firebase SDK version: 9.8.3
  * Firebase Product: Cloud Functions (in emulator)

### [REQUIRED] Describe the problem

I'm passing a simple javascript object which has been wrapped in a javascript Proxy object to the httpsCallable function (i.e. `httpsCallable(/* ...stuff... */)(myObjectWrappedInProxy)`) and the following error is thrown:

```
Uncaught (in promise) TypeError: o.hasOwnProperty is not a function
    at mapValues (serializer.ts:28:11)
    at encode (serializer.ts:66:12)
    at callAtURL (service.ts:275:10)
    at call (service.ts:260:10)
    at service.ts:185:12
    at NewWorkspaceDialog.tsx:102:26
    at loading.service.ts:76:14
    at onlyCallOnceWhilePending.ts:16:12
    at handleSubmit (utils.ts:30:10)
    at Object.callback (NewWorkspaceDialog.tsx:70:15)
```

#### Steps to reproduce:

Wrap a simple javascript object such as `{ name: "Green" }` with a proxy and pass it as an argument to httpCallable.

Error thrown:
```
Uncaught (in promise) TypeError: o.hasOwnProperty is not a function
    at mapValues (serializer.ts:28:11)
    at encode (serializer.ts:66:12)
    at callAtURL (service.ts:275:10)
    at call (service.ts:260:10)
    at service.ts:185:12
    at NewWorkspaceDialog.tsx:102:26
    at loading.service.ts:76:14
    at onlyCallOnceWhilePending.ts:16:12
    at handleSubmit (utils.ts:30:10)
    at Object.callback (NewWorkspaceDialog.tsx:70:15)
```

#### Relevant Code:

Let me know if you need a reproduction for this. I'm guessing someone reading this issue will be like, "Oh ya, we didn't consider that a proxy might be passed to the serializer function." The workaround is to use something like a spread to convert the argument to a POJO (e.g. `{ ...myObjectWrappedInProxy }`). This becomes more annoying if the argument contains nested objects though.

### Expected behavior

I wouldn't expect wrapping something in a proxy to affect its serializability, but maybe that has a larger impact than I realized.

### Additional details

I'm experiencing this problem using the Firebase emulators. It seems possible (likely?) that it affects the non-emulator code as well, though I haven't tested.

**Comment by jorroll** [comment]
> I'm not very familiar with Proxy objects so maybe you can help me out.

I'm afraid that I don't have much familiarity myself. I (incorrectly) assumed there was a trivial way to check if something was a proxy.

> but it seems like it's pretty tricky to identify if something is a proxy?

Your comment made me look into it and you're correct. There doesn't appear to be a general method to check if something is a proxy (the creator of the proxy can build in a method to check for this, but the spec allows for proxies which are indistinguishable from their unwrapped counterpart).

Given this, arguably this is actually a bug with the (Solidjs) library I'm using which is returning the proxies. I just went to report this issue over there, and I see that [someone else beat me to it](https://github.com/solidjs/solid/issues/1112) (and it looks like the fix has already been merged but not yet released).

I'm going to close this issue. This doesn't seem like a Firestore issue but actually a flaw with the proxy I'm using. Thanks for the response!
