### ISSUE TITLE
FIRESTORE (8.10.1) INTERNAL ASSERTION FAILED: Unexpected state when using react-scripts version 4+ (easily reproducible)

### ISSUE THREAD

**Issue by jtestard** [firebase/firebase-js-sdk#6658]
### [REQUIRED] Describe your environment

  * Operating System version: OS X
  * Browser version: N/A
  * Firebase SDK version: 9
  * Firebase Product: firestore emulator / firestore rules unit testing

#### Steps to reproduce:

A repo https://github.com/jtestard/firebase-emulator-react-scripts/tree/main has been created to easily reproduce the error when using the `'@firebase/rules-unit-testing'` SDK and firestore emulator.

To reproduce, clone then repo and run:

```
cd my-app
yarn install
yarn test
```

You will get this output

```
Error: FIRESTORE (8.10.1) INTERNAL ASSERTION FAILED: Unexpected state

    at fail (/Users/julestestard/go/src/github.com/piepacker/firestore-react-scripts-error/my-app/node_modules/@firebase/rules-unit-testing/node_modules/@firebase/firestore/src/util/assert.ts:40:9)
    at hardAssert (/Users/julestestard/go/src/github.com/piepacker/firestore-react-scripts-error/my-app/node_modules/@firebase/rules-unit-testing/node_modules/@firebase/firestore/src/util/assert.ts:54:5)
    at fromBytes (/Users/julestestard/go/src/github.com/piepacker/firestore-react-scripts-error/my-app/node_modules/@firebase/rules-unit-testing/node_modules/@firebase/firestore/src/remote/serializer.ts:252:5)
    at fromWatchChange (/Users/julestestard/go/src/github.com/piepacker/firestore-react-scripts-error/my-app/node_modules/@firebase/rules-unit-testing/node_modules/@firebase/firestore/src/remote/serializer.ts:475:25)
```

**Comment by wu-hui** [comment]
Thanks for reporting this issue.

You seem to be using a pretty old version for rules testing though, were you able to reproduce this with more recent versions?

**Comment by jtestard** [comment]
@wu-hui there is a reason for the rules-unit testing version to be this. The more recent version of the package requires that the code being run uses the new firebase v9 SDK. Our application (not this repro example) uses v9 compat settings, and migrating the to v9 SDK has been on our TODO list but is a lot of work.

I rewrote the example using where the firestore actions use the v9 SDK (not what we use on production) and indeed the bug disappears. But we'd like to avoid having to upgrade all of our production code to v9 SDK and still use the emulator, if possible.

**Comment by DellaBitta** [comment]
Hi @jtestard,

Could you check the info in the issue hsubox76 linked and see if it helps you out at all? Thanks!
