### ISSUE TITLE
Firebase 9 Database: set & update crash when onValue is listening

### ISSUE THREAD

**Issue by shija-ntula** [firebase/firebase-js-sdk#6941]
### Firebase 9 Database: set & update crash when onValue is listening

  * Operating System version: Ubuntu 20.04.5 LTS
  * Browser version: Google Chrome Version 107.0.5304.87 (Official Build) (64-bit)
  * Firebase SDK version: 9.15.0
  * Firebase Product: database
  * Vue 3

### The problem is as follows
Im creating a simple chat app with firebase real time database.
My simple app needs to write messages to a chat room and listen to any new message to render in the view.
When the App starts, it automatically send the first message saying that the user is in.
It the starts a listener with onValue, Everything goes fine.
But when sending the next message, the message doesn't reach the database, and in the console I see the following stack

```javascript
runtime-core.esm-bundler.js:220 Uncaught TypeError: newChildren.insert is not a function
    at IndexMap.ts:147:30
    at map (obj.ts:50:21)
    at Proxy.addToIndexes (IndexMap.ts:115:24)
    at Proxy.updateImmediateChild (ChildrenNode.ts:156:38)
    at IndexedFilter.updateChild (IndexedFilter.ts:94:19)
    at viewProcessorApplyUserOverwrite (ViewProcessor.ts:494:51)
    at viewProcessorApplyOperation (ViewProcessor.ts:103:22)
    at viewApplyOperation (View.ts:213:18)
    at syncPointApplyOperation (SyncPoint.ts:107:9)
    at syncTreeApplyOperationHelper_ (SyncTree.ts:730:9)
```

If I remove the onValue listener, all sent messages reach my database. although I cant get the updates by then.

#### Steps to reproduce:

1. Preparing my database in Firebase.js
```javascript
import { initializeApp } from "firebase/app";
import {getDatabase, ref, onValue, push, set, update, get, } from "firebase/database";

const config = {
  XXXXXXXXXX
};

const firebase = initializeApp(config);
const database = getDatabase(firebase);

export { database, ref, onValue, push, set, update, get };
```

2. Importing and using firebase
```javascript
import { database, ref, onValue, push, set, update } from "../Firebase";
import router from "../router";

export default {
  name: "Chat",
  props: ["roomid", "roomname", "nickname"],
  data() {
    return {
      message: "",
      chats: [],
      errors: [],
      offStatus: false,
      chatsRef: ref(database, "chatrooms/" + this.roomid + "/chats"),
    };
  },
  created() {
    this.sendMessage(this.nickname + " amejiunga katika redio.", "join");

    onValue(this.chatsRef, (snapshot) => {
      if (snapshot.exists()) {
        this.chats = [];
        snapshot.forEach((doc) => {
          let item = doc.val();
          item.key = doc.key;
          this.chats.push(item);
        });
      }
    });
  },
  unmounted() {
    this.exitChat();
  },
  methods: {
    onSubmit(evt) {
      evt.preventDefault();

      this.sendMessage(this.message, "newmsg");
      this.message = "";
    },
    sendMessage(message, type = "newmsg") {
      const newPostKey = push(this.chatsRef).key;
      // const updates = {};
      // updates[newPostKey] = {
      //   type: type,
      //   user: this.nickname,
      //   message: message,
      //   sendDate: Date(),
      // };

      set(ref(database, "chatrooms/" + this.roomid + "/chats/" + newPostKey), {
        type: type,
        user: this.nickname,
        message: message,
        sendDate: Date(),
      });

      // update(this.chatsRef, updates);
    },
    exitChat() {
      this.sendMessage(this.nickname + " ametoka katika redio.", "exit");
      this.offStatus = true;
      router.go(-1);
    },
  },
};
```

**Comment by shija-ntula** [comment]
I downgraded to 8.2.3

**Comment by maneesht** [comment]
In `sendMessage`, is `this.roomid` defined? If it's undefined, then we throw that error.

**Comment by shija-ntula** [comment]
> In `sendMessage`, is `this.roomid` defined? If it's undefined, then we throw that error.

It's defined. Its in ```props``` and it comes from another component to which the current component is attached

**Comment by shija-ntula** [comment]
I've resolved the error. And now its working.
The problem occurred because of using a single database reference for both listening and writing data.
```javascript
import { database, ref, onValue, push, set, update } from "../Firebase";
import router from "../router";

export default {
  name: "Chat",
  props: ["roomid", "roomname", "nickname"],
  data() {
    return {
      message: "",
      chats: [],
      errors: [],
      offStatus: false,
      chatsRef: ref(database, "chatrooms/" + this.roomid + "/chats"), // Here assigning the reference
    };
  },
  created() {
    this.sendMessage(this.nickname + " amejiunga katika redio.", "join");

    onValue(this.chatsRef, (snapshot) => {                                  // Here using it to listen
      if (snapshot.exists()) {
        this.chats = [];
        snapshot.forEach((doc) => {
          let item = doc.val();
          item.key = doc.key;
          this.chats.push(item);
        });
      }
    });
  },
  unmounted() {
    this.exitChat();
  },
  methods: {
    onSubmit(evt) {
      evt.preventDefault();

      this.sendMessage(this.message, "newmsg");
      this.message = "";
    },
    sendMessage(message, type = "newmsg") {
      const newPostKey = push(this.chatsRef).key;                     // Here using it to push
      // const updates = {};
      // updates[newPostKey] = {
      //   type: type,
      //   user: this.nickname,
      //   message: message,
      //   sendDate: Date(),
      // };

      set(ref(database, "chatrooms/" + this.roomid + "/chats/" + newPostKey), {
        type: type,
        user: this.nickname,
        message: message,
        sendDate: Date(),
      });

      // update(this.chatsRef, updates);
    },
    exitChat() {
      this.sendMessage(this.nickname + " ametoka katika redio.", "exit");
      this.offStatus = true;
      router.go(-1);
    },
  },
};
```
I'm not sure why this should be a problem with Firebase internals.
**I think this is a bug**

**Comment by maneesht** [comment]
Interesting. The only way I was able to reproduce this was to set `this.roomid` to undefined, but let me try passing in the values as props.

**Comment by shija-ntula** [comment]
> Interesting. The only way I was able to reproduce this was to set `this.roomid` to undefined, but let me try passing in the values as props.

Since the undefined ```this.roomId``` is also part of reference (```ref(database, "chatrooms/" + this.roomid + "/chats")```) I guess that's an issue with db reference

**Comment by maneesht** [comment]
I was able to reproduce the issue with [create-vue](https://github.com/vuejs/create-vue), but downgrading to 8.2.3 didn't seem to work for me.

And after investigating some more today, it seems like the issue has something to do with the interaction between vue's proxying of RTDB and that object interacting with the SDK's, as when I created an object outside of the vue context and used that in vue, everything worked fine.

**Comment by maneesht** [comment]
Are you using the same CLI tool? And the latest version of it?

**Comment by shija-ntula** [comment]
I created my vue project with [create-vue](https://github.com/vuejs/create-vue) and then installed firebase with ```npm i firebase```

**Comment by shija-ntula** [comment]
> but downgrading to 8.2.3 didn't seem to work for me.

The same to me

**Comment by Pxeba** [comment]
This problem seems to be related to the Vue or Pinia/Vuex state. I managed to solve the problem by keeping the reference in an external variable that receives events and updates data by taking it out of state and putting it outside my defineStore

```
@store
state: () => ({
   messagesRef : {}
   ...
   messagesRef.on('child_added', (snapshot: any) => {} // receiving
   ...
   messagesRef.push(payload.message); // pushing error
})

```

instead: 
```

let messagesRef = {} as any;
export const firebaseStore = defineStore('x', {
   ... do the same...
}
```

**Comment by darrelfrancis** [comment]
This is a persistent bug even when you use VueFire.

You can `set` or `update` a database location, and _then_ use $databaseBind to bind to it, no problem.

But if you `set` or `update` a database location that is already $databaseBind'ed, you will get these hard-to-understand errors, e.g.

VM6601 chunk-3G7ZM6PE.js:4031 Uncaught (in promise) TypeError: newChildren.remove is not a function
    at VM6601 chunk-3G7ZM6PE.js:4031:37
    at map (VM6602 chunk-R5DULB7A.js:608:21)
    at Proxy.addToIndexes (VM6601 chunk-3G7ZM6PE.js:4008:24)
    at Proxy.updateImmediateChild (VM6601 chunk-3G7ZM6PE.js:4128:38)
    at Proxy.updateChild (VM6601 chunk-3G7ZM6PE.js:4567:19)
    at viewProcessorApplyUserOverwrite (VM6601 chunk-3G7ZM6PE.js:6508:51)
    at viewProcessorApplyOperation (VM6601 chunk-3G7ZM6PE.js:6356:23)
    at viewApplyOperation (VM6601 chunk-3G7ZM6PE.js:6725:18)
    at syncPointApplyOperation (VM6601 chunk-3G7ZM6PE.js:6775:30)
    at syncTreeApplyOperationHelper_ (VM6601 chunk-3G7ZM6PE.js:7128:30)

**Comment by suhail23599** [comment]
@maneesht this is still happening even if we use `toRaw` method

**Comment by suhail23599** [comment]
this is the log i put in node_module. Here i am getting newChildren as empty. This happens when i use listener like **onChildAdded.**
I have used different DB reference variable for this listener.
Firebase version: **10.7.2**
Product: **Realtime database**
<img width="1004" alt="Screenshot 2024-04-05 at 4 01 26 PM" src="https://github.com/firebase/firebase-js-sdk/assets/63309817/ad5d17ac-a6e7-44bd-84bf-86c097392e28">

**Comment by suhail23599** [comment]
we had a workaround to fix this issue.
In our application, we had multiple DB listeners which used same firebase DB reference that was causing the issue.
Hence, we created different DB references for each listeners like onChildChanged, onchildAdded, onValue etc.
Eg:
`
this.firebaseChatListListener = db // defined in store (pinia or vuex)
this.firebaseChatRoomListener = db // deined in store (pinia or vuex)
onChildAdded(ref(this.firebaseChatListListener, ${path}), callback)
onValue(ref(this.firebaseChatListListener, ${path}), callback)
`

**Comment by darrelfrancis** [comment]
Solution

I have solved this problem by writing a small helper function. I replace all calls to firebase `set`(), with calls to my function `setClean`()

~~~
import {set,ref} from "firebase/database";

export function setClean(firebaseRef, valueMaybeUndefined) {
  //          _                       _   _  _
  //  /|     |_ o      _|_ |_   _    |_) |_ |_
  //   | o   |  | ><    |_ | | (/_   | \ |_ |
  // Because it may be a Vue Proxy, which causes an error if you are also listening at that firebase location, we reconstitute the reference from the path.
  //

  const targetPath = firebaseRef._path.pieces_.join("/");
  const targetRef = ref(db, targetPath);

  // _       _                                       _
  //  )     |_ o      _|_ |_   _    \  / /\  |  | | |_
  // /_ o   |  | ><    |_ | | (/_    \/ /--\ |_ |_| |_
  // Because we are not allowed to write undefined to Firebase, we convert it to null.

  const valueNeverUndefined =
    valueMaybeUndefined === undefined ? null : valueMaybeUndefined;

  console.log("setClean", targetPath, valueNeverUndefined);
  return set(targetRef, valueNeverUndefined);
}
~~~

So if my code initially said:
~~~
import {set} from "firebase/database";
...
set(x,y)
~~~

I now say
~~~
import {setClean} from     .... my helper function as shown above ...

setClean(x,y)
~~~

**Comment by ateryaev** [comment]
Same issue for me. Can't set/remove while having onValue working in my JS react webapp.
Workaround with two "db" doesn't help - or what exactly is the way to initialize two different db objects?
 "firebase": "^10.12.2"

**Comment by igorjacauna** [comment]
For me, worked using `toRaw` from Vue when I need to call `set`, `update`, `onValue`...

```ts
set(toRaw(databaseRef)), { ... });
update(toRaw(databaseRef)), { ... });
onValue(toRaw(databaseRef)), { ... });
```

Even with same reference, no need create new reference to call multiple times update or set.

I'm using firebase@11.1.0

**Comment by onorok** [comment]
I just wanted to throw another comment into the mix here. I am seeing this issue sporadically in my project utilizing Vue 3.5.13 and Firebase 11.8.1.

Sometimes I get the error, and sometimes I don't, which makes it really hard to debug what the issue is. None of the above fixes have worked for me.
