### ISSUE TITLE
npm install firebase@5.7.3 fail

### ISSUE THREAD

**Issue by Zou-Wang** [firebase/firebase-js-sdk#7312]
Node Js：14.20.0
npm：9.6.7

I am running `cnpm install` based on this environment

The version of firebase in package. json is 5.7.3, and the following error will appear when downloading to firebase.

`> node-pre-gyp install --fallback-to-build --library=static_library
'node-pre-gyp' 不是内部或外部命令，也不是可运行的程序
/ [91/92] Installing long@~3
[npminstall:runscript:error] firebase@5.11.1 › @firebase/firestore@1.2.2 › grpc@1.20.0 run install node-pre-gyp install --fallback-to-build --library=static_library error: Error: Command failed with exit code 1: node-pre-gyp install --fallback-to-build --library=static_library 
    at makeError (D:\nvm\v14.20.0\node_modules\cnpm\node_modules\execa\lib\error.js:60:11)
    at handlePromise (D:\nvm\v14.20.0\node_modules\cnpm\node_modules\execa\index.js:118:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.exports.runScript (D:\nvm\v14.20.0\node_modules\cnpm\node_modules\npminstall\lib\utils.js:262:12)
    at async runLifecycleScripts (D:\nvm\v14.20.0\node_modules\cnpm\node_modules\npminstall\lib\lifecycle_scripts.js:64:7)
    at async _install (D:\nvm\v14.20.0\node_modules\cnpm\node_modules\npminstall\lib\install_package.js:321:5)
    at async install (D:\nvm\v14.20.0\node_modules\cnpm\node_modules\npminstall\lib\install_package.js:23:12)
    at async mapper (D:\nvm\v14.20.0\node_modules\cnpm\node_modules\npminstall\lib\install_package.js:270:9) {
  shortMessage: 'Command failed with exit code 1: node-pre-gyp install --fallback-to-build --library=static_library',
  command: 'node-pre-gyp install --fallback-to-build --library=static_library',
  escapedCommand: 'node-pre-gyp install --fallback-to-build "--library=static_library"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
× Install fail! Error: run install error, please remove node_modules before retry!
Command failed with exit code 1: node-pre-gyp install --fallback-to-build --library=static_library
Error: Command failed with exit code 1: node-pre-gyp install --fallback-to-build --library=static_library
    at makeError (D:\nvm\v14.20.0\node_modules\cnpm\node_modules\execa\lib\error.js:60:11)
    at handlePromise (D:\nvm\v14.20.0\node_modules\cnpm\node_modules\execa\index.js:118:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.exports.runScript (D:\nvm\v14.20.0\node_modules\cnpm\node_modules\npminstall\lib\utils.js:262:12)
    at async runLifecycleScripts (D:\nvm\v14.20.0\node_modules\cnpm\node_modules\npminstall\lib\lifecycle_scripts.js:64:7)
    at async _install (D:\nvm\v14.20.0\node_modules\cnpm\node_modules\npminstall\lib\install_package.js:321:5)
    at async install (D:\nvm\v14.20.0\node_modules\cnpm\node_modules\npminstall\lib\install_package.js:23:12)
    at async mapper (D:\nvm\v14.20.0\node_modules\cnpm\node_modules\npminstall\lib\install_package.js:270:9)
npminstall version: 7.8.0
npminstall argv: D:\nvm\nodejs\node.exe D:\nvm\v14.20.0\node_modules\cnpm\node_modules\npminstall\bin\install.js --fix-bug-versions --china --userconfig=C:\Users\5109u12362\.cnpmrc --disturl=https://cdn.npmmirror.com/binaries/node --registry=https://registry.npmmirror.com      
`

**Comment by Zou-Wang** [comment]
![image](https://github.com/firebase/firebase-js-sdk/assets/48306074/ba7fe352-a81c-412d-a0e3-d5dedcdae7dc)

This is my cnpm version

**Comment by dwyfrequency** [comment]
Can you send the whole package.json or a screenshot? That version of firebase is well behind what we officially support. We highly recommend updating to the latest: 9.22.0. You can also use the compat feature of the SDK if you are still using namespaced code.
