### ISSUE TITLE
Unable to Initialize Firestore with Version 9.23.0

### ISSUE THREAD

**Issue by ThiloReintjes** [firebase/firebase-js-sdk#7503]
### Operating System

macOS 13.0.1

### Browser Version

Firefox/115.0.3

### Firebase SDK Version

9.23.0

### Firebase SDK Product:

Auth, Firestore

### Describe your project's tooling

TypeScript, Svelte-Kit with Vite

### Describe the problem

Attempt to initialise the Firestore application and get the corresponding Firestore object:

firebase.ts:
```
import {getApps, initializeApp} from "firebase/app";
import {getFirestore} from "firebase/firestore/lite";
import {getAuth} from "firebase/auth";


const firebaseConfig = {
    apiKey: "...",
    authDomain: "...",
    projectId: "...",
    storageBucket: "...",
    messagingSenderId: "...",
    appId: "...",
    measurementId: "...",
};

// Initialize Firebase

const apps = getApps();
export let app: any
if (!apps.length) {
    app = initializeApp(firebaseConfig);
    console.log("Firebase app initialized");
} else {
    app = apps[0];
    console.log("Firebase app already initialized", apps.length);
}

export let db = getFirestore(app);
export let auth = getAuth(app);
```

We were using firebase `9.22.1` until the 11.07. Then we upgraded to firebase `10.0.0`.
We host our svelte-kit on firebase hosting, using the experimental features of `firebase-frameworks`. 
Unfortunately, `firebase-frameworks` has in its `peerDependencies` `"firebase": "^9.9.0"`.
So we have downgraded our firebase version to `9.23.0`. 

When we run the project, as well as when we try to deploy the project, we get the error:
```
|- Error: Service firestore is not available
    at Provider.getImmediate (file:///.../node_modules/@firebase/component/dist/esm/index.esm2017.js:147:23)
    at Proxy.getFirestore (file:///.../node_modules/@firebase/firestore/dist/index.node.mjs:27961:47)
    at eval (/Users/.../src/routes/firebase.ts:30:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async instantiateModule (file:///.../node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54405:9)
```

The same thing happens when downgrading to `9.22.1`.
We have been hosting on firebase hosing for about 2 months and have been able to deploy our website with ease, but since the 11.07 we are not able to run the project unless we upgrade to `10.0.0`, and are not able to use `firebase-frameworks` unless we use `^9.23.0`.

### Steps and code to reproduce issue

1. Setup a new Svelte-kit project with "firebase": "9.23.0" or "firebase": "9.22.1".
2. Initialize the Firebase and Firestore in your application using the code provided in the initial description.
3. Run your project. You should see an error indicating that the Firestore service is unavailable.
4. Attempt to deploy your project with `firebase deploy` and with `firebase experiments:enable webframeworks` enabled.
5. Upgrade Firebase to version 10.0.0, and repeat steps 3 and 4. The project should run, but `firebase deploy` will run into dependency issues.

**Comment by ThiloReintjes** [comment]
Thanks for your comment!
This [workaround ](https://github.com/firebase/firebase-tools/issues/6109#issuecomment-1644283569) and adding `vite` as a dependency (normally `vite` is just in `devDependencies`) fixed the issue
