### ISSUE TITLE
Unable to install the firebase npm module on Linux

### ISSUE THREAD

**Issue by VladimirDev93** [firebase/firebase-js-sdk#779]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 18.04 LTS
  * Firebase SDK version: 5.0.0-2
  * Firebase Product: Database

### [REQUIRED] Describe the problem
I cannot install the npm module on Linux.
#### Steps to reproduce:
```bash
npm i firebase
```
Then, this happens:
```bash
> grpc@1.10.1 install /home/wiseman/Desktop/zamphyr-manifesto/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.10.1/node-v64-linux-x64-glibc.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.10.1 and node@10.0.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:149:21)
gyp ERR! System Linux 4.15.0-20-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/wiseman/Desktop/zamphyr-manifesto/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/wiseman/Desktop/zamphyr-manifesto/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc"
gyp ERR! cwd /home/wiseman/Desktop/zamphyr-manifesto/node_modules/grpc
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/wiseman/Desktop/zamphyr-manifesto/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/wiseman/Desktop/zamphyr-manifesto/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/wiseman/Desktop/zamphyr-manifesto/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:947:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
node-pre-gyp ERR! System Linux 4.15.0-20-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/wiseman/Desktop/zamphyr-manifesto/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/wiseman/Desktop/zamphyr-manifesto/node_modules/grpc
node-pre-gyp ERR! node -v v10.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.7.0
node-pre-gyp ERR! not ok
```

**Comment by VladimirDev93** [comment]
@shubham81407 10

**Comment by apaatsio** [comment]
@VladimirDev93 It says `Error: not found: make`. Do you have `make` installed? On Ubuntu `make` is found in the `build-essential` package.

**Comment by VladimirDev93** [comment]
@apaatsio `make` comes pre-installed with Ubuntu.
It says that it can't find `Pre-built binaries` and that is not able to download the `node-v64-linux-x64-glibc.tar.gz` tarball file.

**Comment by VladimirDev93** [comment]
I managed to get it working. I received some external help.
`sudo apt install build-essential` and then `npm i firebase` and it will install successfully.
