### ISSUE TITLE
runTransaction errors are not catchable

### ISSUE THREAD

**Issue by marcusx2** [firebase/firebase-js-sdk#7919]
### Operating System

macOS

### Browser Version

Safari 16.5.2

### Firebase SDK Version

10.7.1

### Firebase SDK Product:

Database

### Describe your project's tooling

index.html with source tag. Just javascript.

### Describe the problem

runTransaction errors can not be caught. 

### Steps and code to reproduce issue

Start with the database empty.

```
var db = getDatabase();
connectDatabaseEmulator(db, '127.0.0.1', 9000);
await update(ref(db, "users/testUser/starCount"), { starCount: increment(1) });
try {
    await runTransaction(ref(db, "users/testUser"), post => {
        console.log(post);
        if (post) {
            var starCount = post["starCount"];
            starCount++;
            post["starCount"] = starCount;
            return post;
        } else {
           return null;
        }
    });
} catch (e) {//it never reaches catch
    console.error("transaction error");
    console.error(e);
}
```

The following error shows up on the console

`Error: transaction failed: Data returned contains NaN in property 'users.testUser.starCount'`

However, the error can never be caught.

**Comment by jbalidiong** [comment]
Apologies for the long silence. I was able to reproduce this issue using the latest SDK version. I'll mark this as reproducible and raise it to our engineering so they can take a look.

**Comment by bhavya091213** [comment]
I looked into this and traced the root cause. I'd like to contribute a fix, and wanted to lay out the proposed change here first per the contributing guide.

## Root cause

There are two independent paths where an error escapes the promise `runTransaction()` returns.

**1. The rerun path — this is the one reported here, and it's the more serious of the two.**

`runTransaction()` wires errors to a `Deferred` via `promiseComplete` ([`Transaction.ts#L134-L143`](https://github.com/firebase/firebase-js-sdk/blob/706b62a404cdd786bc1e1f22ad486bab417470f4/packages/database/src/api/Transaction.ts#L134-L143)). But when a transaction is *rerun*, the update function and `validateFirebaseData()` are called bare inside `repoRerunTransactionQueue` ([`Repo.ts#L1294-L1302`](https://github.com/firebase/firebase-js-sdk/blob/706b62a404cdd786bc1e1f22ad486bab417470f4/packages/database/src/core/Repo.ts#L1294-L1302)), and that function runs from server data-update callbacks (`repoRerunTransactions` is invoked at `Repo.ts` lines 407, 591, 642, 657, 699 and 1197).

So the throw unwinds through the WebSocket message handler instead of the promise:

```
Uncaught Error: transaction failed: Data returned contains NaN in property '<path>.counter'
    at repoRerunTransactionQueue (src/core/Repo.ts:1297:31)
    at repoRerunTransactions (src/core/Repo.ts:1223:3)
    at PersistentConnection.onDataMessage_ (src/core/PersistentConnection.ts:650:9)
    at Connection.onDataMessage_ (src/realtime/Connection.ts:321:10)
    at WebSocketConnection.onMessage (src/realtime/Connection.ts:210:16)
    ...
```

The `Deferred` is never settled, so the `await` never returns **and** never rejects — the promise stays pending forever while the error shows up as an uncaught exception. That's why @marcusx2's `try/catch` never fired.

This also explains why the original repro needs to start with an empty database: the first run sees a not-yet-populated cache and returns valid data, so the transaction is queued; the `NaN` is only produced on the rerun once the server value arrives.

**2. The initial-run path.**

The first run happens synchronously inside `repoStartTransaction`, so an error there is *thrown out of* `runTransaction()` rather than rejecting. `try { await runTransaction(...) } catch` does catch it, but `runTransaction(...).catch(fn)` does not — the `.catch` is never reached, since the call throws before returning a promise. For a function documented to return a `Promise` that seemed worth fixing in the same pass, though I'm happy to split it out if you'd prefer.

There's also a related listener leak on this path: if the update function or validation throws before the transaction is pushed onto the queue, the `onValue` listener registered at [`Transaction.ts#L132`](https://github.com/firebase/firebase-js-sdk/blob/706b62a404cdd786bc1e1f22ad486bab417470f4/packages/database/src/api/Transaction.ts#L132) is never unwatched.

## Proposed change

- In `repoRerunTransactionQueue`, wrap the update call and `validateFirebaseData` so a throw becomes a normal transaction abort. It reuses the existing abort machinery (including `syncTreeAckUserWrite(..., true)` to revert the pending local write), so it behaves consistently with the existing `maxretry` / `nodata` aborts, and reports the original error — stack preserved — through `onComplete`.
- In `runTransaction`, catch a synchronous failure from `repoStartTransaction` and reject the deferred instead, so the error is always delivered through the returned promise.
- In `repoStartTransaction`, call `unwatcher()` before an initial-run error propagates, to fix the leak above.

Deliberately left alone: the argument-validation throws at the top of `runTransaction` (`validateWritablePath`, and the `.length`/`.keys` read-only check). Those are programmer errors rather than transaction failures, and throwing synchronously matches the rest of the SDK. Let me know if you'd rather those were normalized too.

## Tests

Four regression tests added to `packages/database/test/exp/integration.test.ts`, each failing before the change and passing after:

- a rerun that produces `NaN` rejects the promise (the exact scenario in this issue)
- a rerun where the update function throws rejects the promise
- an initial run where the update function throws rejects the promise
- an initial-run failure is observable via `.catch()` rather than throwing synchronously

Full `@firebase/database` node suite against the RTDB emulator goes from 266 passing to 270 passing, 0 failing. `tsc --noEmit`, eslint and prettier are all clean. Changeset included.

One observation while working on this: `integration.test.ts` was the only test file in the package that touches `runTransaction` at all, which is probably why this went unnoticed for so long.

Happy to open the PR whenever it's useful — just wanted to check the approach first, particularly on whether you want the initial-run behaviour change (sync throw → rejection) bundled in or kept separate, since that one is technically a semantic change for anyone relying on the current throw.

**Comment by bhavya091213** [comment]
Opened #10324 with the change described above.

It includes both fixes — the rerun path (this issue) and the initial-run synchronous throw. I flagged the second one as an open question on the PR, since it is a semantic change for anyone relying on the current throw, and I am happy to split it out if you would prefer to land only the rerun fix first.
