### ISSUE TITLE
DOMException: Failed to execute 'put' on 'IDBObjectStore': The transaction is not active.

### ISSUE THREAD

**Issue by pratt3351** [firebase/firebase-js-sdk#7985]
### Operating System

mac OS

### Browser Version

all of browser

### Firebase SDK Version

10.7.2

### Firebase SDK Product:

Analytics

### Describe your project's tooling

with react-native + react-native web.

### Describe the problem

intialize firebase sdk and call any other firebase module just always throw this errors

DOMException: Failed to execute 'put' on 'IDBObjectStore': The transaction is not active.
    at Proxy.<anonymous> (https://localhost/scripts/script.340834.js:381329:26)
    at _callee6$ (https://localhost/scripts/script.340834.js:389062:24)
    at tryCatch (https://localhost/scripts/script.340834.js:388438:1357)
    at Generator.<anonymous> (https://localhost/scripts/script.340834.js:388438:4172)
    at Generator.next (https://localhost/scripts/script.340834.js:388438:2208)
    at asyncGeneratorStep (https://localhost/scripts/script.340834.js:388442:103)
    at _next (https://localhost/scripts/script.340834.js:388443:194)
    at tryCallOne (https://localhost/scripts/script.340834.js:133892:12)
    at https://localhost/scripts/script.340834.js:133973:15
    at run (https://localhost/scripts/script.340834.js:238290:9)

what's wrong with my project..?
i'm using react-native 0.72.7, and react-nativeweb 0.19.9 version

### Steps and code to reproduce issue

i have this babel presets. 
```
{
      presets: [
        [
          '@babel/preset-env',
          {
            loose: true,
            corejs: { version: '3.22', proposals: true },
            useBuiltIns: 'entry',
            targets: { ie: '11' },
          },
        ],
        ['@babel/preset-react', { runtime: 'automatic' }],
        '@babel/preset-typescript',
      ],
      plugins: defaultPlugins,
    }
```

**Comment by DellaBitta** [comment]
This error is generated by the browser's implementation of the IndexedDB API. Can you provide us with a minimal reproducible test case that we can try to debug on our side? Thanks!

**Comment by pratt3351** [comment]
> This error is generated by the browser's implementation of the IndexedDB API. Can you provide us with a minimal reproducible test case that we can try to debug on our side? Thanks!

well, i dont know exactly test it.
it is occurs when initiate firebase sdk and using some kind of functions that produce by firebase remote config functions
