### ISSUE TITLE
Error *after* Firebase Function performing a sendSignInLinkToEmail

### ISSUE THREAD

**Issue by Vinnythetrue** [firebase/firebase-js-sdk#8058]
### Operating System

Ubuntu 22

### Browser Version

Chrome 118

### Firebase SDK Version

9.16.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

Firebase project, front is a VueJS Nuxt app, calling some online firebase functions.

### Describe the problem

I'm trying to create an online firebase function that can be used to sendSignInLinkToEmail()
After some tries, I apparently managed to do something, as my function no longer returns an error.

My function code :

```
export const sendConnectionEmail = functions.https.onCall(async (data) => {
  const email = expectArgument(data, "email") as string;
  const url = expectArgument(data, "url") as string;
  const firebaseUser = await admin.auth().getUserByEmail(email);
  const user = await getUser(firebaseUser.uid);
  if (user) {
    const actionCodeSettings = {
      url: url,
      // This must be true.
      handleCodeInApp: true
    };

    let app = initializeFirebaseApp( { apiKey: "%%%%%%%%%%%%" } );
    sendSignInLinkToEmail(getAuth(app), email, actionCodeSettings);
  }
});
```

But I never get any email from it... Looking in the google cloud logs, I can find these :
```
2024-03-08 10:25:45.194 sendConnectionEmail Function execution started
2024-03-08 10:25:45.210 sendConnectionEmail Function execution took 16 ms, finished with status code: 204
2024-03-08 10:25:45.248 sendConnectionEmail Function execution started
2024-03-08 10:25:45.335 sendConnectionEmail Callable request verification passed
2024-03-08 10:25:49.449 sendConnectionEmail Function execution took 4201 ms, finished with status code: 200
2024-03-08 10:25:49.453 sendConnectionEmail [2024-03-08T09:25:49.453Z]  @firebase/auth: Auth (10.8.1): INTERNAL ASSERTION FAILED: Could not find fetch implementation, make sure you call FetchProvider.initialize() with an appropriate polyfill
2024-03-08 10:25:49.454 sendConnectionEmail Unhandled rejection
2024-03-08 10:25:49.455 sendConnectionEmail FirebaseError: Firebase: Error (auth/network-request-failed).     at createErrorInternal (/workspace/node_modules/@firebase/auth/dist/node/totp-e9be401a.js:517:55)     at _fail (/workspace/node_modules/@firebase/auth/dist/node/totp-e9be401a.js:488:31)
2024-03-08 10:25:49.455 sendConnectionEmail     at /workspace/node_modules/@firebase/auth/dist/node/totp-e9be401a.js:998:21
2024-03-08 10:25:49.455 sendConnectionEmail     at step (/workspace/node_modules/tslib/tslib.js:195:27)
2024-03-08 10:25:49.455 sendConnectionEmail     at Object.throw (/workspace/node_modules/tslib/tslib.js:176:57)
2024-03-08 10:25:49.455 sendConnectionEmail     at rejected (/workspace/node_modules/tslib/tslib.js:167:69)
2024-03-08 10:25:49.455 sendConnectionEmail     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2024-03-08 10:25:50.397 sendConnectionEmail Error: Process exited with code 16     at process.<anonymous> (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:92:22)     at process.emit (events.js:400:28)     at process.emit (domain.js:475:12)     at process.exit (internal/process/per_thread.js:179:15)     at sendCrashResponse (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/logger.js:44:9)     at process.<anonymous> (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:88:44)     at process.emit (events.js:400:28)     at process.emit (domain.js:475:12)     at processPromiseRejections (internal/process/promises.js:245:33)     at processTicksAndRejections (internal/process/task_queues.js:96:32)

```

It seems like my function ends well, but afterwards, maybe when the mail would actually been sent, there is an error in initializing stuff... What can I do about this ? A cannot seem to find any relevant documentation about this situation...

### Steps and code to reproduce issue

Create A firebase function that does the call :
```
export const sendConnectionEmail = functions.https.onCall(async (data) => {
  const email = expectArgument(data, "email") as string;
  const url = expectArgument(data, "url") as string;
  const firebaseUser = await admin.auth().getUserByEmail(email);
  const user = await getUser(firebaseUser.uid);
  if (user) {
    const actionCodeSettings = {
      url: url,
      // This must be true.
      handleCodeInApp: true
    };

    let app = initializeFirebaseApp( { apiKey: "%%%%%%%%%%%%%" } );
    sendSignInLinkToEmail(getAuth(app), email, actionCodeSettings);
  }
});

```

Deploy the function.
Call it with email & url parameters (email should match an existing user)

**Comment by renkelvin** [comment]
Hi @Vinnythetrue , could you elaborate your use case? Why do you want to call `sendSignInLinkToEmail` in blocking functions?

**Comment by Vinnythetrue** [comment]
Hello @renkelvin !

What exactly do you mean by blocking functions ? Are you refering the fact that I call this method inside a synchronous httpcallback ? I tried to implement the thing as I read it in the documentations. Maybe I got it wrong ?

My use case is quite simple : I want to call a firebase function with a given email address amongst the payload, and expect an email on this address containing a connection link. Nothing fancy here...

Thanks for your time :)

**Comment by renkelvin** [comment]
I was referring to https://firebase.google.com/docs/auth/extend-with-blocking-functions?gen=2nd, which seems not your case.

Using the auth web sdk in Firebase function is not a typical use case since it's designed for client side interactions. To use Firebase auth in Firebase functions, you can use the admin sdks. https://firebase.google.com/docs/auth/admin
