### ISSUE TITLE
` isHostLanguageValid()` in auth's recaptcha loader incorrectly determines long language codes to be invalid

### ISSUE THREAD

**Issue by sxxov** [firebase/firebase-js-sdk#8357]
### Operating System

Windows 11

### Browser Version

Chrome/126.0.6478.127

### Firebase SDK Version

10.12.3

### Firebase SDK Product:

Auth

### Describe your project's tooling

NextJS 15 RC
React Compiler

### Describe the problem

My browser's language is `en-GB-oxendict` (got by doing `navigator.languages[0]`).

When trying to use `auth.useDeviceLanguage()`, which sets the above value to `auth.languageCode`, the recaptcha loader will fail an assertion as described [here](https://github.com/firebase/firebase-js-sdk/blob/52f8deb1dc07cd6acc323f36d8be158e927d17c6/packages/auth/src/platform_browser/recaptcha/recaptcha_loader.ts#L59), & as implemented [here](https://github.com/firebase/firebase-js-sdk/blob/52f8deb1dc07cd6acc323f36d8be158e927d17c6/packages/auth/src/platform_browser/recaptcha/recaptcha_loader.ts#L127), throwing a `FirebaseError: Firebase: Error (auth/argument-error)`.

A bit perculiar that language codes are expected to be below 6 characters. Either that, or `auth.useDeviceLanguage()` should handle it.

### Steps and code to reproduce issue

```ts
import { getAuth } from 'firebase/auth';
import { app } from './app';

export const auth = getAuth(app);
// either, on a environment with a long language string:
// auth.useDeviceLanguage();
// or, set it directly here:
auth.languageCode = 'en-GB-oxendict';

const el = document.createElement('div');
document.body.appendChild(el);

const verifier = new RecaptchaVerifier(auth, el, {
	size: 'invisible',
});
void verifier.render().then(console.log);
// uncaught promise rejection:
// FirebaseError: Firebase: Error (auth/argument-error).
//    at createErrorInternal (index-54738136.js:455:37)
//    at _assert (index-54738136.js:461:11)
//    at ReCaptchaLoaderImpl.load (index-54738136.js:8134:5)
//    at RecaptchaVerifier.init (index-54738136.js:8382:50)
//    at async RecaptchaVerifier.makeRenderPromise (index-54738136.js:8367:5)
```

**Comment by dlarocque** [comment]
Thanks for reporting this issue, and for providing a great description!

**Comment by jbalidiong** [comment]
Apologies for the long silence. I tried replicating the issue using the latest SDK version and I was able to replicate the behavior. Looking at the code, it is possible that long character length of the language code is causing this issue. Will raise this to our engineering team and will mark this as reproducible.

**Comment by ATKasem** [comment]
I'd like to contribute a fix for this.

Root cause is in `isHostLanguageValid` (`packages/auth/src/platform_browser/recaptcha/recaptcha_loader.ts`): it rejects any host-language code longer than 6 characters (`hl.length <= 6`), so a valid BCP-47 tag like `en-GB-oxendict` (what `useDeviceLanguage()` sets from `navigator.language`) fails the assertion in `load()` and `RecaptchaVerifier.render()` rejects with `auth/argument-error`. The character-class check already keeps the value URL-safe, so the length bound just needs to be permissive enough for real language tags.

Fix + a regression test on the way.
