### ISSUE TITLE
Compatibility error with Node 22.7

### ISSUE THREAD

**Issue by lucasmengarda** [firebase/firebase-js-sdk#8455]
### Operating System

Linux

### Environment (if applicable)

Node 22.7

### Firebase SDK Version

9.23.0

### Firebase SDK Product(s)

Firestore

### Project Tooling

React app with Firebase

### Detailed Problem Description

When running a Node.js application that interacts with Firestore on the Google Cloud Platform (GCP), specifically in a Cloud Run environment, I encounter a RangeError [ERR_BUFFER_OUT_OF_BOUNDS]. This error occurs when attempting to retrieve a document from Firestore using the following code:

This issue began happening after updating to Node.js 22.7. I have since downgraded to a previous version, which resolved the issue, but I wanted to report this problem.

### Steps and code to reproduce issue

const docRef = database.collection('users').doc(uid);
const doc = await docRef.get();

**Comment by dlarocque** [comment]
Looking at the Node 22.7 release notes, I see quite a few changes have been made to Buffer in [#54311](https://github.com/nodejs/node/pull/54311), [#54324](https://github.com/nodejs/node/pull/54324), and [#54087](https://github.com/nodejs/node/pull/54087). This might be a Node bug introduced by these changes.

**Comment by dlarocque** [comment]
Here's a full stack trace:
```
[2024-08-23T18:57:08.150Z]  @firebase/firestore: Firestore (10.13.0): INTERNAL UNHANDLED ERROR:  RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: "length" is outside of buffer bounds
    at proto.utf8Write (node:internal/buffer:1066:13)
    at Op.writeStringBuffer [as fn] (/Users/dlarocque/workspace/repro/nodebug/node_modules/protobufjs/src/writer_buffer.js:61:13)
    at BufferWriter.finish (/Users/dlarocque/workspace/repro/nodebug/node_modules/protobufjs/src/writer.js:453:14)
    at /Users/dlarocque/workspace/repro/nodebug/node_modules/@grpc/proto-loader/build/src/index.js:177:109
    at Array.map (<anonymous>)
    at createPackageDefinition (/Users/dlarocque/workspace/repro/nodebug/node_modules/@grpc/proto-loader/build/src/index.js:177:39)
    at Module.fromJSON (/Users/dlarocque/workspace/repro/nodebug/node_modules/@grpc/proto-loader/build/src/index.js:230:12)
    at loadProtos (file:///Users/dlarocque/workspace/repro/nodebug/node_modules/@firebase/firestore/dist/index.node.mjs:22129:43)
    at newConnection (file:///Users/dlarocque/workspace/repro/nodebug/node_modules/@firebase/firestore/dist/index.node.mjs:22151:20)
    at OnlineComponentProvider.createDatastore (file:///Users/dlarocque/workspace/repro/nodebug/node_modules/@firebase/firestore/dist/index.node.mjs:26266:28)
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: "length" is outside of buffer bounds
    at proto.utf8Write (node:internal/buffer:1066:13)
    at Op.writeStringBuffer [as fn] (/Users/dlarocque/workspace/repro/nodebug/node_modules/protobufjs/src/writer_buffer.js:61:13)
    at BufferWriter.finish (/Users/dlarocque/workspace/repro/nodebug/node_modules/protobufjs/src/writer.js:453:14)
    at /Users/dlarocque/workspace/repro/nodebug/node_modules/@grpc/proto-loader/build/src/index.js:177:109
    at Array.map (<anonymous>)
    at createPackageDefinition (/Users/dlarocque/workspace/repro/nodebug/node_modules/@grpc/proto-loader/build/src/index.js:177:39)
    at Module.fromJSON (/Users/dlarocque/workspace/repro/nodebug/node_modules/@grpc/proto-loader/build/src/index.js:230:12)
    at loadProtos (file:///Users/dlarocque/workspace/repro/nodebug/node_modules/@firebase/firestore/dist/index.node.mjs:22129:43)
    at newConnection (file:///Users/dlarocque/workspace/repro/nodebug/node_modules/@firebase/firestore/dist/index.node.mjs:22151:20)
    at OnlineComponentProvider.createDatastore (file:///Users/dlarocque/workspace/repro/nodebug/node_modules/@firebase/firestore/dist/index.node.mjs:26266:28) {
  code: 'ERR_BUFFER_OUT_OF_BOUNDS'
}

Node.js v22.7.0
```

**Comment by dlarocque** [comment]
Looks like this new line added to node in 22.7 is what's throwing the error https://github.com/nodejs/node/pull/54311/files#diff-ec53d27b3c64c43cc2d4773dd88046ebb149e3d89e31d838df3252c8d5de89adR1066

**Comment by blackazaru** [comment]
This is happening and has already happened several times on:

Firebase CLI: 13.15.4
firebase-admin: 11.10.1
Node.js: 20.10"

**Comment by dlarocque** [comment]
> I got caught off guard. I was using FROM node:latest in my Docker for the dev environment, and suddenly the whole system started failing with the error RangeError [ERR_BUFFER_OUT_OF_BOUNDS].
> 
> Spent a few hours figuring out the issue, but I switched the Dockerfile to FROM node:lts and everything's back to normal.
> 
> Probably is a Node bug.

Do you happen to be using protobufjs or grpc?

**Comment by dlarocque** [comment]
This is a Node bug, and was fixed here: https://github.com/nodejs/node/pull/54526

**Comment by lucasmengarda** [comment]
Thanks bud
