### ISSUE TITLE
Signin failing after re-install the ssl certificate

### ISSUE THREAD

**Issue by loremine** [firebase/firebase-js-sdk#8616]
### Operating System

ubuntu

### Environment (if applicable)

Chrome Version 129.0.6668.100 (Official Build) (64-bit)

### Firebase SDK Version

10.13.2

### Firebase SDK Product(s)

Auth

### Project Tooling

Front-end app built with NuxtJS 3, Back end app built with express js. Both apps are running in docker containers, and have an extra container for certbot. I am using Lets encrypt's certificate.

### Detailed Problem Description

My app is integrated with the firebase authentication service and have features for Google and Microsoft logins. Recently i have re-installed my app (re-installed ssl certificates too) in server as part of a new a release, after the release the sign in with google and microsoft functionalities are not working. I am using signInWithPopup method and i have tried to replace it with signInWithRedirect function but the call back function getRedirectResult is not getting the data.

**Here is the error when pop being automatically closed.**
```
FirebaseError: Firebase: Error (auth/popup-closed-by-user).
    at Te (1npBjZnL.js:31:754)
    at p (1npBjZnL.js:31:66)
    at 1npBjZnL.js:871:1473
```
**Note:** The sign in functionalities are working in localhost and without https in server too.

### Steps and code to reproduce issue

Re-install the ssl certificate and try to login using microsoft or google

**Comment by hsubox76** [comment]
> My app is integrated with the firebase authentication service and have features for Google and Microsoft logins. Recently i have re-installed my app (re-installed ssl certificates too) in server as part of a new a release, after the release the sign in with google and microsoft functionalities are not working. I am using signInWithPopup method and i have tried to replace it with signInWithRedirect function but the call back function getRedirectResult is not getting the data.

If I'm understanding correctly, the app was working before, and the only thing that has changed is that you re-uploaded your app to the server and reinstalled certificates, and you didn't change your version of the Firebase SDK. Is there anything that indicates this is a bug in the Firebase SDK? Did you update the Firebase SDK version with this release as well? Does a previous version of the Firebase SDK work? If so, which version?

If there isn't a strong indication this is an SDK bug (for example, if you can find a previous version of the SDK where this problem doesn't happen, that would indicate a bug has been introduced, or if you have additional information that leads you to believe the problem in the SDK) I would suggest talking to [Firebase Support](https://firebase.google.com/support) to narrow the problem down.

**Comment by loremine** [comment]
> hsubox76

Thanks for the response, I recently updated Firebase from 9.18.0 to 10.13.2, and the application was working fine afterward. The issue occurred when reinstalling the app and SSL certificates in the development server. In order to debug the issue, I removed https from the development server and it resolved the issue. **FYI:**  I created the app one year ago, but I'm still using the same OAuth client id for the Google and Microsoft apps for the sign in method configuration. Could this issue be related to these settings?

**Comment by hsubox76** [comment]
The fact there wasn't a problem during the SDK version upgrade seems to indicate this wasn't caused by a bug in the SDK. I would suggest contacting [Firebase Support](https://firebase.google.com/support) to try to narrow down the issue, which seems to lie outside the SDK. It could be an issue with the certificates or it could be an issue with your Firebase provider configs - support might be able to help figure that out.

Let us know if there's anything else you're seeing that points to an SDK issue and we can reopen this.

**Comment by loremine** [comment]
@hsubox76 Thanks
